var tableauQuestion = [
    {   question : "Estas por pasar el área residencial o comercial a más de 100 km/h, ¿que haces?",
        propositionA : "Aceleras y alcanzas los 120km/h",
        propositionB : "Mantenes la velocidad sin adelantar a otros vehículos",
        propositionC : "Reducis a 80km/h",
        propositionD : "Mantenes una velocidad de 100 km/h",
        reponse : "C"},

    {   question : "Si estás pasando un semáforo y ves un peaton caminando, ¿qué haces?",
        propositionA : "Atropellas al peatón",
        propositionB : "Puteas al peatón",
        propositionC : "Esperas a que el peatón cruce",
        propositionD : "Le disparas al peatón y huis",
        reponse : "C"},

    {   question : "Cuando no hay indicación, la velocidad máxima permitida en una zona residencial es de: __ km/h",
        propositionA : "60",
        propositionB : "80",
        propositionC : "40",
        propositionD : "120",
        reponse : "A"},

  {   question : "Antes de cambiar de carril debes:",
        propositionA : "Revisa los espejos",
        propositionB : "Comprobar puntos ciegos",
        propositionC : "Señalas tus intenciones",
        propositionD : "Todas las anteriores",
        reponse : "D"},

  {   question : "Venis manejando en la ciudad y tenes ganas de ir al baño, cual seria tu reaccion? ",
        propositionA : "Dejas el auto tirado en el medio de la calle y salis corriendo hacia un arbusto",
        propositionB : "Apretas las nalgas y lo metes para adentro hasta llegar a tu casa",
        propositionC : "Estacionas bien y vas a una estacion de servicio",
        propositionD : "Te haces encima",
        reponse : "C"},

  {   question : "Estas con el semaforo en verde, se te acerca un limpia vidrios a limpiarte el auto mientras te tocan bocina, como reaccionas?",
        propositionA : "Lo rajas a puteadas",
        propositionB : "Le entregas la billetera y a tu mujer",
        propositionC : "Le decis que no porque estas obstruyendo el paso del resto",
        propositionD : "Le decis que lo limpie tranquilo y que el resto espere",
        reponse : "C"},

  {   question : "Venis manejando en la avenida y ves a una persona atractiva, que haces?",
        propositionA : "Le miras el culo",
        propositionB : "Le haces seña de luces",
        propositionC : "Le gritas algun pirobo ordinario",
        propositionD : "Ignoras y seguis concentrado en el trafico",
        reponse : "D"},

  {   question : "Estas manejando y te llega un whatsapp, que deberias hacer?",
        propositionA : "Lo respondes y de paso haces videollamada mientras manejas",
        propositionB : "Te estacionas para agarrar el celular y contestas",
        propositionC : "Dejas que suene e ignoras el llamado",
        propositionD : "B y C son correctas",
        reponse : "D"},

  {   question : "Usted esta conduciendo en una via libre en la que el limite de velocidad es de 110km/h. La mayoria de los vehiculos estan viajando a 120 km/h, por lo que debe conducir no mas que a:",
        propositionA : "110km/h",
        propositionB : "80km/h",
        propositionC : "20km/h",
        propositionD : "50km/h",
        reponse : "A"},

  {   question : "Viene un ciclista que quiere cruzar, que haces?",
        propositionA : "Le das el paso por ser el vehiculo de menor porte",
        propositionB : "Le decis que las calzas le quedan para el orto",
        propositionC : "Lo atropellas y te llevas la bici para venderla en Marketplace",
        propositionD : "Le corres una carrera",
        reponse : "A"},
]
