Config.Vehicles = {

    -- Vehicle Copy of https://github.com/qbcore-framework/qb-core/blob/main/shared.lua
	-- CUSTOM VEHICLES
	-- https://github.com/PLOKMJNB/FiveM-Civ-Car-Pack
	-- All Custom Cars preconfigured here is from that repo.
    ['18s560'] = {
        brand = "Mercedes Benz",
        shop = "pdm",
        model = "18s560",
        price = 350000,
        category = "Sedan",
        name = "2018 Mercedez Benz s560",
        hash = -338562743,
    },

    ['fiat'] = {
        brand = "Fiat",
        shop = "pdm",
        model = "fiat",
        price = 30000,
        category = "Compacto",
        name = "Fiat 147",
        hash = -338562743,
    },
    
    ['180sx'] = {
        brand = "Nissan",
        shop = "pdm",
        model = "180sx",
        price = 250000,
        category = "Deportivo",
        name = "Nissan 180sx",
        hash = -338562743,
    },

    ['350z'] = {
        brand = "Nissan",
        shop = "pdm",
        model = "350z",
        price = 260000,
        category = "Deportivo",
        name = "Nissan 350z",
        hash = -338562743,
    },

    ['206fn'] = {
        brand = "Peugeot",
        shop = "pdm",
        model = "206fn",
        price = 100000,
        category = "Compacto",
        name = "Peugeot 206",
        hash = -338562743,
    },

    ['370z16'] = {
        brand = "Nissan",
        shop = "pdm",
        model = "370z16",
        price = 300000,
        category = "Deportivo",
        name = "Nissan 370z",
        hash = -338562743,
    },

    ['405slxfn'] = {
        brand = "Peugeot",
        shop = "pdm",
        model = "405slxfn",
        price = 130000,
        category = "Sedan",
        name = "Peugeot 405",
        hash = -338562743,
    },

    ['500abarth'] = {
        brand = "Fiat",
        shop = "pdm",
        model = "500abarth",
        price = 250000,
        category = "Compacto",
        name = "Fiat 500 Abarth",
        hash = -338562743,
    },

    ['504'] = {
        brand = "Peugeot",
        shop = "pdm",
        model = "504",
        price = 120000,
        category = "Compacto",
        name = "Peugeot 504",
        hash = -338562743,
    },

    ['760li20'] = {
        brand = "BMW",
        shop = "pdm",
        model = "760li20",
        price = 550000,
        category = "Sedan",
        name = "BMW 760li XDrive",
        hash = -338562743,
    },

    ['amarok'] = {
        brand = "Volkswagen",
        shop = "pdm",
        model = "Amarok",
        price =300000,
        category = "Camioneta",
        name = "Volkswagen Amarok V6 Tdi",
        hash = -338562743,
    },

    ['2013rs7'] = {
        brand = "Audi",
        shop = "pdm",
        model = "2013rs7",
        price = 650000,
        category = "Deportivo",
        name = "Audi Rs7 2013",
        hash = -338562743,
    },

    ['M4cs'] = {
        brand = "BMW",
        shop = "pdm",
        model = "M4cs",
        price = 540000,
        category = "Deportivo",
        name = "BMW M4 Coupe",
        hash = -338562743,
    },

    ['bmw8mm'] = {
        brand = "BMW",
        shop = "pdm",
        model = "bmw8mm",
        price = 640000,
        category = "Deportivo",
        name = "BMW M8",
        hash = -338562743,
    },

    ['bmci'] = {
        brand = "BMW",
        shop = "pdm",
        model = "bmci",
        price = 620000,
        category = "Deportivo",
        name = "BMW M5",
        hash = -338562743,
    },

    ['brz13'] = {
        brand = "Subaru",
        shop = "pdm",
        model = "brz13",
        price = 315000,
        category = "Deportivo",
        name = "Subaru Brz",
        hash = -338562743,
    },

    ['m2f22'] = {
        brand = "BMW",
        shop = "pdm",
        model = "m2f22",
        price = 450000,
        category = "Deportivo",
        name = "Bmw M2 F22",
        hash = -338562743,
    },

    ['16ss'] = {
        brand = "Chevrolet",
        shop = "pdm",
        model = "16ss",
        price = 350000,
        category = "Deportivo",
        name = "Chevrolet Camaro 2016",
        hash = -338562743,
    },

    ['trhawk'] = {
        brand = "Jeep",
        shop = "pdm",
        model = "trhawk",
        price = 900000,
        category = "Compacto",
        name = "Jeep Cherokee TrailHawk",
        hash = -338562743,
    },

    ['boricua'] = {
        brand = "Volkswagen",
        shop = "pdm",
        model = "boricua",
        price = 220000,
        category = "Sedan",
        name = "Volkswagen Bora",
        hash = -338562743,
    },

    ['celgt4'] = {
        brand = "Toyota",
        shop = "pdm",
        model = "celgt4",
        price = 295000,
        category = "Deportivo",
        name = "Toyota Celica GT4",
        hash = -338562743,
    },

    ['2cv6naj'] = {
        brand = "Citroën",
        shop = "pdm",
        model = "2cv6naj",
        price = 50000,
        category = "Compacto",
        name = "Citroën 2cv",
        hash = -338562743,
    },

    ['ek9'] = {
        brand = "Honda",
        shop = "pdm",
        model = "ek9",
        price = 230000,
        category = "Compacto",
        name = "Honda Civic Ek9",
        hash = -338562743,
    },

    ['civic'] = {
        brand = "Honda",
        shop = "pdm",
        model = "civic",
        price = 220000,
        category = "Sedan",
        name = "Honda Civic 5",
        hash = -338562743,
    },

    ['clio'] = {
        brand = "Renault",
        shop = "pdm",
        model = "clio",
        price = 230000,
        category = "Compacto",
        name = "Renault Clio Williams",
        hash = -338562743,
    },

    ['civiccoupe'] = {
        brand = "Honda",
        shop = "pdm",
        model = "civiccoupe",
        price = 190000,
        category = "Deportivo",
        name = "Honda Civic Coupe 1999",
        hash = -338562743,
    },

    ['2017chiron'] = {
        brand = "Bugatti",
        shop = "pdm",
        model = "2017chiron",
        price = 4500000,
        category = "Super",
        name = "Bugatti Chiron 2017",
        hash = -338562743,
    },

    ['clio2ph25'] = {
        brand = "Renault",
        shop = "pdm",
        model = "clio2ph25",
        price = 175000,
        category = "Compacto",
        name = "Renault Clio 2",
        hash = -338562743,
    },

    ['corsa'] = {
        brand = "Chevrolet",
        shop = "pdm",
        model = "corsa",
        price = 179000,
        category = "Sedan",
        name = "Chevrolet Corsa Gls",
        hash = -338562743,
    },

    ['c7'] = {
        brand = "Chevrolet",
        shop = "pdm",
        model = "c7",
        price = 590000,
        category = "Deportivo",
        name = "Chevrolet Corvette C7",
        hash = -338562743,
    },

    ['corvettec5z06'] = {
        brand = "Chevrolet",
        shop = "pdm",
        model = "corvettec5z06",
        price = 380000,
        category = "Deportivo",
        name = "Chevrolet C5",
        hash = -338562743,
    },

    ['bencongt13'] = {
        brand = "Bentley",
        shop = "pdm",
        model = "bencongt13",
        price = 340000,
        category = "Deportivo",
        name = "Bentley Continental GT",
        hash = -338562743,
    },

    ['cobaltss'] = {
        brand = "Chevrolet",
        shop = "pdm",
        model = "cobaltss",
        price = 240000,
        category = "Sedan",
        name = "Chevrolet Colbalt ss",
        hash = -338562743,
    },

    ['chrxfire'] = {
        brand = "Chrysler",
        shop = "pdm",
        model = "chrxfire",
        price = 370000,
        category = "Deportivo",
        name = "Chrysley Crossfire",
        hash = -338562743,
    },

    ['corolla'] = {
        brand = "Toyota",
        shop = "pdm",
        model = "corolla",
        price = 210000,
        category = "Sedan",
        name = "Toyota Corolla",
        hash = -338562743,
    },

    ['eclipsegt06'] = {
        brand = "Mitsubishi",
        shop = "pdm",
        model = "eclipsegt06",
        price = 260000,
        category = "Compacto",
        name = "Mitsubishi Eclipse GT 06",
        hash = -338562743,
    },

    ['KAPCAI2'] = {
        brand = "Honda",
        shop = "pdm",
        model = "KAPCAI2",
        price = 20000,
        category = "Moto",
        name = "Honda Econo C90",
        hash = -338562743,
    },

    ['f8spider'] = {
        brand = "Ferrari",
        shop = "pdm",
        model = "f8spider",
        price = 950000,
        category = "Super",
        name = "Ferrari Tributo F8 Spider",
        hash = -338562743,
    },

    ['sv'] = {
        brand = "Lamborghini",
        shop = "pdm",
        model = "sv",
        price = 850000,
        category = "Super",
        name = "Lamborghini Diablo",
        hash = -338562743,
    },

    ['fiat1300'] = {
        brand = "Fiat",
        shop = "pdm",
        model = "fiat1300",
        price = 120000,
        category = "Compacto",
        name = "Fiat 1300",
        hash = -338562743,
    },

    ['fiat600'] = {
        brand = "Fiat",
        shop = "pdm",
        model = "fiat600",
        price = 70000,
        category = "Compacto",
        name = "Fiat 600",
        hash = -338562743,
    },

    ['xls'] = {
        brand = "Honda",
        shop = "pdm",
        model = "xls",
        price = 170000,
        category = "Compacto",
        name = "Honda Fit",
        hash = -338562743,
    },

    ['blista'] = {
        brand = "Ford",
        shop = "pdm",
        model = "blista",
        price = 180000,
        category = "Compacto",
        name = "Ford Escort XR3",
        hash = -338562743,
    },

    ['fordka'] = {
        brand = "Ford",
        shop = "pdm",
        model = "fordka",
        price = 170000,
        category = "Compacto",
        name = "Ford Ka",
        hash = -338562743,
    },

    ['fluencetmspec'] = {
        brand = "Renault",
        shop = "pdm",
        model = "fluencetmspec",
        price = 200000,
        category = "Sedan",
        name = "Renault Fluence GT",
        hash = -338562743,
    },

    ['fe86'] = {
        brand = "Ford",
        shop = "pdm",
        model = "fe86",
        price = 210000,
        category = "Compacto",
        name = "Ford Escort",
        hash = -338562743,
    },

    ['buffalo'] = {
        brand = "Ford",
        shop = "pdm",
        model = "buffalo",
        price = 180000,
        category = "Compacto",
        name = "Ford Taunus",
        hash = -338562743,
    },

    ['glendale'] = {
        brand = "Volkswagen",
        shop = "pdm",
        model = "glendale",
        price = 195000,
        category = "Compacto",
        name = "Volkswagen Fox 2016",
        hash = -338562743,
    },

    ['gt17'] = {
        brand = "Ford",
        shop = "pdm",
        model = "gt17",
        price = 1000000,
        category = "Super",
        name = "Ford GT 2017",
        hash = -338562743,
    },

    ['f100'] = {
        brand = "Ford",
        shop = "pdm",
        model = "f100",
        price = 150000,
        category = "Camioneta",
        name = "Ford F100",
        hash = -338562743,
    },

    ['blista3'] = {
        brand = "Renault",
        shop = "pdm",
        model = "blista3",
        price = 170000,
        category = "Compacto",
        name = "Renault Fuego",
        hash = -338562743,
    },

    ['testarossa'] = {
        brand = "Ferrari",
        shop = "pdm",
        model = "testarossa",
        price = 400000,
        category = "Super",
        name = "Ferrari Testarrosa",
        hash = -338562743,
    },

    ['G632021'] = {
        brand = "Mercedes Benz",
        shop = "pdm",
        model = "G632021",
        price = 400000,
        category = "Camioneta",
        name = "Mercedes Benz G63",
        hash = -338562743,
    },

    ['fto'] = {
        brand = "Mitsubishi",
        shop = "pdm",
        model = "FTO",
        price = 240000,
        category = "Deportivo",
        name = "Mitsubishi FTO Coupe",
        hash = -338562743,
    },

    ['golfgti7'] = {
        brand = "Volkswagen",
        shop = "pdm",
        model = "golfgti7",
        price = 300000,
        category = "Compacto",
        name = "Vokswagen MK7 GTI",
        hash = -338562743,
    },

    ['golf4'] = {
        brand = "Volkswagen",
        shop = "pdm",
        model = "golf4",
        price = 200000,
        category = "Compacto",
        name = "Volkswagen Golf MK4",
        hash = -338562743,
    },

    ['gencoupe'] = {
        brand = "Hyundai",
        shop = "pdm",
        model = "gencoupe",
        price = 270000,
        category = "Deportivo",
        name = "Genesis Coupe",
        hash = -338562743,
    },

    ['hilux'] = {
        brand = "Toyota",
        shop = "pdm",
        model = "hilux",
        price = 280000,
        category = "Camioneta",
        name = "Toyota Hilux 4x4 Turbo",
        hash = -338562743,
    },

    ['mk3vr6'] = {
        brand = "Volkswagen",
        shop = "pdm",
        model = "mk3vr6",
        price = 230000,
        category = "Compacto",
        name = "Volkswagen Golf MK3 VR6",
        hash = -338562743,
    },

    ['gtr'] = {
        brand = "Nissan",
        shop = "pdm",
        model = "gtr",
        price = 550000,
        category = "Deportivo",
        name = "Nissan GTR R35",
        hash = -338562743,
    },

    ['hellcat15w'] = {
        brand = "Dodge",
        shop = "pdm",
        model = "hellcat15w",
        price = 300000,
        category = "Deportivo",
        name = "Dodge Hellcat",
        hash = -338562743,
    },

    ['mitsugto'] = {
        brand = "Mitsubishi",
        shop = "pdm",
        model = "mitsugto",
        price = 340000,
        category = "Deportivo",
        name = "Mitsubishi GTO",
        hash = -338562743,
    },

    ['fordhv2'] = {
        brand = "Ford",
        shop = "pdm",
        model = "fordhv2",
        price = 450000,
        category = "Deportivo",
        name = "Ford Hoonicorn Hv2",
        hash = -338562743,
    },

    ['cooperworks'] = {
        brand = "Mini",
        shop = "pdm",
        model = "cooperworks",
        price = 280000,
        category = "Compacto",
        name = "Mini Cooper",
        hash = -338562743,
    },

    ['jeep2012'] = {
        brand = "Jeep",
        shop = "pdm",
        model = "jeep2012",
        price = 300000,
        category = "Camioneta",
        name = "Jeep Wrangler",
        hash = -338562743,
    },

    ['jeepreneg'] = {
        brand = "Jeep",
        shop = "pdm",
        model = "jeepreneg",
        price = 320000,
        category = "Camioneta",
        name = "Jeep Renegade",
        hash = -338562743,
    },

    ['bc'] = {
        brand = "Pagani",
        shop = "pdm",
        model = "bc",
        price = 800000,
        category = "Super",
        name = "Huayra",
        hash = -338562742,
    },

    ['cont88'] = {
        brand = "Lamborghini",
        shop = "pdm",
        model = "cont88",
        price = 850000,
        category = "Super",
        name = "Lamborghini Countach",
        hash = -338562743,
    },

    ['evo9'] = {
        brand = "Mitsubishi",
        shop = "pdm",
        model = "evo9",
        price = 330000,
        category = "Deportivo",
        name = "Mitsubishi Evo 9",
        hash = -338562743,
    },

    ['laguna'] = {
        brand = "Renault",
        shop = "pdm",
        model = "laguna",
        price = 230000,
        category = "Sedan",
        name = "Renault Laguna",
        hash = -338562743,
    },

    ['lhuracan'] = {
        brand = "Lamborghini",
        shop = "pdm",
        model = "lhuracan",
        price = 900000,
        category = "Super",
        name = "Lamboghini Huracan",
        hash = -338562743,
    },

    ['lc500'] = {
        brand = "Lexus",
        shop = "pdm",
        model = "lc500",
        price = 450000,
        category = "Deportivo",
        name = "Lexus LC 500",
        hash = -338562743,
    },

    ['seatleon'] = {
        brand = "Seat",
        shop = "pdm",
        model = "seatleon",
        price = 300000,
        category = "Compacto",
        name = "Seat Leon",
        hash = -338562743,
    },

    ['evo3'] = {
        brand = "Mitsubishi",
        shop = "pdm",
        model = "evo3",
        price = 500000,
        category = "Deportivo",
        name = "Mitsubishi Evo 3",
        hash = -338562743,
    },

    ['lbdy01'] = {
        brand = "Lamborghini",
        shop = "pdm",
        model = "lbdy01",
        price = 4000000,
        category = "Super",
        name = "Lamborghini Veneno",
        hash = -338562743,
    },

    ['lgss'] = {
        brand = "Lamborghini",
        shop = "pdm",
        model = "lgss",
        price = 500000,
        category = "Super",
        name = "Lamborghini Gallardo",
        hash = -338562743,
    },

    ['m3f80'] = {
        brand = "BMW",
        shop = "pdm",
        model = "m3f80",
        price = 380000,
        category = "Deportivo",
        name = "BMW M3 F80",
        hash = -338562743,
    },

    ['m3e36'] = {
        brand = "BMW",
        shop = "pdm",
        model = "m3e36",
        price = 310000,
        category = "Deportivo",
        name = "BMW M3 E36",
        hash = -338562743,
    },

    ['m3e30'] = {
        brand = "BMW",
        shop = "pdm",
        model = "m3e30",
        price = 260000,
        category = "Deportivo",
        name = "BMW M3 E30",
        hash = -338562743,
    },

    ['m8gte'] = {
        brand = "BMW",
        shop = "pdm",
        model = "m8gte",
        price = 600000,
        category = "Deportivo",
        name = "BMW M8 GTE",
        hash = -338562743,
    },

    ['e60'] = {
        brand = "BMW",
        shop = "pdm",
        model = "e60",
        price = 380000,
        category = "Deportivo",
        name = "BMW M5 E60",
        hash = -338562743,
    },

    ['macla'] = {
        brand = "Mercedes Benz",
        shop = "pdm",
        model = "macla",
        price = 340000,
        category = "Sedan",
        name = "Mercedes Benz Clase A",
        hash = -338562743,
    },

    ['brabus'] = {
        brand = "Mercedes Benz",
        shop = "pdm",
        model = "brabus",
        price = 650000,
        category = "Camioneta",
        name = "Mercedes Benz Brabus",
        hash = -338562743,
    },

    ['gt63samg'] = {
        brand = "Mercedes Benz",
        shop = "pdm",
        model = "gt63samg",
        price = 500000,
        category = "Deportivo",
        name = "Mercedes Benz GT63 amg",
        hash = -338562743,
    },

    ['p1'] = {
        brand = "McLaren",
        shop = "pdm",
        model = "p1",
        price = 1200000,
        category = "Super",
        name = "McLaren P1",
        hash = -338562743,
    },

    ['senna'] = {
        brand = "McLaren",
        shop = "pdm",
        model = "senna",
        price = 900000,
        category = "Super",
        name = "McLaren Senna",
        hash = -338562743,
    },
    ['mgrantur2010'] = {
        brand = "Maserati",
        shop = "pdm",
        model = "mgrantur2010",
        price = 800000,
        category = "Deportivo",
        name = "Maserati Gran Turismo",
        hash = -338562743,
    },

    ['na6'] = {
        brand = "Mazda",
        shop = "pdm",
        model = "na6",
        price = 220000,
        category = "Deportivo",
        name = "Mazda Miata Mx-5",
        hash = -338562743,
    },
    ['models'] = {
        brand = "Tesla",
        shop = "pdm",
        model = "models",
        price = 1500000,
        category = "Sedan",
        name = "Tesla Model S",
        hash = -338562743,
    },
    ['teslax'] = {
        brand = "Tesla",
        shop = "pdm",
        model = "teslax",
        price = 1000000,
        category = "Sedan",
        name = "Tesla Model X",
        hash = -338562743,
    },
    ['mondeo'] = {
        brand = "Ford",
        shop = "pdm",
        model = "mondeo",
        price = 280000,
        category = "Sedan",
        name = "Ford Mondeo",
        hash = -338562743,
    },
    ['rmodmustang'] = {
        brand = "Ford",
        shop = "pdm",
        model = "rmodmustang",
        price = 380000,
        category = "Deportivo",
        name = "Ford Mustang GT Boss",
        hash = -338562743,
    },
    ['boss302'] = {
        brand = "Ford",
        shop = "pdm",
        model = "boss302",
        price = 200000,
        category = "Deportivo",
        name = "Ford Boss 302",
        hash = -338562743,
    },
    ['urban'] = {
        brand = "LADA",
        shop = "pdm",
        model = "urban",
        price = 165000,
        category = "Camioneta",
        name = "LADA Niva 4x4",
        hash = -338562743,
    },
    ['p911r'] = {
        brand = "Porsche",
        shop = "pdm",
        model = "p911r",
        price = 660000,
        category = "Deportivo",
        name = "Porsche 911 R",
        hash = -338562743,
    },
    ['judge'] = {
        brand = "Pontiac",
        shop = "pdm",
        model = "judge",
        price = 230000,
        category = "Deportivo",
        name = "Pontiac GTO",
        hash = -338562743,
    },
    ['punto'] = {
        brand = "Fiat",
        shop = "pdm",
        model = "Punto",
        price = 170000,
        category = "Compacto",
        name = "Fiat Punto",
        hash = -338562743,
    },
    ['prius'] = {
        brand = "Toyota",
        shop = "pdm",
        model = "Prius",
        price = 180000,
        category = "Compacto",
        name = "Toyota Prius",
        hash = -338562743,
    },
    ['r8ppi'] = {
        brand = "Audi",
        shop = "pdm",
        model = "r8ppi",
        price = 1050000,
        category = "Super",
        name = "Audi R8",
        hash = -338562743,
    },
    ['r33'] = {
        brand = "Nissan",
        shop = "pdm",
        model = "r33",
        price = 280000,
        category = "Deportivo",
        name = "Nissan Skyline R33",
        hash = -338562743,
    },
    ['ram2500'] = {
        brand = "Dodge",
        shop = "pdm",
        model = "ram2500",
        price = 300000,
        category = "Camioneta",
        name = "Dodge Ram 2500",
        hash = -338562743,
    },
    ['ranger2019'] = {
        brand = "Ford",
        shop = "pdm",
        model = "ranger2019",
        price = 320000,
        category = "Camioneta",
        name = "Ford Ranger",
        hash = -338562743,
    },
    ['rmodsupra'] = {
        brand = "Toyota",
        shop = "pdm",
        model = "rmodsupra",
        price = 370000,
        category = "Deportivo",
        name = "Supra MK4 II",
        hash = -338562743,
    },
    ['rs4avant'] = {
        brand = "Audi",
        shop = "pdm",
        model = "rs4avant",
        price = 300000,
        category = "Sedan",
        name = "Rs4 Avant",
        hash = -338562743,
    },
    ['renault4'] = {
        brand = "Renault",
        shop = "pdm",
        model = "renault4",
        price = 90000,
        category = "Compacto",
        name = "Renault 4",
        hash = -338562743,
    },
    ['rs318'] = {
        brand = "Audi",
        shop = "pdm",
        model = "rs318",
        price = 320000,
        category = "Compacto",
        name = "Audi Rs3",
        hash = -338562743,
    },
    ['scirocco'] = {
        brand = "Volkswagen",
        shop = "pdm",
        model = "scirocco",
        price = 280500,
        category = "Compacto",
        name = "Volkswagen Scirocco",
        hash = -338562743,
    },
    ['sierra'] = {
        brand = "Ford",
        shop = "pdm",
        model = "sierra",
        price = 200000,
        category = "Compacto",
        name = "Ford Sierra",
        hash = -338562743,
    },
    ['hs2000'] = {
        brand = "Honda",
        shop = "pdm",
        model = "hs2000",
        price = 230000,
        category = "Deportivo",
        name = "Honda S2000",
        hash = -338562743,
    },
    ['skyline'] = {
        brand = "Nissan",
        shop = "pdm",
        model = "skyline",
        price = 400000,
        category = "Deportivo",
        name = "Nissan Skyline R34",
        hash = -338562743,
    },
    ['toysupmk4'] = {
        brand = "Toyota",
        shop = "pdm",
        model = "toysupmk4",
        price = 420000,
        category = "Deportivo",
        name = "Toyota Supra MK4",
        hash = -338562743,
    },
    ['silvias15'] = {
        brand = "Nissan",
        shop = "pdm",
        model = "silvias15",
        price = 230000,
        category = "Deportivo",
        name = "Nissan Silvia S15",
        hash = -338562743,
    },
    ['wrx15'] = {
        brand = "Subaru",
        shop = "pdm",
        model = "WRX15",
        price = 230000,
        category = "Sedan",
        name = "Subaru WRX",
        hash = -338562743,
    },
    ['fortwo'] = {
        brand = "Smart",
        shop = "pdm",
        model = "ForTwo",
        price = 160000,
        category = "Compacto",
        name = "Smart For Two",
        hash = -338562743,
    },
    ['tesroad20'] = {
        brand = "Tesla",
        shop = "pdm",
        model = "tesroad20",
        price = 6000000,
        category = "Sedan",
        name = "Tesla Roadster",
        hash = -338562743,
    },
    ['ae86'] = {
        brand = "Toyota",
        shop = "pdm",
        model = "ae86",
        price = 240000,
        category = "Compacto",
        name = "Toyota Trueno ae86",
        hash = -338562743,
    },
    ['triton'] = {
        brand = "Mitsubishi",
        shop = "pdm",
        model = "triton",
        price = 500000,
        category = "Camioneta",
        name = "Mitsubishi Triton",
        hash = -338562743,
    },
    ['trx'] = {
        brand = "Dodge",
        shop = "pdm",
        model = "trx",
        price = 550000,
        category = "Camioneta",
        name = "Dodge Ram TRX",
        hash = -338562743,
    },
    ['veln'] = {
        brand = "Hyundai",
        shop = "pdm",
        model = "veln",
        price = 280000,
        category = "Compacto",
        name = "Hyundai Veloster",
        hash = -338562743,
    },
    ['suran'] = {
        brand = "Volkswagen",
        shop = "pdm",
        model = "suran",
        price = 190000,
        category = "Compacto",
        name = "Volkswagen Suran",
        hash = -338562743,
    },
    ['aventador'] = {
        brand = "Lamborghini",
        shop = "pdm",
        model = "Aventador",
        price = 700000,
        category = "Super",
        name = "Lamborghini Aventador",
        hash = -338562743,
    },
    ['raptor2017'] = {
        brand = "Ford",
        shop = "pdm",
        model = "raptor2017",
        price = 400000,
        category = "Camioneta",
        name = "Ford Raptor F150",
        hash = -338562743,
    },
    ['vip8'] = {
        brand = "Dodge",
        shop = "pdm",
        model = "Vip8",
        price = 370000,
        category = "Deportivo",
        name = "Dodge Viper",
        hash = -338562743,
    },
    ['bugatti'] = {
        brand = "Bugatti",
        shop = "pdm",
        model = "bugatti",
        price = 3000000,
        category = "Super",
        name = "Bugatti Veyron",
        hash = -338562743,
    },
    ['polo'] = {
        brand = "Volkswagen",
        shop = "pdm",
        model = "Polo",
        price = 190000,
        category = "Compacto",
        name = "Volkswagen Polo",
        hash = -338562743,
    },
    ['virtus'] = {
        brand = "Volkswagen",
        shop = "pdm",
        model = "Virtus",
        price = 240000,
        category = "Sedan",
        name = "Volkswagen Polo Largo",
        hash = -338562743,
    },
    ['volvoiron'] = {
        brand = "Volvo",
        shop = "pdm",
        model = "volvoiron",
        price = 1000000,
        category = "Camion",
        name = "Volvo Iron Knight",
        hash = -338562743,
    },
    ['romeo155'] = {
        brand = "Alfa Romeo",
        shop = "pdm",
        model = "romeo155",
        price = 200000,
        category = "Sedan",
        name = "Alfa Romeo 155",
        hash = -338562743,
    },
    
    ['208gti'] = {
        brand = "Peugeot",
        shop = "pdm",
        model = "208 GTI",
        price = 380000,
        category = "Sedan",
        name = "Peugeot 208 GTI",
        hash = -338562743,
    },

    ['stratum'] = {
        brand = "Chevrolet",
        shop = "pdm",
        model = "stratum",
        price = 160000,
        category = "Sedan",
        name = "Chevrolet Astra",
        hash = -338562743,
    },

    ['habanero'] = {
        brand = "Chevrolet",
        shop = "pdm",
        model = "habanero",
        price = 160000,
        category = "Sedan",
        name = "Chevrolet Agile",
        hash = -338562743,
    },

    ['minivan'] = {
        brand = "Citroën",
        shop = "pdm",
        model = "minivan",
        price = 160000,
        category = "Sedan",
        name = "Citroen Berlingo",
        hash = -338562743,
    },

    ['captur'] = {
        brand = "Renault",
        shop = "pdm",
        model = "captur",
        price = 190000,
        category = "Sedan",
        name = "Renaut Captur",
        hash = -338562743,
    },

    ['celta'] = {
        brand = "Chevrolet",
        shop = "pdm",
        model = "celta",
        price = 200000,
        category = "Sedan",
        name = "Chevrolet Celta",
        hash = -338562743,
    },

    ['cruze'] = {
        brand = "Chevrolet",
        shop = "pdm",
        model = "cruze",
        price = 220000,
        category = "Sedan",
        name = "Chevrolet Cruze",
        hash = -338562743,
    },

    ['fiorino'] = {
        brand = "Fiat",
        shop = "pdm",
        model = "fiorino",
        price = 175000,
        category = "Sedan",
        name = "Fiat Fiorino",
        hash = -338562743,
    },

    ['baller'] = {
        brand = "Renault",
        shop = "pdm",
        model = "baller",
        price = 170000,
        category = "Sedan",
        name = "Renault Duster",
        hash = -338562743,
    },

    ['f430'] = {
        brand = "Ferrari",
        shop = "pdm",
        model = "f430",
        price = 1500000,
        category = "Deportivo",
        name = "Ferrari F430",
        hash = -338562743,
    },

    ['dilettante'] = {
        brand = "Fiat",
        shop = "pdm",
        model = "dilettante",
        price = 170000,
        category = "Sedan",
        name = "Fiat Tipo",
        hash = -338562743,
    },

    ['emperor'] = {
        brand = "Fiat",
        shop = "pdm",
        model = "emperor",
        price = 140000,
        category = "Sedan",
        name = "Fiat Palio",
        hash = -338562743,
    },

    ['focus2003'] = {
        brand = "Ford",
        shop = "pdm",
        model = "focus2003",
        price = 300000,
        category = "Sedan",
        name = "Ford Focus 2003",
        hash = -338562743,
    },

    ['golfmk6'] = {
        brand = "Volkswagen",
        shop = "pdm",
        model = "golfmk6",
        price = 210000,
        category = "Sedan",
        name = "Volkswagen Golf MK6 R",
        hash = -338562743,
    },

    ['moonbeam'] = {
        brand = "Renault",
        shop = "pdm",
        model = "moonbeam",
        price = 160000,
        category = "Sedan",
        name = "Renault Kangoo",
        hash = -338562743,
    },

    ['youga'] = {
        brand = "Renault",
        shop = "pdm",
        model = "youga",
        price = 150500,
        category = "Sedan",
        name = "Renault Master",
        hash = -338562743,
    },

    ['primo2'] = {
        brand = "Chevrolet",
        shop = "pdm",
        model = "primo2",
        price = 170000,
        category = "Sedan",
        name = "Chevrolet Onix",
        hash = -338562743,
    },

    ['startechrr1'] = {
        brand = "RangeRover",
        shop = "pdm",
        model = "startechrr1",
        price = 570000,
        category = "Camioneta",
        name = "Range Rover Startech RR1",
        hash = -338562743,
    },

    ['emperor2'] = {
        brand = "Renault",
        shop = "pdm",
        model = "emperor2",
        price = 160000,
        category = "Sedan",
        name = "Renault 11",
        hash = -338562743,
    },

    ['twingo'] = {
        brand = "Renault",
        shop = "pdm",
        model = "twingo",
        price = 190000,
        category = "Sedan",
        name = "twingo",
        hash = -338562743,
    },

    ['sentra'] = {
        brand = "Nissan",
        shop = "pdm",
        model = "sentra",
        price = 230000,
        category = "Sedan",
        name = "Nissan Sentra",
        hash = -338562743,
    },

    ['nissantitan17'] = {
        brand = "Nissan",
        shop = "pdm",
        model = "nissantitan17",
        price = 600000,
        category = "Sedan",
        name = "Nissan Titan",
        hash = -338562743,
    },

    ['jetta'] = {
        brand = "Volkswagen",
        shop = "pdm",
        model = "jetta",
        price = 250000,
        category = "Sedan",
        name = "Volkswagen Vento",
        hash = -338562743,
    },

    ['307c'] = {
        brand = "Peugeot",
        shop = "pdm",
        model = "307c",
        price = 220000,
        category = "Sedan",
        name = "Peugeot 307C",
        hash = -338562743,
    },

    ['porrs73'] = {
        brand = "Porsche",
        shop = "pdm",
        model = "porrs73",
        price = 400000,
        category = "Sedan",
        name = "Porsche 911 Carrera 1973",
        hash = -338562743,
    },

    ['pgt3rs19'] = {
        brand = "Porsche",
        shop = "pdm",
        model = "pgt3rs19",
        price = 700000,
        category = "Sedan",
        name = "Porsche 911 GT3",
        hash = -338562743,
    },

    ['gxgiulia'] = {
        brand = "Alfa Romeo",
        shop = "pdm",
        model = "gxgiulia",
        price = 270000,
        category = "Sedan",
        name = "Alfa Romeo GX Giulia",
        hash = -338562743,
    },

    ['850'] = {
        brand = "BMW",
        shop = "pdm",
        model = "850",
        price = 300000,
        category = "Sedan",
        name = "BMW 850CSI 1995",
        hash = -338562743,
    },

    ['70zr1'] = {
        brand = "Chevrolet",
        shop = "pdm",
        model = "70zr1",
        price = 300000,
        category = "Sedan",
        name = "Chevrolet Corvette C3",
        hash = -338562743,
    },

    ['tico'] = {
        brand = "Daewoo",
        shop = "pdm",
        model = "tico",
        price = 150000,
        category = "Sedan",
        name = "Daewoo Tico",
        hash = -338562743,
    },

    ['gxevoviii'] = {
        brand = "Mitsubishi",
        shop = "pdm",
        model = "gxevoviii",
        price = 370000,
        category = "Sedan",
        name = "Mitsubishi EVO 8",
        hash = -338562743,
    },

    ['focusrs'] = {
        brand = "Ford",
        shop = "pdm",
        model = "focusrs",
        price = 300000,
        category = "Sedan",
        name = "Ford Focus RS",
        hash = -338562743,
    },

    ['16challenger'] = {
        brand = "Dodge",
        shop = "pdm",
        model = "16challenger",
        price = 340000,
        category = "Sedan",
        name = "Dodge Challenger 2016",
        hash = -338562743,
    },

    ['hilux1'] = {
        brand = "Toyota",
        shop = "pdm",
        model = "hilux1",
        price = 290000,
        category = "Sedan",
        name = "Toyota Hilux",
        hash = -338562743,
    },

    ['na1'] = {
        brand = "Honda",
        shop = "pdm",
        model = "na1",
        price = 300000,
        category = "Sedan",
        name = "Honda NSX R1",
        hash = -338562743,
    },

    ['22b'] = {
        brand = "Subaru",
        shop = "pdm",
        model = "22b",
        price = 300000,
        category = "Sedan",
        name = "Subaru Impresa 22b",
        hash = -338562743,
    },

    ['lfa'] = {
        brand = "Lexus",
        shop = "pdm",
        model = "lfa",
        price = 800000,
        category = "Sedan",
        name = "Lexus LFA",
        hash = -338562743,
    },

    ['mazrx7fb'] = {
        brand = "Mazda",
        shop = "pdm",
        model = "mazrx7fb",
        price = 260000,
        category = "Sedan",
        name = "Mazda RX7 FB",
        hash = -338562743,
    },

    ['mcf1'] = {
        brand = "McLaren",
        shop = "pdm",
        model = "mcf1",
        price = 2000000,
        category = "Sedan",
        name = "Mclaren F1",
        hash = -338562743,
    },

    ['z32'] = {
        brand = "Nissan",
        shop = "pdm",
        model = "z32",
        price = 280000,
        category = "Sedan",
        name = "Nissan 300ZX",
        hash = -338562743,
    },

    ['peugeot404'] = {
        brand = "Peugeot",
        shop = "pdm",
        model = "peugeot404",
        price = 130000,
        category = "Sedan",
        name = "Peugeot 404",
        hash = -338562743,
    },

    ['bnr32'] = {
        brand = "Nissan",
        shop = "pdm",
        model = "bnr32",
        price = 360000,
        category = "Sedan",
        name = "Nissan GTR R32",
        hash = -338562743,
    },

    ['rmodi8mlb'] = {
        brand = "BMW",
        shop = "pdm",
        model = "rmodi8mlb",
        price = 450000,
        category = "Sedan",
        name = "BMW I8",
        hash = -338562743,
    },

    ['gxrx7'] = {
        brand = "Mazda",
        shop = "pdm",
        model = "gxrx7",
        price = 360000,
        category = "Sedan",
        name = "Mazda RX7",
        hash = -338562743,
    },

    ['rx8r'] = {
        brand = "Mazda",
        shop = "pdm",
        model = "rx8r",
        price = 310000,
        category = "Sedan",
        name = "Mazda RX8",
        hash = -338562743,
    },

    ['gxs14'] = {
        brand = "Nissan",
        shop = "pdm",
        model = "gxs14",
        price = 280000,
        category = "Sedan",
        name = "Nissan Silvia S14",
        hash = -338562743,
    },

    ['gxa90'] = {
        brand = "Toyota",
        shop = "pdm",
        model = "gxa90",
        price = 610000,
        category = "Sedan",
        name = "Toyota Supra MK5",
        hash = -338562743,
    },

    ['uptsi'] = {
        brand = "Volkswagen",
        shop = "pdm",
        model = "uptsi",
        price = 160000,
        category = "Sedan",
        name = "Volkswagen Up!",
        hash = -338562743,
    },
    
    ['cd69'] = {
        brand = "Chevrolet",
        shop = "pdm",
        model = "cd69",
        price = 320000,
        category = "Sedan",
        name = "Chevrolet Nova",
        hash = -338562743,
    },

    ['cb500f'] = {
        brand = "Honda",
        shop = "pdm",
        model = "cb500f",
        price = 180000,
        category = "Moto",
        name = "Honda Cb500f",
        hash = -338562743,
    },

    ['m1000rr'] = {
        brand = "BMW",
        shop = "pdm",
        model = "m1000rr",
        price = 700000,
        category = "moto",
        name = "BMW m1000rr",
        hash = -338562743,
    },

    ['f4rr'] = {
        brand = "MV Agusta",
        shop = "pdm",
        model = "f4RR",
        price = 630000,
        category = "moto",
        name = "MV Agusta F4 RR",
        hash = -338562743,
    },

    ['biz25'] = {
        brand = "Honda",
        shop = "pdm",
        model = "biz25",
        price = 160000,
        category = "moto",
        name = "Honda Biz 125",
        hash = -338562743,
    },

    ['bmws19'] = {
        brand = "BMW",
        shop = "pdm",
        model = "bmws19",
        price = 710000,
        category = "moto",
        name = "BMW S1000RR",
        hash = -338562743,
    },

    ['mv2019'] = {
        brand = "MV Agusta",
        shop = "pdm",
        model = "mv2019",
        price = 680000,
        category = "moto",
        name = "MV Agusta Brutale 1000",
        hash = -338562743,
    },

    ['blazer2'] = {
        brand = "Can-Am",
        shop = "pdm",
        model = "blazer2",
        price = 40000,
        category = "moto",
        name = "Can-Am 250",
        hash = -338562743,
    },

    ['cb650r'] = {
        brand = "Honda",
        shop = "pdm",
        model = "cb650r",
        price = 340500,
        category = "moto",
        name = "Honda CB650R",
        hash = -338562743,
    },

    ['cbr1000rrr'] = {
        brand = "Honda",
        shop = "pdm",
        model = "cbr1000rrr",
        price = 690000,
        category = "moto",
        name = "Honda CBR 1000RR",
        hash = -338562743,
    },

    ['cbtwister'] = {
        brand = "Honda",
        shop = "pdm",
        model = "cbtwister",
        price = 240000,
        category = "moto",
        name = "Honda Twister 250",
        hash = -338562743,
    },

    ['f131'] = {
        brand = "Taller Carlos",
        shop = "pdm",
        model = "f131",
        price = 400500,
        category = "moto",
        name = "Confederate Hellcat",
        hash = -338562743,
    },

    ['cr85'] = {
        brand = "Honda",
        shop = "pdm",
        model = "cr85",
        price = 140500,
        category = "moto",
        name = "Honda CR 85",
        hash = -338562743,
    },

    ['crf450r1'] = {
        brand = "Honda",
        shop = "pdm",
        model = "crf450r1",
        price = 255500,
        category = "moto",
        name = "Honda CRF 450R",
        hash = -338562743,
    },

    ['desmo'] = {
        brand = "Ducati",
        shop = "pdm",
        model = "desmo",
        price = 1400000,
        category = "moto",
        name = "Ducati Desmosedici",
        hash = -338562743,
    },

    ['diavel'] = {
        brand = "Ducati",
        shop = "pdm",
        model = "diavel",
        price = 590000,
        category = "moto",
        name = "Ducati Diavel",
        hash = -338562743,
    },

    ['superlag12'] = {
        brand = "Ducati",
        shop = "pdm",
        model = "superlag12",
        price = 800000,
        category = "moto",
        name = "Ducati Panigale 1299 Superleggera",
        hash = -338562743,
    },

    ['2020excsm'] = {
        brand = "KTM",
        shop = "pdm",
        model = "2020excsm",
        price = 260000,
        category = "moto",
        name = "KTM EXC450",
        hash = -338562743,
    },

    ['exc530sm'] = {
        brand = "KTM",
        shop = "pdm",
        model = "exc530sm",
        price = 200000,
        category = "moto",
        name = "KTM 530",
        hash = -338562743,
    },

    ['srad'] = {
        brand = "Suzuki",
        shop = "pdm",
        model = "srad",
        price = 460000,
        category = "moto",
        name = "Suzuki GSX-R750",
        hash = -338562743,
    },

    ['gsxr19'] = {
        brand = "Suzuki",
        shop = "pdm",
        model = "gsxr19",
        price = 600000,
        category = "moto",
        name = "Suzuki GSX- R1000R",
        hash = -338562743,
    },

    ['hayabusa'] = {
        brand = "Suzuki",
        shop = "pdm",
        model = "hayabusa",
        price = 1200000,
        category = "moto",
        name = "Suzuki Hayabusa",
        hash = -338562743,
    },

    ['breakout'] = {
        brand = "Harley Davidson",
        shop = "pdm",
        model = "breakout",
        price = 350000,
        category = "moto",
        name = "Harley Davidson Breakout",
        hash = -338562743,
    },

    ['twincamcus'] = {
        brand = "Harley Davidson",
        shop = "pdm",
        model = "twincamcus",
        price = 300000,
        category = "moto",
        name = "Harley Davidson Custom",
        hash = -338562743,
    },

    ['hdiron883'] = {
        brand = "Harley Davidson",
        shop = "pdm",
        model = "hdiron883",
        price = 260000,
        category = "moto",
        name = "Harley Davidson 883 Iron",
        hash = -338562743,
    },

    ['goldwing'] = {
        brand = "Honda",
        shop = "pdm",
        model = "goldwing",
        price = 320000,
        category = "moto",
        name = "Honda Goldwing 1800",
        hash = -338562743,
    },

    ['hypermotard'] = {
        brand = "Ducati",
        shop = "pdm",
        model = "hypermotard",
        price = 270000,
        category = "moto",
        name = "Ducati Hypermotard",
        hash = -338562743,
    },

    ['indiancdh'] = {
        brand = "Indian",
        shop = "pdm",
        model = "indiancdh",
        price = 250000,
        category = "moto",
        name = "Indian Chief Dark Horse",
        hash = -338562743,
    },

    ['katana2'] = {
        brand = "Suzuki",
        shop = "pdm",
        model = "katana2",
        price = 400000,
        category = "moto",
        name = "Suzuki Katana",
        hash = -338562743,
    },

    ['kr150'] = {
        brand = "Honda",
        shop = "pdm",
        model = "kr150",
        price = 300000,
        category = "moto",
        name = "Honda KR 150",
        hash = -338562743,
    },

    ['ksd'] = {
        brand = "KTM",
        shop = "pdm",
        model = "ksd",
        price = 420000,
        category = "moto",
        name = "KTM Super Duke 1290",
        hash = -338562743,
    },

    ['ktmsm'] = {
        brand = "KTM",
        shop = "pdm",
        model = "ktmsm",
        price = 260000,
        category = "moto",
        name = "KTM 450sx f",
        hash = -338562743,
    },

    ['smc690'] = {
        brand = "KTM",
        shop = "pdm",
        model = "smc690",
        price = 320000,
        category = "moto",
        name = "KTM 690R",
        hash = -338562743,
    },

    ['bati'] = {
        brand = "Taller Carlos",
        shop = "pdm",
        model = "bati",
        price = 180000,
        category = "moto",
        name = "Mini Moto",
        hash = -338562743,
    },

    ['sanchez'] = {
        brand = "Taller Carlos",
        shop = "pdm",
        model = "sanchez",
        price = 150000,
        category = "moto",
        name = "Mini Moto",
        hash = -338562743,
    },

    ['150'] = {
        brand = "Honda",
        shop = "pdm",
        model = "150",
        price = 140000,
        category = "moto",
        name = "Honda CG Titan 150",
        hash = -338562743,
    },

    ['mt03'] = {
        brand = "Yamaha",
        shop = "pdm",
        model = "mt03",
        price = 280500,
        category = "moto",
        name = "Yamaha MT 03",
        hash = -338562743,
    },

    ['fz07'] = {
        brand = "Yamaha",
        shop = "pdm",
        model = "fz07",
        price = 330000,
        category = "moto",
        name = "Yamaha MT 07",
        hash = -338562743,
    },

    ['mt10'] = {
        brand = "Yamaha",
        shop = "pdm",
        model = "mt10",
        price = 460000,
        category = "moto",
        name = "Yamaha MT 10",
        hash = -338562743,
    },

    ['hondanc750s'] = {
        brand = "Honda",
        shop = "pdm",
        model = "hondanc750s",
        price = 380000,
        category = "moto",
        name = "Honda NC 750s",
        hash = -338562743,
    },

    ['nh2r'] = {
        brand = "Kawasaki",
        shop = "pdm",
        model = "nh2r",
        price = 2000000,
        category = "moto",
        name = "Kawasaki H2R",
        hash = -338562743,
    },

    ['ninja300'] = {
        brand = "Kawasaki",
        shop = "pdm",
        model = "ninja300",
        price = 260000,
        category = "moto",
        name = "Kawasaki Ninja 300",
        hash = -338562743,
    },

    ['gs1200'] = {
        brand = "BMW",
        shop = "pdm",
        model = "gs1200",
        price = 550000,
        category = "moto",
        name = "BMW GS 1200r",
        hash = -338562743,
    },

    ['r1250r'] = {
        brand = "BMW",
        shop = "pdm",
        model = "r1250r",
        price = 400000,
        category = "moto",
        name = "BMW R 1250R",
        hash = -338562743,
    },

    ['rc213vs'] = {
        brand = "Honda",
        shop = "pdm",
        model = "rc213vs",
        price = 1400000,
        category = "moto",
        name = "Honda RCV 213S",
        hash = -338562743,
    },

    ['ktmrc39019'] = {
        brand = "KTM",
        shop = "pdm",
        model = "ktmrc39019",
        price = 290500,
        category = "moto",
        name = "KTM RC 390",
        hash = -338562743,
    },

    ['rc'] = {
        brand = "KTM",
        shop = "pdm",
        model = "rc",
        price = 160500,
        category = "moto",
        name = "KTM RC 200",
        hash = -338562743,
    },

    ['2020rmz'] = {
        brand = "Suzuki",
        shop = "pdm",
        model = "2020rmz",
        price = 240000,
        category = "moto",
        name = "Suzuki RMZ 450",
        hash = -338562743,
    },

    ['tmax'] = {
        brand = "Yamaha",
        shop = "pdm",
        model = "tmax",
        price = 200000,
        category = "moto",
        name = "Yamaha TMax 500",
        hash = -338562743,
    },

    ['blazer'] = {
        brand = "Honda",
        shop = "pdm",
        model = "blazer",
        price = 34500,
        category = "moto",
        name = "Honda TRX 450",
        hash = -338562743,
    },

    ['yzfsm'] = {
        brand = "Yamaha",
        shop = "pdm",
        model = "yzfsm",
        price = 220000,
        category = "moto",
        name = "Yamaha YZ 450f",
        hash = -338562743,
    },

    ['14r1'] = {
        brand = "Yamaha",
        shop = "pdm",
        model = "14r1",
        price = 715000,
        category = "moto",
        name = "Yamaha YZF R1",
        hash = -338562743,
    },

    ['r6'] = {
        brand = "Yamaha",
        shop = "pdm",
        model = "r6",
        price = 520500,
        category = "moto",
        name = "Yamaha YZF R6",
        hash = -338562743,
    },

    ['zh2'] = {
        brand = "Kawasaki",
        shop = "pdm",
        model = "zh2",
        price = 450000,
        category = "moto",
        name = "Kawasaki Zh2",
        hash = -338562743,
    },

    ['zx10r'] = {
        brand = "Kawasaki",
        shop = "pdm",
        model = "zx10r",
        price = 625000,
        category = "moto",
        name = "Kawasaki ZX-10 R",
        hash = -338562743,
    },

    ['yzfr7'] = {
        brand = "Yamaha",
        shop = "pdm",
        model = "yzfr7",
        price = 365000,
        category = "moto",
        name = "Yamaha YZF R7",
        hash = -338562743,
    },

    ['rmzsm'] = {
        brand = "Suzuki",
        shop = "pdm",
        model = "rmzsm",
        price = 270500,
        category = "moto",
        name = "Suzuki RMX 450",
        hash = -338562743,
    },

    ['6736'] = {
        brand = "Taller Carlos",
        shop = "pdm",
        model = "cr85",
        price = 90000,
        category = "moto",
        name = "Poronga Antigua",
        hash = -338562743,
    },

    ['2019chiron'] = {
        brand = "Bugatti",
        shop = "pdm",
        model = "2019chiron",
        price = 5000000,
        category = "moto",
        name = "Bugatti Chiron 2019",
        hash = -338562743,
    },

    ['4881'] = {
        brand = "Ferrari",
        shop = "pdm",
        model = "4881",
        price = 1300000,
        category = "moto",
        name = "Ferrari 488",
        hash = -338562743,
    },

    ['enzo'] = {
        brand = "Ferrari",
        shop = "pdm",
        model = "enzo",
        price = 4300000,
        category = "moto",
        name = "Ferrari Enzo",
        hash = -338562743,
    },

    ['fct'] = {
        brand = "Ferrari",
        shop = "pdm",
        model = "fct",
        price = 1600000,
        category = "moto",
        name = "Ferrari California",
        hash = -338562743,
    },

    ['dtdfenyrlb'] = {
        brand = "Lycan",
        shop = "pdm",
        model = "dtdfenyrlb",
        price = 4300000,
        category = "moto",
        name = "Lycan Hyper Sport",
        hash = -338562743,
    },

    ['240sxhr'] = {
        brand = "Honda",
        shop = "pdm",
        model = "240sxhr",
        price = 240000,
        category = "moto",
        name = "Honda SX 240",
        hash = -338562743,
    },

    ['cupra'] = {
        brand = "Leon",
        shop = "pdm",
        model = "cupra",
        price = 580000,
        category = "deportivo",
        name = "Leon Cupra",
        hash = -338562743,
    },

    ['dbxultimate'] = {
        brand = "Aston Martin",
        shop = "pdm",
        model = "dbxultimate",
        price = 650000,
        category = "deportivo",
        name = "Aston Martin DBX Ultimate",
        hash = -338562743,
    },

    ['GODzMBG900'] = {
        brand = "Mercedes Benz",
        shop = "pdm",
        model = "GODzMBG900",
        price = 700000,
        category = "camioneta",
        name = "Mercedes Benz Maybach",
        hash = -338562743,
    },

    ['gcmpanameratst21'] = {
        brand = "Porsche",
        shop = "pdm",
        model = "gcmpanameratst21",
        price = 4300000,
        category = "deportivo",
        name = "Porsche Panamera",
        hash = -338562743,
    },

    ['divo'] = {
        brand = "Bugatti",
        shop = "pdm",
        model = "divo",
        price = 8000000,
        category = "superdeportivo",
        name = "Bugatti Divo",
        hash = -338562743,
    },

    ['600ltmso'] = {
        brand = "McLaren",
        shop = "pdm",
        model = "600ltmso",
        price = 1400000,
        category = "superdeportivo",
        name = "McLaren 600lts",
        hash = -338562743,
    },

    ['760li20'] = {
        brand = "McLaren",
        shop = "pdm",
        model = "760li20",
        price = 1350000,
        category = "moto",
        name = "McLaren 760",
        hash = -338562743,
    },

}

exports('VehiclesTable', function()
    return Config.Vehicles
end)