Citizen.CreateThread(function()
    AddTextEntry('evija', 'Lotus')
    AddTextEntry('agerars', 'Agera')
    AddTextEntry('amgone', 'AMG One')
    AddTextEntry('dbsr', 'Super leggera')
    AddTextEntry('oycval', 'Aston Martin Valhalla')
    AddTextEntry('VictorHirot', 'Aston Martin Hirot')
    AddTextEntry('r8ppi', 'Audi R8')
    AddTextEntry('audir8lms2', 'Audi R8 LMS')
    AddTextEntry('avent700', 'Aventador')
    AddTextEntry('bbentayga', 'Bentley Bentayga')
    AddTextEntry('ben17', 'Bentley')
    AddTextEntry('m4comp', 'BMW M4 custom')
    AddTextEntry('bt62r', 'Brabham 62R')
    AddTextEntry('bcss', 'Bugatti Chiron Sport')
    AddTextEntry('div', 'Bugatti Divo')
    AddTextEntry('bugatti', 'Bugatti Veyron')
    AddTextEntry('chiron17', 'Bugatti Chiron')
    AddTextEntry('contgt20c', 'Bentley GT')
    AddTextEntry('widebodyled', 'Dodge Charger custom')
    AddTextEntry('488', 'Ferrari 488')
    AddTextEntry('aperta', 'Ferrari Aperta')
    AddTextEntry('gtc4', 'Ferrari GTC')
    AddTextEntry('ff50', 'Ferrari F50')
    AddTextEntry('mgt17', 'Mansory')
    AddTextEntry('gt2rsmr', 'Porsche GT2R')
    AddTextEntry('huracandyred_xxb', 'Lamborghini Huracan')
    AddTextEntry('jesko', 'JESKO')
    AddTextEntry('lp580', 'Lamborghini lp580')
    AddTextEntry('lhgt3', 'Huracan GT3')
    AddTextEntry('venenor', 'Veneno')
    AddTextEntry('ocnlamtmc', 'Lamborghini Termill')
    AddTextEntry('ldsv', 'Lamborghini Diablo')
    AddTextEntry('lgss', 'Lamborghini LGSS')
    AddTextEntry('stradale18', 'Maserati Stradale')
    AddTextEntry('675lt', 'Mc Laren 675')
    AddTextEntry('zoom', 'Mulliner')
    AddTextEntry('murc640', 'Lamborghini murcielago')
    AddTextEntry('mvisiongt', 'Vision GT')
    AddTextEntry('entity11', 'Entity')
    AddTextEntry('Imola', 'Pagani Imola')
    AddTextEntry('porcgt03', 'Porsche GT 03')
    AddTextEntry('63lb', 'Turbo S')
    AddTextEntry('r8v10', 'Audi R8V10')
    AddTextEntry('reventonr', 'Lamborghini Reventon')
    AddTextEntry('RollsRoyceCP', 'Rolls Royce')
    AddTextEntry('rrphantom', 'Rolls royce Phantom')
    AddTextEntry('selva', 'Selva')
    AddTextEntry('sennagtr', 'Mc Laren Senna GTR')
    AddTextEntry('stingraywb', 'Corvette Stringray WB')
    AddTextEntry('brz', 'BRZ')
    AddTextEntry('tempestaes', 'Pegassi Tempestaes')
    AddTextEntry('tesroad20', 'Tesla Readster')
    AddTextEntry('trailcat', 'Jeep Trailcat')
    AddTextEntry('cbr1000rrr', 'CBR 1000RRR')
    AddTextEntry('dv4r', 'DUCATI')
    AddTextEntry('h2carb', 'H2 Carbon')
    AddTextEntry('s1000rr', 'S1000rr')
    AddTextEntry('gsxr19', 'Suzuki GSX 1000r')
    AddTextEntry('hvrod', 'Terminator')
    AddTextEntry('yzfr6', 'Yzfr6')
    AddTextEntry('zx10r', 'Zx10r')
    AddTextEntry('fxxk2', 'Ferrari FXXK2')
    AddTextEntry('cc1', 'cc1')
    AddTextEntry('hycadem8', 'BMW M8')
    AddTextEntry('xxxxx', 'Mercedes 6x6 AMG')
    AddTextEntry('2ncsgt63s', 'Taxi')
    AddTextEntry('765ltmso', 'Camion')
    AddTextEntry('911venom', 'Camion')
    AddTextEntry('adr8', 'Maserati same')
    AddTextEntry('AmgGtrLight', 'Moto same')
    AddTextEntry('bentaygaplsd', 'Moto meca')
    AddTextEntry('c7', 'Grúa meca')
    AddTextEntry('caliburn', 'Auto escuela')
    AddTextEntry('chironsupersport22', 'Moto rappi')
    AddTextEntry('drehycadeviper', 'Dodge Viper')
    AddTextEntry('furai', 'Furia')
    AddTextEntry('gcmlamboultimae', 'Lamborghini ultimate')
    AddTextEntry('gmcev2', 'Hummer 6x6')
    AddTextEntry('GODzLBAVENTADOR', 'Lamborghini Aventador')
    AddTextEntry('kia', 'Camión basura')
    AddTextEntry('laferrari17', 'Ferrari Aperta CC')
    AddTextEntry('lambolb', 'Lamborghini Light')
    AddTextEntry('mbc', 'Mercedes Prototype')
    AddTextEntry('models', 'Tels Model S')
    AddTextEntry('nh2r', 'Kawawsaki ninja')
    AddTextEntry('p1', 'Mc Laren P1')
    AddTextEntry('rmodchiron300', 'Bugatti Chiron')
    AddTextEntry('STO', 'Lamborghini STO')
    AddTextEntry('topcar911', 'Porsche 911 TOP')
    AddTextEntry('torofeo', 'Lamborghini L')
    AddTextEntry('2012gtr', 'GTR Racing')
    AddTextEntry('458it', 'Ferrari 458')
    AddTextEntry('812mnsry', 'Ferrari 812')
    AddTextEntry('f488pista', 'Ferrari 488')
    AddTextEntry('gto', 'Ferrari GTO')
    AddTextEntry('lw458s', 'Ferrari RR')
    AddTextEntry('gtr', 'GTR')
    AddTextEntry('huayra', 'Pagani Huayra')
    AddTextEntry('wraithb', 'Rolls Royce THB')
    AddTextEntry('f8spider', 'Ferrari 8 Spider')  
    AddTextEntry('mustangbkit', 'Mustang 2014')
    AddTextEntry('stingray', 'Corvette Stingray')
    AddTextEntry('yzrm19', 'YZRM 19')
    AddTextEntry('510', 'Fiat 128')
    AddTextEntry('chevfleetf8', 'Chevrolet Toretto')
    AddTextEntry('cycloneex0', 'Cycloneex')
    AddTextEntry('escalade', 'Cadillac Escalade')
    AddTextEntry('fnfdaytona', 'Daytona FR')
    AddTextEntry('fordDriftFF3', 'Mustang FF')
    AddTextEntry('fxxkevoTT', 'Evo TT')
    AddTextEntry('HDIron883', 'Harley Davidson Iron')
    AddTextEntry('jesko2020', 'Jesko 2022')
    AddTextEntry('mansoryveyron', 'Bugatti Veyron')
    AddTextEntry('mvisiongt', 'Mercedes Vision GT')
    AddTextEntry('onyxwraith', 'Rolls Royce ONYX')
    AddTextEntry('oycval', 'Aston Martin Valquirie')
    AddTextEntry('plymouthgtxf8', 'Playmouth GTX')
    AddTextEntry('plymouthrrff7', 'Playmouth GTX FF7')
    AddTextEntry('porcgt03', 'Porsche Carrera GT')
    AddTextEntry('rainpriskdivo', 'Bugatti Divo V2')
    AddTextEntry('supersport', 'Super Sport')
    AddTextEntry('Tecnica', 'Lamborghini técnica')
    AddTextEntry('tesroad20', 'Tesla Roadster 20')
    AddTextEntry('veyronbb', 'Bugatti Veyron BB')
    AddTextEntry('veyronjc', 'Bugatti Veyron JC')
    AddTextEntry('x3sianr21', 'Lamborghini Cyan')
    AddTextEntry('x321c21', 'C21')
    AddTextEntry('Evoque', 'Evoque')
end)
