Config.Vehicles = {

    -- Vehicle Copy of https://github.com/qbcore-framework/qb-core/blob/main/shared.lua
	-- CUSTOM VEHICLES
	-- https://github.com/PLOKMJNB/FiveM-Civ-Car-Pack
	-- All Custom Cars preconfigured here is from that repo.
    -- LOCAL VEHICLES
	['ab19gt500'] = {
		['name'] = 'Ford Mustang GT500',
		['brand'] = 'vip',
		['model'] = 'ab19gt500',
		['price'] = 195000,
		['category'] = 'vip',
		['hash'] = `ab19gt500`,
		['shop'] = 'pdm',
	},
	['abbcss'] = {
		['name'] = 'Bugatti Chiron g',
		['brand'] = 'vip',
		['model'] = 'abbcss',
		['price'] = 5000000,
		['category'] = 'vip',
		['hash'] = `abbcss`,
		['shop'] = 'pdm',
	},
	['abcan'] = {
		['name'] = 'Can Am',
		['brand'] = 'vip',
		['model'] = 'abcan',
		['price'] = 950000,
		['category'] = 'vip',
		['hash'] = `abcan`,
		['shop'] = 'pdm',
	},
	['abccc8'] = {
		['name'] = 'Corvette',
		['brand'] = 'vip',
		['model'] = 'abccc8',
		['price'] = 6000000,
		['category'] = 'vip',
		['hash'] = `abccc8`,
		['shop'] = 'pdm',
	},
	['abdbx'] = {
		['name'] = 'Astron Martin DBX',
		['brand'] = 'vip',
		['model'] = 'abdbx',
		['price'] = 900000,
		['category'] = 'vip',
		['hash'] = `abdbx`,
		['shop'] = 'pdm',
	},
	['abdtype'] = {
		['name'] = 'Carita',
		['brand'] = 'vip',
		['model'] = 'abdtype',
		['price'] = 5500000,
		['category'] = 'vip',
		['hash'] = `abdtype`,
		['shop'] = 'pdm',
	},
	['abf8t'] = {
		['name'] = 'Ferrari Tributo',
		['brand'] = 'vip',
		['model'] = 'abf8t',
		['price'] = 7500000,
		['category'] = 'vip',
		['hash'] = `abf8t`,
		['shop'] = 'pdm',
	},
	['abfe86'] = {
		['name'] = 'Sscort RS Turbo',
		['brand'] = 'vip',
		['model'] = 'abfe86',
		['price'] = 1200000,
		['category'] = 'vip',
		['hash'] = `abfe86`,
		['shop'] = 'pdm',
	},
	['abff50'] = {
		['name'] = 'Ferrari F50',
		['brand'] = 'vip',
		['model'] = 'abff50',
		['price'] = 1600000,
		['category'] = 'vip',
		['hash'] = `abff50`,
		['shop'] = 'pdm',
	},
	['abgsf'] = {
		['name'] = 'Lexus Sport S+',
		['brand'] = 'vip',
		['model'] = 'abgsf',
		['price'] = 2100000,
		['category'] = 'vip',
		['hash'] = `abgsf`,
		['shop'] = 'pdm',
	},
	['abit18'] = {
		['name'] = 'Italdesign',
		['brand'] = 'vip',
		['model'] = 'abit18',
		['price'] = 1800000,
		['category'] = 'vip',
		['hash'] = `abit18`,
		['shop'] = 'pdm',
	},
	['ablrrr'] = {
		['name'] = 'Range Rover',
		['brand'] = 'vip',
		['model'] = 'ablrrr',
		['price'] = 1200000,
		['category'] = 'vip',
		['hash'] = `ablrrr`,
		['shop'] = 'pdm',
	},
	
	-- AUTOS REALES --
	
	
	['405glxfn'] = {
		['name'] = 'Peugeot 405',
		['brand'] = 'autoreal',
		['model'] = '405glxfn',
		['price'] = 1100000,
		['category'] = 'autoreal',
		['hash'] = `405glxfn`,
		['shop'] = 'pdm',
	},
	
	['golf4'] = {
		['name'] = 'Golf 4',
		['brand'] = 'autoreal',
		['model'] = 'golf4',
		['price'] = 1200000,
		['category'] = 'autoreal',
		['hash'] = `golf4`,
		['shop'] = 'pdm',
	},
	['golfgti'] = {
		['name'] = 'Golf GTI',
		['brand'] = 'autoreal',
		['model'] = 'golfgti',
		['price'] = 2500000,
		['category'] = 'autoreal',
		['hash'] = `golfgti`,
		['shop'] = 'pdm',
	},
	['160'] = {
		['name'] = 'Titan 160',
		['brand'] = 'autoreal',
		['model'] = '160',
		['price'] = 800000,
		['category'] = 'autoreal',
		['hash'] = `160`,
		['shop'] = 'pdm',
	},
	['750li'] = {
		['name'] = 'BMW 750li',
		['brand'] = 'autoreal',
		['model'] = '750li',
		['price'] = 2600000,
		['category'] = 'autoreal',
		['hash'] = `750li`,
		['shop'] = 'pdm',
	},
	
	['abmonza'] = {
		['name'] = 'Ferrari Monza SP2',
		['brand'] = 'autoreal',
		['model'] = 'abmonza',
		['price'] = 25000000,
		['category'] = 'autoreal',
		['hash'] = `abmonza`,
		['shop'] = 'pdm',
	},
	['abpgt2'] = {
		['name'] = 'Porsche GT2 RS',
		['brand'] = 'autoreal',
		['model'] = 'abpgt2',
		['price'] = 1900000,
		['category'] = 'autoreal',
		['hash'] = `abpgt2`,
		['shop'] = 'pdm',
	},
	['abpgt3'] = {
		['name'] = 'Porsche GT3 RS',
		['brand'] = 'autoreal',
		['model'] = 'abpgt3',
		['price'] = 1900000,
		['category'] = 'autoreal',
		['hash'] = `abpgt3`,
		['shop'] = 'pdm',
	},
	['abamcj'] = {
		['name'] = 'Charger',
		['brand'] = 'autoreal',
		['model'] = 'abamcj',
		['price'] = 300000,
		['category'] = 'autoreal',
		['hash'] = `abamcj`,
		['shop'] = 'pdm',
	},
	['abpm19'] = {
		['name'] = 'Porsche',
		['brand'] = 'autoreal',
		['model'] = 'abpm19',
		['price'] = 1500000,
		['category'] = 'autoreal',
		['hash'] = `abpm19`,
		['shop'] = 'pdm',
	},
	['abpor968'] = {
		['name'] = 'Porsche Turbo S',
		['brand'] = 'autoreal',
		['model'] = 'abpor968',
		['price'] = 320000,
		['category'] = 'autoreal',
		['hash'] = `abpor968`,
		['shop'] = 'pdm',
	},
	['absl65bs'] = {
		['name'] = 'Mercedes benz SL 65',
		['brand'] = 'autoreal',
		['model'] = 'absl65bs',
		['price'] = 6000000,
		['category'] = 'autoreal',
		['hash'] = `absl65bs`,
		['shop'] = 'pdm',
	},
	['abss69'] = {
		['name'] = 'Charger 2',
		['brand'] = 'autoreal',
		['model'] = 'abss69',
		['price'] = 100000,
		['category'] = 'autoreal',
		['hash'] = `abss69`,
		['shop'] = 'pdm',
	},
	['abvip8'] = {
		['name'] = 'Dogde Viper',
		['brand'] = 'autoreal',
		['model'] = 'abvip8',
		['price'] = 4100000,
		['category'] = 'autoreal',
		['hash'] = `abvip8`,
		['shop'] = 'pdm',
	},
	['abz48'] = {
		['name'] = 'BMW M',
		['brand'] = 'autoreal',
		['model'] = 'abz48',
		['price'] = 3000000,
		['category'] = 'autoreal',
		['hash'] = `abz48`,
		['shop'] = 'pdm',
	},
	['fiatuno'] = {
		['name'] = 'Fiat uno',
		['brand'] = 'autoreal',
		['model'] = 'fiatuno',
		['price'] = 180000,
		['category'] = 'autoreal',
		['hash'] = `fiatuno`,
		['shop'] = 'pdm',
	},
	['renault4'] = {
		['name'] = 'Renault 4',
		['brand'] = 'autoreal',
		['model'] = 'renault4',
		['price'] = 150000,
		['category'] = 'autoreal',
		['hash'] = `renault4`,
		['shop'] = 'pdm',
	},
	['renault9'] = {
		['name'] = 'Renault 9',
		['brand'] = 'autoreal',
		['model'] = 'renault9',
		['price'] = 200000,
		['category'] = 'autoreal',
		['hash'] = `renault9`,
		['shop'] = 'pdm',
	},
	['rocoto'] = {
		['name'] = 'Fiat Toro',
		['brand'] = 'autoreal',
		['model'] = 'rocoto',
		['price'] = 1600000,
		['category'] = 'autoreal',
		['hash'] = `rocoto`,
		['shop'] = 'pdm',
	},
	['21sierra'] = {
		['name'] = 'GMC Sierra',
		['brand'] = 'autoreal',
		['model'] = '21sierra',
		['price'] = 2500000,
		['category'] = 'autoreal',
		['hash'] = `21sierra`,
		['shop'] = 'pdm',
	},
	
	['208'] = {
		['name'] = '208',
		['brand'] = 'autoreal',
		['model'] = '208',
		['price'] = 1400000,
		['category'] = 'autoreal',
		['hash'] = `208`,
		['shop'] = 'pdm',
	},
	
	['308cc'] = {
		['name'] = '308cc',
		['brand'] = 'autoreal',
		['model'] = '308cc',
		['price'] = 2500000,
		['category'] = 'autoreal',
		['hash'] = `308cc`,
		['shop'] = 'pdm',
	},
	
	['capi20'] = {
		['name'] = 'capi20',
		['brand'] = 'autoreal',
		['model'] = 'capi20',
		['price'] = 2200000,
		['category'] = 'autoreal',
		['hash'] = `capi20`,
		['shop'] = 'pdm',
	},
	
	['fairlane64'] = {
		['name'] = 'fairlane64',
		['brand'] = 'autoreal',
		['model'] = 'fairlane64',
		['price'] = 1250000,
		['category'] = 'autoreal',
		['hash'] = `fairlane64`,
		['shop'] = 'pdm',
	},
	
	['sedan'] = {
		['name'] = 'Sedan',
		['brand'] = 'autoreal',
		['model'] = 'sedan',
		['price'] = 2450000,
		['category'] = 'autoreal',
		['hash'] = `sedan`,
		['shop'] = 'pdm',
	},
	
	['s10'] = {
		['name'] = 'S10',
		['brand'] = 'autoreal',
		['model'] = 's10',
		['price'] = 8000000,
		['category'] = 'autoreal',
		['hash'] = `s10`,
		['shop'] = 'pdm',
	},
	
	['ecosport'] = {
		['name'] = 'Ecosport',
		['brand'] = 'autoreal',
		['model'] = 'ecosport',
		['price'] = 2500000,
		['category'] = 'autoreal',
		['hash'] = `ecosport`,
		['shop'] = 'pdm',
	},
	
	['bora'] = {
		['name'] = 'Bora',
		['brand'] = 'autoreal',
		['model'] = 'bora',
		['price'] = 3650000,
		['category'] = 'autoreal',
		['hash'] = `bora`,
		['shop'] = 'pdm',
	},
	
	['agile'] = {
		['name'] = 'Agile',
		['brand'] = 'autoreal',
		['model'] = 'agile',
		['price'] = 1500000,
		['category'] = 'autoreal',
		['hash'] = `agile`,
		['shop'] = 'pdm',
	},
	
	['huracanmansory'] = {
		['name'] = 'Huracan Mansory',
		['brand'] = 'autoreal',
		['model'] = 'huracanmansory',
		['price'] = 30000000,
		['category'] = 'autoreal',
		['hash'] = `huracanmansory`,
		['shop'] = 'pdm',
	},
	
	['ocnetrongt'] = {
		['name'] = 'Ocnetron GT',
		['brand'] = 'autoreal',
		['model'] = 'ocnetrongt',
		['price'] = 27000000,
		['category'] = 'autoreal',
		['hash'] = `ocnetrongt`,
		['shop'] = 'pdm',
	},
	
	['alphard'] = {
		['name'] = 'Alphard',
		['brand'] = 'autoreal',
		['model'] = 'alphard',
		['price'] = 3500000,
		['category'] = 'autoreal',
		['hash'] = `alphard`,
		['shop'] = 'pdm',
	},
	
	['dtdmansq60'] = {
		['name'] = 'dtdmansq60',
		['brand'] = 'autoreal',
		['model'] = 'dtdmansq60',
		['price'] = 26000000,
		['category'] = 'autoreal',
		['hash'] = `dtdmansq60`,
		['shop'] = 'pdm',
	},
	['rs62'] = {
		['name'] = 'Audi RS62',
		['brand'] = 'autoreal',
		['model'] = 'rs62',
		['price'] = 32000000,
		['category'] = 'autoreal',
		['hash'] = `rs62`,
		['shop'] = 'pdm',
	},
	['rs6+'] = {
		['name'] = 'Audi RS6 +',
		['brand'] = 'autoreal',
		['model'] = 'rs6',
		['price'] = 27000000,
		['category'] = 'autoreal',
		['hash'] = `rs6`,
		['shop'] = 'pdm',
	},
	
	-- OFF ROADS --
	
	['vagrant'] = {
		['name'] = 'Vagrant',
		['brand'] = 'offroads',
		['model'] = 'vagrant',
		['price'] = 450000,
		['category'] = 'offroads',
		['hash'] = `vagrant`,
		['shop'] = 'pdm',
	},
	['virgo3'] = {
		['name'] = 'Virgo',
		['brand'] = 'offroads',
		['model'] = 'virgo3',
		['price'] = 145000,
		['category'] = 'offroads',
		['hash'] = `virgo3`,
		['shop'] = 'pdm',
	},
	['trophytruck'] = {
		['name'] = 'Rally truck',
		['brand'] = 'offroads',
		['model'] = 'trophytruck',
		['price'] = 450000,
		['category'] = 'offroads',
		['hash'] = `trophytruck`,
		['shop'] = 'pdm',
	},
	['bifta'] = {
		['name'] = 'Bifta',
		['brand'] = 'offroads',
		['model'] = 'bifta',
		['price'] = 150000,
		['category'] = 'offroads',
		['hash'] = `bifta`,
		['shop'] = 'pdm',
	},
	['blazer'] = {
		['name'] = 'Blazer',
		['brand'] = 'offroads',
		['model'] = 'blazer',
		['price'] = 125000,
		['category'] = 'offroads',
		['hash'] = `blazer`,
		['shop'] = 'pdm',
	},
	['blazer3'] = {
		['name'] = 'Blazer 3',
		['brand'] = 'offroads',
		['model'] = 'blazer3',
		['price'] = 121000,
		['category'] = 'offroads',
		['hash'] = `blazer3`,
		['shop'] = 'pdm',
	},
	['blazer4'] = {
		['name'] = 'Blazer Sport',
		['brand'] = 'offroads',
		['model'] = 'blazer4',
		['price'] = 185000,
		['category'] = 'offroads',
		['hash'] = `blazer4`,
		['shop'] = 'pdm',
	},
	['outlaw'] = {
		['name'] = 'Outlaw',
		['brand'] = 'offroads',
		['model'] = 'outlaw',
		['price'] = 300000,
		['category'] = 'offroads',
		['hash'] = `outlaw`,
		['shop'] = 'pdm',
	},
	
	-- MUSCLES --
	
	['phoenix'] = {
		['name'] = 'Dytona 2',
		['brand'] = 'muscles',
		['model'] = 'phoenix',
		['price'] = 100001,
		['category'] = 'muscles',
		['hash'] = `phoenix`,
		['shop'] = 'pdm',
	},
	['tampa'] = {
		['name'] = 'Tampa',
		['brand'] = 'muscles',
		['model'] = 'tampa',
		['price'] = 138000,
		['category'] = 'muscles',
		['hash'] = `tampa`,
		['shop'] = 'pdm',
	},
	['vigero'] = {
		['name'] = 'Vigero',
		['brand'] = 'muscles',
		['model'] = 'vigero',
		['price'] = 150000,
		['category'] = 'muscles',
		['hash'] = `vigero`,
		['shop'] = 'pdm',
	},
	['slamvan3'] = {
		['name'] = 'Slamvan 3',
		['brand'] = 'muscles',
		['model'] = 'slamvan3',
		['price'] = 181000,
		['category'] = 'muscles',
		['hash'] = `slamvan3`,
		['shop'] = 'pdm',
	},
	['buccaneer2'] = {
		['name'] = 'Buccaneer 2',
		['brand'] = 'muscles',
		['model'] = 'buccaneer2',
		['price'] = 150000,
		['category'] = 'muscles',
		['hash'] = `buccaneer2`,
		['shop'] = 'pdm',
	},
	['blade'] = {
		['name'] = 'Blade',
		['brand'] = 'muscles',
		['model'] = 'blade',
		['price'] = 250000,
		['category'] = 'muscles',
		['hash'] = `blade`,
		['shop'] = 'pdm',
	},
	['faction2'] = {
		['name'] = 'Faction 2',
		['brand'] = 'muscles',
		['model'] = 'faction2',
		['price'] = 180000,
		['category'] = 'muscles',
		['hash'] = `faction2`,
		['shop'] = 'pdm',
	},
	['nightshade'] = {
		['name'] = 'Nightshade',
		['brand'] = 'muscles',
		['model'] = 'nightshade',
		['price'] = 125000,
		['category'] = 'muscles',
		['hash'] = `nightshade`,
		['shop'] = 'pdm',
	},
	['dukes'] = {
		['name'] = 'Dukes',
		['brand'] = 'muscles',
		['model'] = 'dukes',
		['price'] = 180000,
		['category'] = 'muscles',
		['hash'] = `dukes`,
		['shop'] = 'pdm',
	},
	['gauntlet5'] = {
		['name'] = 'Dytona',
		['brand'] = 'muscles',
		['model'] = 'gauntlet5',
		['price'] = 140050,
		['category'] = 'muscles',
		['hash'] = `gauntlet5`,
		['shop'] = 'pdm',
	},
	['dominator'] = {
		['name'] = 'Dominator',
		['brand'] = 'muscles',
		['model'] = 'dominator',
		['price'] = 250000,
		['category'] = 'muscles',
		['hash'] = `dominator`,
		['shop'] = 'pdm',
	},
	['deviant'] = {
		['name'] = 'Deviant',
		['brand'] = 'muscles',
		['model'] = 'deviant',
		['price'] = 240000,
		['category'] = 'muscles',
		['hash'] = `deviant`,
		['shop'] = 'pdm',
	},
	['chino'] = {
		['name'] = 'Chino',
		['brand'] = 'muscles',
		['model'] = 'chino',
		['price'] = 120000,
		['category'] = 'muscles',
		['hash'] = `chino`,
		['shop'] = 'pdm',
	},
	['clique'] = {
		['name'] = 'Clique',
		['brand'] = 'muscles',
		['model'] = 'clique',
		['price'] = 99999,
		['category'] = 'muscles',
		['hash'] = `clique`,
		['shop'] = 'pdm',
	},
	
	-- VANS --
	
	['speedo'] = {
		['name'] = 'SpeedO2',
		['brand'] = 'vans',
		['model'] = 'speedo',
		['price'] = 1110000,
		['category'] = 'vans',
		['hash'] = `speedo`,
		['shop'] = 'pdm',
	},
	['surfer'] = {
		['name'] = 'Surfer',
		['brand'] = 'vans',
		['model'] = 'surfer',
		['price'] = 76000,
		['category'] = 'vans',
		['hash'] = `surfer`,
		['shop'] = 'pdm',
	},
	['burrito3'] = {
		['name'] = 'Burrito',
		['brand'] = 'vans',
		['model'] = 'burrito3',
		['price'] = 125000,
		['category'] = 'vans',
		['hash'] = `burrito3`,
		['shop'] = 'pdm',
	},
	['bobcatxl'] = {
		['name'] = 'Bobcat XL',
		['brand'] = 'vans',
		['model'] = 'bobcatxl',
		['price'] = 130000,
		['category'] = 'vans',
		['hash'] = `bobcatxl`,
		['shop'] = 'pdm',
	},
	['bison'] = {
		['name'] = 'Bison',
		['brand'] = 'vans',
		['model'] = 'bison',
		['price'] = 245000,
		['category'] = 'vans',
		['hash'] = `bison`,
		['shop'] = 'pdm',
	},
	
	-- SUPERS --
	
	['adder'] = {
		['name'] = 'Bugatti Veyron',
		['brand'] = 'supers',
		['model'] = 'adder',
		['price'] = 2000000,
		['category'] = 'supers',
		['hash'] = `adder`,
		['shop'] = 'pdm',
	},
	['autarch'] = {
		['name'] = 'Autarch',
		['brand'] = 'supers',
		['model'] = 'autarch',
		['price'] = 1350000,
		['category'] = 'supers',
		['hash'] = `autarch`,
		['shop'] = 'pdm',
	},
	['visione'] = {
		['name'] = 'Visione',
		['brand'] = 'supers',
		['model'] = 'visione',
		['price'] = 880000,
		['category'] = 'supers',
		['hash'] = `visione`,
		['shop'] = 'pdm',
	},
	['xa21'] = {
		['name'] = 'Xa 21',
		['brand'] = 'supers',
		['model'] = 'xa21',
		['price'] = 1050000,
		['category'] = 'supers',
		['hash'] = `xa21`,
		['shop'] = 'pdm',
	},
	['tyrus'] = {
		['name'] = 'Tyrus',
		['brand'] = 'supers',
		['model'] = 'tyrus',
		['price'] = 1180000,
		['category'] = 'supers',
		['hash'] = `tyrus`,
		['shop'] = 'pdm',
	},
	['nero'] = {
		['name'] = 'Bugatti peruano',
		['brand'] = 'supers',
		['model'] = 'nero',
		['price'] = 1850000,
		['category'] = 'supers',
		['hash'] = `nero`,
		['shop'] = 'pdm',
	},
	['nero2'] = {
		['name'] = 'Bugatti Chino',
		['brand'] = 'supers',
		['model'] = 'nero2',
		['price'] = 1650000,
		['category'] = 'supers',
		['hash'] = `nero2`,
		['shop'] = 'pdm',
	},
	['penetrator'] = {
		['name'] = 'Penetrador 2000',
		['brand'] = 'supers',
		['model'] = 'penetrator',
		['price'] = 850000,
		['category'] = 'supers',
		['hash'] = `penetrator`,
		['shop'] = 'pdm',
	},
	['pfister811'] = {
		['name'] = 'Pfister',
		['brand'] = 'supers',
		['model'] = 'pfister811',
		['price'] = 1560000,
		['category'] = 'supers',
		['hash'] = `pfister811`,
		['shop'] = 'pdm',
	},
	['fmj'] = {
		['name'] = 'FMJ',
		['brand'] = 'supers',
		['model'] = 'fmj',
		['price'] = 1100000,
		['category'] = 'supers',
		['hash'] = `fmj`,
		['shop'] = 'pdm',
	},
	['reaper'] = {
		['name'] = 'Reaper',
		['brand'] = 'supers',
		['model'] = 'reaper',
		['price'] = 1250000,
		['category'] = 'supers',
		['hash'] = `reaper`,
		['shop'] = 'pdm',
	},
	['italigtb'] = {
		['name'] = 'Itali GTB',
		['brand'] = 'supers',
		['model'] = 'italigtb',
		['price'] = 1450000,
		['category'] = 'supers',
		['hash'] = `italigtb`,
		['shop'] = 'pdm',
	},
	['sheava'] = {
		['name'] = 'Sheava',
		['brand'] = 'supers',
		['model'] = 'sheava',
		['price'] = 750000,
		['category'] = 'supers',
		['hash'] = `sheava`,
		['shop'] = 'pdm',
	},
	['cheetah'] = {
		['name'] = 'Cheetah',
		['brand'] = 'supers',
		['model'] = 'cheetah',
		['price'] = 1700000,
		['category'] = 'supers',
		['hash'] = `cheetah`,
		['shop'] = 'pdm',
	},
	['cyclone'] = {
		['name'] = 'Cyclone',
		['brand'] = 'supers',
		['model'] = 'cyclone',
		['price'] = 1000000,
		['category'] = 'supers',
		['hash'] = `cyclone`,
		['shop'] = 'pdm',
	},
	['entityfx'] = {
		['name'] = 'Entyti',
		['brand'] = 'supers',
		['model'] = 'entityfx',
		['price'] = 840999,
		['category'] = 'supers',
		['hash'] = `entityfx`,
		['shop'] = 'pdm',
	},
	
	
	['abzn20'] = {
		['name'] = 'Zenvo',
		['brand'] = 'supers',
		['model'] = 'abzn20',
		['price'] = 7000000,
		['category'] = 'autoreal',
		['hash'] = `abzn20`,
		['shop'] = 'pdm',
	},
	
	-- SEDANS --
	
	['premier'] = {
		['name'] = 'Premier',
		['brand'] = 'sedans',
		['model'] = 'premier',
		['price'] = 280000,
		['category'] = 'sedans',
		['hash'] = `premier`,
		['shop'] = 'pdm',
	},
	['regina'] = {
		['name'] = 'Regina',
		['brand'] = 'sedans',
		['model'] = 'regina',
		['price'] = 70000,
		['category'] = 'sedans',
		['hash'] = `regina`,
		['shop'] = 'pdm',
	},
	['tailgater'] = {
		['name'] = 'Tailgater',
		['brand'] = 'sedans',
		['model'] = 'tailgater',
		['price'] = 130000,
		['category'] = 'sedans',
		['hash'] = `tailgater`,
		['shop'] = 'pdm',
	},
	['washington'] = {
		['name'] = 'Washington',
		['brand'] = 'sedans',
		['model'] = 'washington',
		['price'] = 130000,
		['category'] = 'sedans',
		['hash'] = `washington`,
		['shop'] = 'pdm',
	},
	['asea'] = {
		['name'] = 'Asea',
		['brand'] = 'sedans',
		['model'] = 'asea',
		['price'] = 90000,
		['category'] = 'sedans',
		['hash'] = `asea`,
		['shop'] = 'pdm',
	},
	['cognoscenti'] = {
		['name'] = 'Cognoscenti',
		['brand'] = 'sedans',
		['model'] = 'cognoscenti',
		['price'] = 95000,
		['category'] = 'sedans',
		['hash'] = `cognoscenti`,
		['shop'] = 'pdm',
	},
	['glendale'] = {
		['name'] = 'Glendale',
		['brand'] = 'sedans',
		['model'] = 'glendale',
		['price'] = 95000,
		['category'] = 'sedans',
		['hash'] = `glendale`,
		['shop'] = 'pdm',
	},
	['intruder'] = {
		['name'] = 'Intruder',
		['brand'] = 'sedans',
		['model'] = 'intruder',
		['price'] = 195000,
		['category'] = 'sedans',
		['hash'] = `intruder`,
		['shop'] = 'pdm',
	},
	['cog55'] = {
		['name'] = 'Cog 55',
		['brand'] = 'sedans',
		['model'] = 'cog55',
		['price'] = 180000,
		['category'] = 'sedans',
		['hash'] = `cog55`,
		['shop'] = 'pdm',
	},
	
	-- COUPES --
	
	['jackal'] = {
		['name'] = 'Jackal',
		['brand'] = 'coupes',
		['model'] = 'jackal',
		['price'] = 215000,
		['category'] = 'coupes',
		['hash'] = `jackal`,
		['shop'] = 'pdm',
	},
	['oracle2'] = {
		['name'] = 'Oracle XS',
		['brand'] = 'coupes',
		['model'] = 'oracle2',
		['price'] = 200000,
		['category'] = 'coupes',
		['hash'] = `oracle2`,
		['shop'] = 'pdm',
	},
	['sentinel'] = {
		['name'] = 'Sentinel',
		['brand'] = 'coupes',
		['model'] = 'sentinel',
		['price'] = 180000,
		['category'] = 'coupes',
		['hash'] = `sentinel`,
		['shop'] = 'pdm',
	},
	['cogcabrio'] = {
		['name'] = 'Cogcabrio',
		['brand'] = 'coupes',
		['model'] = 'cogcabrio',
		['price'] = 124000,
		['category'] = 'coupes',
		['hash'] = `cogcabrio`,
		['shop'] = 'pdm',
	},
	['f620'] = {
		['name'] = 'F620',
		['brand'] = 'coupes',
		['model'] = 'f620',
		['price'] = 120000,
		['category'] = 'coupes',
		['hash'] = `f620`,
		['shop'] = 'pdm',
	},
	['felon'] = {
		['name'] = 'Felon',
		['brand'] = 'coupes',
		['model'] = 'felon',
		['price'] = 175000,
		['category'] = 'coupes',
		['hash'] = `felon`,
		['shop'] = 'pdm',
	},
	
	-- COMPACTS --
	
	['blista'] = {
		['name'] = 'Blista',
		['brand'] = 'compacts',
		['model'] = 'blista',
		['price'] = 95000,
		['category'] = 'compacts',
		['hash'] = `blista`,
		['shop'] = 'pdm',
	},
	['brioso'] = {
		['name'] = 'Brioso RA', 'brioso',
		['brand'] = 'compacts',
		['model'] = 'brioso',
		['price'] = 95000,
		['category'] = 'compacts',
		['hash'] = `brioso`,
		['shop'] = 'pdm',
	},
	['panto'] = {
		['name'] = 'Panto',
		['brand'] = 'compacts',
		['model'] = 'panto',
		['price'] = 95000,
		['category'] = 'compacts',
		['hash'] = `panto`,
		['shop'] = 'pdm',
	},
	['prairie'] = {
		['name'] = 'Prairie',
		['brand'] = 'compacts',
		['model'] = 'prairie',
		['price'] = 200000,
		['category'] = 'compacts',
		['hash'] = `prairie`,
		['shop'] = 'pdm',
	},
	['rhapsody'] = {
		['name'] = 'Rapsodia',
		['brand'] = 'compacts',
		['model'] = 'rhapsody',
		['price'] = 95999,
		['category'] = 'compacts',
		['hash'] = `rhapsody`,
		['shop'] = 'pdm',
	},
	['issi3'] = {
		['name'] = 'Issi3',
		['brand'] = 'compacts',
		['model'] = 'issi3',
		['price'] = 95000,
		['category'] = 'compacts',
		['hash'] = `issi3`,
		['shop'] = 'pdm',
	},
	
	-- CYCLES --
	
	['cruiser'] = {
		['name'] = 'Cruiser',
		['brand'] = 'cycles',
		['model'] = 'cruiser',
		['price'] = 5000,
		['category'] = 'cycles',
		['hash'] = `cruiser`,
		['shop'] = 'pdm',
	},
	['scorcher'] = {
		['name'] = 'Scorcher',
		['brand'] = 'cycles',
		['model'] = 'scorcher',
		['price'] = 5000,
		['category'] = 'cycles',
		['hash'] = `scorcher`,
		['shop'] = 'pdm',
	},
	['tribike'] = {
		['name'] = 'Race bike Whippet',
		['brand'] = 'cycles',
		['model'] = 'tribike',
		['price'] = 5000,
		['category'] = 'cycles',
		['hash'] = `tribike`,
		['shop'] = 'pdm',
	},
	['tribike2'] = {
		['name'] = 'Race bike Endurex',
		['brand'] = 'cycles',
		['model'] = 'tribike2',
		['price'] = 5000,
		['category'] = 'cycles',
		['hash'] = `tribike2`,
		['shop'] = 'pdm',
	},
	['tribike3'] = {
		['name'] = 'Race bike Tri-Cycles',
		['brand'] = 'cycles',
		['model'] = 'tribike3',
		['price'] = 5000,
		['category'] = 'cycles',
		['hash'] = `tribike3`,
		['shop'] = 'pdm',
	},
	['fixter'] = {
		['name'] = 'Fixter',
		['brand'] = 'cycles',
		['model'] = 'fixter',
		['price'] = 5000,
		['category'] = 'cycles',
		['hash'] = `fixter`,
		['shop'] = 'pdm',
	},
	
	-- SUVS --
	
	['cavalcade2'] = {
		['name'] = 'Cavalcade',
		['brand'] = 'suvs',
		['model'] = 'cavalcade2',
		['price'] = 190000,
		['category'] = 'suvs',
		['hash'] = `cavalcade2`,
		['shop'] = 'pdm',
	},
	['contender'] = {
		['name'] = 'Contender',
		['brand'] = 'suvs',
		['model'] = 'contender',
		['price'] = 342000,
		['category'] = 'suvs',
		['hash'] = `contender`,
		['shop'] = 'pdm',
	},
	['dubsta'] = {
		['name'] = 'Dubsta',
		['brand'] = 'suvs',
		['model'] = 'dubsta',
		['price'] = 250000,
		['category'] = 'suvs',
		['hash'] = `dubsta`,
		['shop'] = 'pdm',
	},
	['dubsta2'] = {
		['name'] = 'Dubsta2',
		['brand'] = 'suvs',
		['model'] = 'dubsta2',
		['price'] = 370000,
		['category'] = 'suvs',
		['hash'] = `dubsta2`,
		['shop'] = 'pdm',
	},
	['gresley'] = {
		['name'] = 'Gresley',
		['brand'] = 'suvs',
		['model'] = 'gresley',
		['price'] = 95000,
		['category'] = 'suvs',
		['hash'] = `gresley`,
		['shop'] = 'pdm',
	},
	['landstalker'] = {
		['name'] = 'Landstalker',
		['brand'] = 'suvs',
		['model'] = 'landstalker',
		['price'] = 125000,
		['category'] = 'suvs',
		['hash'] = `landstalker`,
		['shop'] = 'pdm',
	},
	['patriot'] = {
		['name'] = 'Patriot',
		['brand'] = 'suvs',
		['model'] = 'patriot',
		['price'] = 550000,
		['category'] = 'suvs',
		['hash'] = `patriot`,
		['shop'] = 'pdm',
	},
	['patriot2'] = {
		['name'] = 'Patriot Limusina',
		['brand'] = 'suvs',
		['model'] = 'patriot2',
		['price'] = 1250000,
		['category'] = 'suvs',
		['hash'] = `patriot2`,
		['shop'] = 'pdm',
	},
	['baller2'] = {
		['name'] = 'Baller',
		['brand'] = 'suvs',
		['model'] = 'baller2',
		['price'] = 170000,
		['category'] = 'suvs',
		['hash'] = `baller2`,
		['shop'] = 'pdm',
	},
	['baller3'] = {
		['name'] = 'Baller Sport',
		['brand'] = 'suvs',
		['model'] = 'baller3',
		['price'] = 160000,
		['category'] = 'suvs',
		['hash'] = `baller3`,
		['shop'] = 'pdm',
	},
	
	-- sportsclassics --
	
	
	['btype'] = {
		['name'] = 'Btype',
		['brand'] = 'sportsclassics',
		['model'] = 'btype',
		['price'] = 160000,
		['category'] = 'sportsclassics',
		['hash'] = `btype`,
		['shop'] = 'pdm',
	},
	['btype3'] = {
		['name'] = 'Btype Luxe',
		['brand'] = 'sportsclassics',
		['model'] = 'btype3',
		['price'] = 185000,
		['category'] = 'sportsclassics',
		['hash'] = `btype3`,
		['shop'] = 'pdm',
	},
	['infernus2'] = {
		['name'] = 'Infernus 2',
		['brand'] = 'sportsclassics',
		['model'] = 'infernus2',
		['price'] = 600000,
		['category'] = 'sportsclassics',
		['hash'] = `infernus2`,
		['shop'] = 'pdm',
	},
	['cheetah2'] = {
		['name'] = 'Cheetah 2',
		['brand'] = 'sportsclassics',
		['model'] = 'cheetah2',
		['price'] = 660000,
		['category'] = 'sportsclassics',
		['hash'] = `cheetah2`,
		['shop'] = 'pdm',
	},
	['pigalle'] = {
		['name'] = 'Pigalle',
		['brand'] = 'sportsclassics',
		['model'] = 'pigalle',
		['price'] = 125000,
		['category'] = 'sportsclassics',
		['hash'] = `pigalle`,
		['shop'] = 'pdm',
	},
	['turismo2'] = {
		['name'] = 'Turismo 2',
		['brand'] = 'sportsclassics',
		['model'] = 'turismo2',
		['price'] = 500000,
		['category'] = 'sportsclassics',
		['hash'] = `turismo2`,
		['shop'] = 'pdm',
	},
	['z190'] = {
		['name'] = 'Z190',
		['brand'] = 'sportsclassics',
		['model'] = 'z190',
		['price'] = 290000,
		['category'] = 'sportsclassics',
		['hash'] = `z190`,
		['shop'] = 'pdm',
	},
	
	-- SPORTS --
	

	['buffalo'] = {
		['name'] = 'Buffalo',
		['brand'] = 'sports',
		['model'] = 'buffalo',
		['price'] = 175000,
		['category'] = 'sports',
		['hash'] = `buffalo`,
		['shop'] = 'pdm',
	},
	['carbonizzare'] = {
		['name'] = 'Carbonizzare',
		['brand'] = 'sports',
		['model'] = 'carbonizzare',
		['price'] = 250000,
		['category'] = 'sports',
		['hash'] = `carbonizzare`,
		['shop'] = 'pdm',
	},
	['flashgt'] = {
		['name'] = 'Flash GT',
		['brand'] = 'sports',
		['model'] = 'flashgt',
		['price'] = 220000,
		['category'] = 'sports',
		['hash'] = `flashgt`,
		['shop'] = 'pdm',
	},
	['furoregt'] = {
		['name'] = 'Furore GT',
		['brand'] = 'sports',
		['model'] = 'furoregt',
		['price'] = 250000,
		['category'] = 'sports',
		['hash'] = `furoregt`,
		['shop'] = 'pdm',
	},
	['pariah'] = {
		['name'] = 'Pariah',
		['brand'] = 'sports',
		['model'] = 'pariah',
		['price'] = 750000,
		['category'] = 'sports',
		['hash'] = `pariah`,
		['shop'] = 'pdm',
	},
	['raiden'] = {
		['name'] = 'Raiden',
		['brand'] = 'sports',
		['model'] = 'raiden',
		['price'] = 650000,
		['category'] = 'sports',
		['hash'] = `raiden`,
		['shop'] = 'pdm',
	},
	['schlagen'] = {
		['name'] = 'Schlagen',
		['brand'] = 'sports',
		['model'] = 'schlagen',
		['price'] = 365000,
		['category'] = 'sports',
		['hash'] = `schlagen`,
		['shop'] = 'pdm',
	},
	['bestiagts'] = {
		['name'] = 'Bestia Gts',
		['brand'] = 'sports',
		['model'] = 'bestiagts',
		['price'] = 350000,
		['category'] = 'sports',
		['hash'] = `bestiagts`,
		['shop'] = 'pdm',
	},
	['blista2'] = {
		['name'] = 'Blista Cubo',
		['brand'] = 'sports',
		['model'] = 'blista2',
		['price'] = 150000,
		['category'] = 'sports',
		['hash'] = `blista2`,
		['shop'] = 'pdm',
	},
	['alpha'] = {
		['name'] = 'Alpha',
		['brand'] = 'sports',
		['model'] = 'alpha',
		['price'] = 260000,
		['category'] = 'sports',
		['hash'] = `alpha`,
		['shop'] = 'pdm',
	},
	['banshee'] = {
		['name'] = 'Banshee',
		['brand'] = 'sports',
		['model'] = 'banshee',
		['price'] = 300000,
		['category'] = 'sports',
		['hash'] = `banshee`,
		['shop'] = 'pdm',
	},
	
	-- motorcycles --
	
	['akuma'] = {
		['name'] = 'Akuma',
		['brand'] = 'motorcycles',
		['model'] = 'akuma',
		['price'] = 220000,
		['category'] = 'motorcycles',
		['hash'] = `akuma`,
		['shop'] = 'pdm',
	},
	['bati'] = {
		['name'] = 'Bati',
		['brand'] = 'motorcycles',
		['model'] = 'bati',
		['price'] = 255000,
		['category'] = 'motorcycles',
		['hash'] = `bati`,
		['shop'] = 'pdm',
	},
	['bf400'] = {
		['name'] = 'BF400',
		['brand'] = 'motorcycles',
		['model'] = 'bf400',
		['price'] = 225000,
		['category'] = 'motorcycles',
		['hash'] = `bf400`,
		['shop'] = 'pdm',
	},
	['cliffhanger'] = {
		['name'] = 'Cliffhanger',
		['brand'] = 'motorcycles',
		['model'] = 'cliffhanger',
		['price'] = 170000,
		['category'] = 'motorcycles',
		['hash'] = `cliffhanger`,
		['shop'] = 'pdm',
	},
	['daemon2'] = {
		['name'] = 'Daemon',
		['brand'] = 'motorcycles',
		['model'] = 'daemon2',
		['price'] = 170000,
		['category'] = 'motorcycles',
		['hash'] = `daemon2`,
		['shop'] = 'pdm',
	},
	['defiler'] = {
		['name'] = 'Defiler',
		['brand'] = 'motorcycles',
		['model'] = 'defiler',
		['price'] = 1550000,
		['category'] = 'motorcycles',
		['hash'] = `defiler`,
		['shop'] = 'pdm',
	},
	['diablous2'] = {
		['name'] = 'Diablo',
		['brand'] = 'motorcycles',
		['model'] = 'diablous2',
		['price'] = 150000,
		['category'] = 'motorcycles',
		['hash'] = `diablous2`,
		['shop'] = 'pdm',
	},
	['faggio'] = {
		['name'] = 'Faggio',
		['brand'] = 'motorcycles',
		['model'] = 'faggio',
		['price'] = 80000,
		['category'] = 'motorcycles',
		['hash'] = `faggio`,
		['shop'] = 'pdm',
	},
	['hakuchou'] = {
		['name'] = 'Hakuchou',
		['brand'] = 'motorcycles',
		['model'] = 'hakuchou',
		['price'] = 240000,
		['category'] = 'motorcycles',
		['hash'] = `hakuchou`,
		['shop'] = 'pdm',
	},
	['hakuchou2'] = {
		['name'] = 'hakuchou pistera',
		['brand'] = 'motorcycles',
		['model'] = 'hakuchou2',
		['price'] = 220000,
		['category'] = 'motorcycles',
		['hash'] = `hakuchou2`,
		['shop'] = 'pdm',
	},
	['manchez'] = {
		['name'] = 'manchez',
		['brand'] = 'motorcycles',
		['model'] = 'manchez',
		['price'] = 220000,
		['category'] = 'motorcycles',
		['hash'] = `manchez`,
		['shop'] = 'pdm',
	},
	['nemesis'] = {
		['name'] = 'nemesis',
		['brand'] = 'motorcycles',
		['model'] = 'nemesis',
		['price'] = 100000,
		['category'] = 'motorcycles',
		['hash'] = `nemesis`,
		['shop'] = 'pdm',
	},
	['nightblade'] = {
		['name'] = 'nightblade',
		['brand'] = 'motorcycles',
		['model'] = 'nightblade',
		['price'] = 195000,
		['category'] = 'motorcycles',
		['hash'] = `nightblade`,
		['shop'] = 'pdm',
	},
	['sanchez'] = {
		['name'] = 'Sanchez',
		['brand'] = 'motorcycles',
		['model'] = 'sanchez',
		['price'] = 230000,
		['category'] = 'motorcycles',
		['hash'] = `sanchez`,
		['shop'] = 'pdm',
	},
	['vindicator'] = {
		['name'] = 'Vindicator',
		['brand'] = 'motorcycles',
		['model'] = 'vindicator',
		['price'] = 180000,
		['category'] = 'motorcycles',
		['hash'] = `vindicator`,
		['shop'] = 'pdm',
	},
	['vortex'] = {
		['name'] = 'Vortex',
		['brand'] = 'motorcycles',
		['model'] = 'vortex',
		['price'] = 180000,
		['category'] = 'motorcycles',
		['hash'] = `vortex`,
		['shop'] = 'pdm',
	},
	['zombieb'] = {
		['name'] = 'Zombie Luxuary',
		['brand'] = 'motorcycles',
		['model'] = 'zombieb',
		['price'] = 250000,
		['category'] = 'motorcycles',
		['hash'] = `zombieb`,
		['shop'] = 'pdm',
	},
	
	--- FLOW BR
	
	['puntoap'] = {
		['name'] = 'Fiat Punto',
		['brand'] = 'flowbr',
		['model'] = 'puntoap',
		['price'] = 13000000,
		['category'] = 'flowbr',
		['hash'] = `puntoap`,
		['shop'] = 'pdm',
	},
	
	['palio97'] = {
		['name'] = 'Fiat Palio 1997',
		['brand'] = 'flowbr',
		['model'] = 'palio97',
		['price'] = 11000000,
		['category'] = 'flowbr',
		['hash'] = `palio97`,
		['shop'] = 'pdm',
	},
	
	['ecosportap'] = {
		['name'] = 'EcoSport FreeStyle',
		['brand'] = 'flowbr',
		['model'] = 'ecosportap',
		['price'] = 11000000,
		['category'] = 'flowbr',
		['hash'] = `ecosportap`,
		['shop'] = 'pdm',
	},
	
	['c10ap'] = {
		['name'] = 'Chevrolt c10 al piso',
		['brand'] = 'flowbr',
		['model'] = 'c10ap',
		['price'] = 10500000,
		['category'] = 'flowbr',
		['hash'] = `c10ap`,
		['shop'] = 'pdm',
	},
	
	['golglap'] = {
		['name'] = 'Gol G5 Al piso',
		['brand'] = 'flowbr',
		['model'] = 'golglap',
		['price'] = 10000000,
		['category'] = 'flowbr',
		['hash'] = `golglap`,
		['shop'] = 'pdm',
	},
	
	['paratiap'] = {
		['name'] = 'Vw Parati Surf 1.8 Turbo',
		['brand'] = 'flowbr',
		['model'] = 'paratiap',
		['price'] = 12000000,
		['category'] = 'flowbr',
		['hash'] = `paratiap`,
		['shop'] = 'pdm',
	},
	
	['brasiliaap'] = {
		['name'] = 'Vw Brasilia 1974',
		['brand'] = 'flowbr',
		['model'] = 'brasiliaap',
		['price'] = 11250000,
		['category'] = 'flowbr',
		['hash'] = `brasiliaap`,
		['shop'] = 'pdm',
	},
	
	['saveiroap'] = {
		['name'] = 'Saveiro Cli 1.6',
		['brand'] = 'flowbr',
		['model'] = 'saveiroap',
		['price'] = 10000000,
		['category'] = 'flowbr',
		['hash'] = `saveiroap`,
		['shop'] = 'pdm',
	},
	
	['pop110i'] = {
		['name'] = 'Honda Pop',
		['brand'] = 'flowbr',
		['model'] = 'pop110i',
		['price'] = 3000000,
		['category'] = 'flowbr',
		['hash'] = `pop110i`,
		['shop'] = 'pdm',
	},
	
	['rc390s21'] = {
		['name'] = 'KTM RC 390',
		['brand'] = 'flowbr',
		['model'] = 'rc390s21',
		['price'] = 5000000,
		['category'] = 'flowbr',
		['hash'] = `rc390s21`,
		['shop'] = 'pdm',
	},
	
	['hcrf450r'] = {
		['name'] = 'CRF 450r',
		['brand'] = 'flowbr',
		['model'] = 'hcrf450r',
		['price'] = 6500000,
		['category'] = 'flowbr',
		['hash'] = `hcrf450r`,
		['shop'] = 'pdm',
	},
	
	['rebaixada'] = {
		['name'] = 'REBAIXADA',
		['brand'] = 'flowbr',
		['model'] = 'rebaixada',
		['price'] = 12500000,
		['category'] = 'flowbr',
		['hash'] = `rebaixada`,
		['shop'] = 'pdm',
	},
	
	['supra1'] = {
		['name'] = 'SUPRA 1',
		['brand'] = 'flowbr',
		['model'] = 'supra1',
		['price'] = 13500000,
		['category'] = 'flowbr',
		['hash'] = `supra1`,
		['shop'] = 'pdm',
	},
	
	
	
}

exports('VehiclesTable', function()
    return Config.Vehicles
end)