Citizen.CreateThread(function()
	SetRichPresence("ID  [" .. GetPlayerServerId(PlayerId()) .. "]  | valhallarp.net")
	SetDiscordAppId("982457849500287016")
	SetDiscordRichPresenceAsset("logo")
    SetDiscordRichPresenceAssetSmall("logo")
    SetDiscordRichPresenceAssetSmallText("discord.valhallarp.net")
    SetDiscordRichPresenceAssetText("VALHALLA:RP v2.0")
    SetDiscordRichPresenceAction(0, "Website", "https://www.valhallarp.net")
    SetDiscordRichPresenceAction(1, "Discord", "https://discord.gg/Rxx6WRzUuA")
end)