var tableauQuestion = [
    {   question : "Si vas a 65 mph, y te estás acercando a una zona residencial, debes:",
        propositionA : "Acelerar",
        propositionB : "Mantienes tu velocidad, si no pasas otros vehículos.",
        propositionC : "Disminuir la velocidad",
        propositionD : "Mantener velocidad",
        reponse : "C"},

    {   question : "Si está girando a la derecha en un semáforo, pero ves un cruce de peatones, ¿qué hace?:",
        propositionA : "Pasas el peatón",
        propositionB : "Comprobar que no hay otros vehículos alrededor.",
        propositionC : "Esperas hasta que el peatón haya cruzado.",
        propositionD : "Disparas al peatón y sigues conduciendo.",
        reponse : "C"},

    {   question : "Sin ninguna indicación previa, la velocidad en una zona residencial es: __ mph",
        propositionA : "30",
        propositionB : "35",
        propositionC : "40",
        propositionD : "45",
        reponse : "A"},

  {   question : "Antes de cada cambio de carril debes:",
        propositionA : "Revisar tus espejos",
        propositionB : "Revisa tus puntos ciegos",
        propositionC : "Señala tus intenciones",
        propositionD : "Todas las anteriores",
        reponse : "D"},

  {   question : "¿Qué nivel de alcohol en sangre se clasifican como permitido mientras estas intoxicado?",
        propositionA : "0.05%",
        propositionB : "0.18%",
        propositionC : "0.08%",
        propositionD : "0.06%",
        reponse : "C"},

  {   question : "¿Cuándo puedes continuar conduciendo en un semáforo?",
        propositionA : "Cuando es verde",
        propositionB : "Cuando no hay nadie en la intersección.",
        propositionC : "Cuando estas en una zona escolar",
        propositionD : "Cuando está verde y/o rojo y estás girando a la derecha",
        reponse : "D"},

  {   question : "Un peatón tiene una señal de no cruzar, ¿qué haces?",
        propositionA : "Les dejas pasar",
        propositionB : "Observas antes de continuar",
        propositionC : "Les saludas para decirles que crucen",
        propositionD : "Continúas porque tu semáforo está en verde.",
        reponse : "D"},

  {   question : "Lo que está permitido al pasar por otro vehículo.",
        propositionA : "Lo sigues de cerca para pasarlo más rápido.",
        propositionB : "Lo pasas sin salir de la calzada.",
        propositionC : "Conduces por el lado opuesto de la carretera para pasar.",
        propositionD : "Se supera el límite de velocidad para pasarlos.",
        reponse : "C"},

  {   question : "Usted está conduciendo en una carretera que indica una velocidad máxima de 70 mph. La mayoría de las unidades de tráfico a 75 mph, por lo que no debe conducir más rápido que:",
        propositionA : "50 mph",
        propositionB : "25 mph",
        propositionC : "30 mph",
        propositionD : "70 mph",
        reponse : "D"},

  {   question : "Cuando es superado por otro vehículo, es importante NO:",
        propositionA : "Ir más despacio",
        propositionB : "Revisar tus espejos",
        propositionC : "Mirar a otros conductores",
        propositionD : "Aumentar tu velocidad",
        reponse : "D"},
]
