Citizen.CreateThread(function()
	local GarageBlip = AddBlipForCoord(374.16, 287.6, 103.24)
	SetBlipSprite (GarageBlip, 50)
	SetBlipDisplay(GarageBlip, 4)
	SetBlipScale  (GarageBlip, 0.9)
	SetBlipColour (GarageBlip, 2)
	SetBlipAsShortRange(GarageBlip, true)

	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Garage")
	EndTextCommandSetBlipName(GarageBlip)
end)

Citizen.CreateThread(function()
	local GarageBlip = AddBlipForCoord(-818.96, -687.08, 123.4)
	SetBlipSprite (GarageBlip, 304)
	SetBlipDisplay(GarageBlip, 4)
	SetBlipScale  (GarageBlip, 0.9)
	SetBlipColour (GarageBlip, 27)
	SetBlipAsShortRange(GarageBlip, true)

	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Lux")
	EndTextCommandSetBlipName(GarageBlip)
end)

Citizen.CreateThread(function()
	local GarageBlip = AddBlipForCoord(-330.72, -889.44, 31.08)
	SetBlipSprite (GarageBlip, 50)
	SetBlipDisplay(GarageBlip, 4)
	SetBlipScale  (GarageBlip, 0.9)
	SetBlipColour (GarageBlip, 2)
	SetBlipAsShortRange(GarageBlip, true)

	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Garage")
	EndTextCommandSetBlipName(GarageBlip)
end)

Citizen.CreateThread(function()
	local GarageBlip = AddBlipForCoord(877.96, 5.16, 78.76)
	SetBlipSprite (GarageBlip, 50)
	SetBlipDisplay(GarageBlip, 4)
	SetBlipScale  (GarageBlip, 0.9)
	SetBlipColour (GarageBlip, 2)
	SetBlipAsShortRange(GarageBlip, true)

	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Garage")
	EndTextCommandSetBlipName(GarageBlip)
end)

Citizen.CreateThread(function()
	local GarageBlip = AddBlipForCoord(877.96, 5.16, 78.76)
	SetBlipSprite (GarageBlip, 50)
	SetBlipDisplay(GarageBlip, 4)
	SetBlipScale  (GarageBlip, 0.9)
	SetBlipColour (GarageBlip, 2)
	SetBlipAsShortRange(GarageBlip, true)

	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Garage")
	EndTextCommandSetBlipName(GarageBlip)
end)

Citizen.CreateThread(function()
	local GarageBlip = AddBlipForCoord(-59.92, -1843.04, 26.56)
	SetBlipSprite (GarageBlip, 50)
	SetBlipDisplay(GarageBlip, 4)
	SetBlipScale  (GarageBlip, 0.9)
	SetBlipColour (GarageBlip, 2)
	SetBlipAsShortRange(GarageBlip, true)

	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Garage")
	EndTextCommandSetBlipName(GarageBlip)
end)

Citizen.CreateThread(function()
	local PampBlip = AddBlipForCoord(-709.04, -905.44, 19.2)
	SetBlipSprite (PampBlip, 119)
	SetBlipDisplay(PampBlip, 4)
	SetBlipScale  (PampBlip, 0.8)
	SetBlipColour (PampBlip, 1)
	SetBlipAsShortRange(PampBlip, true)

	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Robo a Tienda")
	EndTextCommandSetBlipName(GarageBlip)
end)

Citizen.CreateThread(function()
	local PampBlip = AddBlipForCoord(-1291.88, -838.6, 17.16)
	SetBlipSprite (PampBlip, 119)
	SetBlipDisplay(PampBlip, 4)
	SetBlipScale  (PampBlip, 0.8)
	SetBlipColour (PampBlip, 1)
	SetBlipAsShortRange(PampBlip, true)

	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Robo a Maze")
	EndTextCommandSetBlipName(GarageBlip)
end)

Citizen.CreateThread(function()
	local GarageBlip = AddBlipForCoord(1102.04, 2661.0, 37.96)
	SetBlipSprite (GarageBlip, 542)
	SetBlipDisplay(GarageBlip, 4)
	SetBlipScale  (GarageBlip, 0.5)
	SetBlipColour (GarageBlip, 1)
	SetBlipAsShortRange(GarageBlip, true)

	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Garage")
	EndTextCommandSetBlipName(GarageBlip)
end)

Citizen.CreateThread(function()
	local GarageBlip = AddBlipForCoord(223.84, -789.72, 31.52)
	SetBlipSprite (GarageBlip, 50)
	SetBlipDisplay(GarageBlip, 4)
	SetBlipScale  (GarageBlip, 0.9)
	SetBlipColour (GarageBlip, 2)
	SetBlipAsShortRange(GarageBlip, true)

	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Garage")
	EndTextCommandSetBlipName(GarageBlip)
end)

Citizen.CreateThread(function()
	local GarageBlip = AddBlipForCoord(2794.16, 3481.92, 55.12)
	SetBlipSprite (GarageBlip, 50)
	SetBlipDisplay(GarageBlip, 4)
	SetBlipScale  (GarageBlip, 0.9)
	SetBlipColour (GarageBlip, 2)
	SetBlipAsShortRange(GarageBlip, true)

	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Garage")
	EndTextCommandSetBlipName(GarageBlip)
end)

Citizen.CreateThread(function()
	local GarageBlip = AddBlipForCoord(1419.68, 3619.12, 34.88)
	SetBlipSprite (GarageBlip, 50)
	SetBlipDisplay(GarageBlip, 4)
	SetBlipScale  (GarageBlip, 0.9)
	SetBlipColour (GarageBlip, 2)
	SetBlipAsShortRange(GarageBlip, true)

	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Garage")
	EndTextCommandSetBlipName(GarageBlip)
end)

Citizen.CreateThread(function()
	local GarageBlip = AddBlipForCoord(127.24, 6608.24, 31.84)
	SetBlipSprite (GarageBlip, 50)
	SetBlipDisplay(GarageBlip, 4)
	SetBlipScale  (GarageBlip, 0.9)
	SetBlipColour (GarageBlip, 2)
	SetBlipAsShortRange(GarageBlip, true)

	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Garage")
	EndTextCommandSetBlipName(GarageBlip)
end)

Citizen.CreateThread(function()
	local HospitalBlip = AddBlipForCoord(1840.36, 3670.72, 33.92)
	SetBlipSprite (HospitalBlip, 61)
	SetBlipDisplay(HospitalBlip, 4)
	SetBlipScale  (HospitalBlip, 0.9)
	SetBlipColour (HospitalBlip, 0)
	SetBlipAsShortRange(HospitalBlip, true)

	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Hospital Sandy")
	EndTextCommandSetBlipName(HospitalBlip)
end)

Citizen.CreateThread(function()
	local HospitalBlip = AddBlipForCoord(294.92, -588.56, 43.12)
	SetBlipSprite (HospitalBlip, 61)
	SetBlipDisplay(HospitalBlip, 4)
	SetBlipScale  (HospitalBlip, 0.9)
	SetBlipColour (HospitalBlip, 0)
	SetBlipAsShortRange(HospitalBlip, true)

	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Hospital Italiano")
	EndTextCommandSetBlipName(HospitalBlip)
end)



Citizen.CreateThread(function()
	local BahamasBlip = AddBlipForCoord(-1390.16, -597.2, 30.32)
	SetBlipSprite (BahamasBlip, 93)
	SetBlipDisplay(BahamasBlip, 4)
	SetBlipScale  (BahamasBlip, 0.9)
	SetBlipColour (BahamasBlip, 83)
	SetBlipAsShortRange(BahamasBlip, true)

	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Bahamas")
	EndTextCommandSetBlipName(BahamasBlip)
end)

Citizen.CreateThread(function()
	local GarageBlip = AddBlipForCoord(-571.0, 329.2, 84.52)
	SetBlipSprite (GarageBlip, 50)
	SetBlipDisplay(GarageBlip, 4)
	SetBlipScale  (GarageBlip, 0.9)
	SetBlipColour (GarageBlip, 2)
	SetBlipAsShortRange(GarageBlip, true)

	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Garage")
	EndTextCommandSetBlipName(GarageBlip)
end)

Citizen.CreateThread(function()
	local GarageBlip = AddBlipForCoord(1126.96, 2650.84, 38.0)
	SetBlipSprite (GarageBlip, 50)
	SetBlipDisplay(GarageBlip, 4)
	SetBlipScale  (GarageBlip, 0.9)
	SetBlipColour (GarageBlip, 2)
	SetBlipAsShortRange(GarageBlip, true)

	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Garage")
	EndTextCommandSetBlipName(GarageBlip)
end)

Citizen.CreateThread(function()
	local GarageBlip = AddBlipForCoord(-1521.56, -434.88, 35.44)
	SetBlipSprite (GarageBlip, 50)
	SetBlipDisplay(GarageBlip, 4)
	SetBlipScale  (GarageBlip, 0.9)
	SetBlipColour (GarageBlip, 2)
	SetBlipAsShortRange(GarageBlip, true)

	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Garage")
	EndTextCommandSetBlipName(GarageBlip)
end)

Citizen.CreateThread(function()
	local IglesiaBlip = AddBlipForCoord(-780.24, -0.68, 41.56)
	SetBlipSprite (IglesiaBlip, 305)
	SetBlipDisplay(IglesiaBlip, 4)
	SetBlipScale  (IglesiaBlip, 0.9)
	SetBlipColour (IglesiaBlip, 0)
	SetBlipAsShortRange(IglesiaBlip, true)

	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Parroquia Rodrigo Bueno")
	EndTextCommandSetBlipName(IglesiaBlip)
end)

Citizen.CreateThread(function()
	local RingBlip = AddBlipForCoord(-1274.56, -1530.76, 5.16)
	SetBlipSprite (RingBlip, 630)
	SetBlipDisplay(RingBlip, 4)
	SetBlipScale  (RingBlip, 0.8)
	SetBlipColour (RingBlip, 0)
	SetBlipAsShortRange(RingBlip, true)

	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Ring de pelea")
	EndTextCommandSetBlipName(RingBlip)
end)

Citizen.CreateThread(function()
	local RingBlip = AddBlipForCoord(-32.2, -1231.24, 30.08)
	SetBlipSprite (RingBlip, 630)
	SetBlipDisplay(RingBlip, 4)
	SetBlipScale  (RingBlip, 0.8)
	SetBlipColour (RingBlip, 0)
	SetBlipAsShortRange(RingBlip, true)

	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Ring de pelea")
	EndTextCommandSetBlipName(RingBlip)
end)

Citizen.CreateThread(function()
	local MorisBlip = AddBlipForCoord(116.96, -149.24, 54.8)
	SetBlipSprite (MorisBlip, 273)
	SetBlipDisplay(MorisBlip, 4)
	SetBlipScale  (MorisBlip, 0.9)
	SetBlipColour (MorisBlip, 0)
	SetBlipAsShortRange(MorisBlip, true)

	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Concesionario de usados")
	EndTextCommandSetBlipName(MorisBlip)
end)

Citizen.CreateThread(function()
	local PolleBlip = AddBlipForCoord(-86.28, 6236.88, 31.09)
	SetBlipSprite (PolleBlip, 389)
	SetBlipDisplay(PolleBlip, 4)
	SetBlipScale  (PolleBlip, 1.2)
	SetBlipColour (PolleBlip, 0)
	SetBlipAsShortRange(PolleBlip, true)

	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Robo a polleria")
	EndTextCommandSetBlipName(PolleBlip)
end)

Citizen.CreateThread(function()
	local LifeBlip = AddBlipForCoord(-1052.36, -232.4, 44.04)
	SetBlipSprite (LifeBlip, 269)
	SetBlipDisplay(LifeBlip, 4)
	SetBlipScale  (LifeBlip, 0.8)
	SetBlipColour (LifeBlip, 0)
	SetBlipAsShortRange(LifeBlip, true)

	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Robo a Facebook")
	EndTextCommandSetBlipName(LifeBlip)
end)

Citizen.CreateThread(function()
	local HumaBlip = AddBlipForCoord(3534.87, 3660.68, 28.12)
	SetBlipSprite (HumaBlip, 104)
	SetBlipDisplay(HumaBlip, 4)
	SetBlipScale  (HumaBlip, 0.9)
	SetBlipColour (HumaBlip, 0)
	SetBlipAsShortRange(HumaBlip, true)

	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Robo a Humane")
	EndTextCommandSetBlipName(HumaBlip)
end)

Citizen.CreateThread(function()
	local FabriBlip = AddBlipForCoord(-613.1, -1623.98, 33.01)
	SetBlipSprite (FabriBlip, 405)
	SetBlipDisplay(FabriBlip, 4)
	SetBlipScale  (FabriBlip, 0.9)
	SetBlipColour (FabriBlip, 0)
	SetBlipAsShortRange(FabriBlip, true)

	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Robo a Fabrica")
	EndTextCommandSetBlipName(FabriBlip)
end)

Citizen.CreateThread(function()
	local CarniBlip = AddBlipForCoord(990.88, -2136.13, 30.22)
	SetBlipSprite (CarniBlip, 384)
	SetBlipDisplay(CarniBlip, 4)
	SetBlipScale  (CarniBlip, 0.9)
	SetBlipColour (CarniBlip, 0)
	SetBlipAsShortRange(CarniBlip, true)

	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Robo a Carniceria")
	EndTextCommandSetBlipName(CarniBlip)
end)

Citizen.CreateThread(function()
	local Banco3Blip = AddBlipForCoord(311.06, -283.19, 54.17)
	SetBlipSprite (Banco3Blip, 431)
	SetBlipDisplay(Banco3Blip, 4)
	SetBlipScale  (Banco3Blip, 0.8)
	SetBlipColour (Banco3Blip, 1)
	SetBlipAsShortRange(Banco3Blip, true)

	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Robo a Santander")
	EndTextCommandSetBlipName(Banco3Blip)
end)

Citizen.CreateThread(function()
	local Banco4Blip = AddBlipForCoord(-2957.75, 481.4, 15.9)
	SetBlipSprite (Banco4Blip, 431)
	SetBlipDisplay(Banco4Blip, 4)
	SetBlipScale  (Banco4Blip, 0.8)
	SetBlipColour (Banco4Blip, 1)
	SetBlipAsShortRange(Banco4Blip, true)

	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Robo a Santander")
	EndTextCommandSetBlipName(Banco4Blip)
end)

Citizen.CreateThread(function()
	local Banco5Blip = AddBlipForCoord(-106.66, 6474.57, 31.63)
	SetBlipSprite (Banco5Blip, 431)
	SetBlipDisplay(Banco5Blip, 4)
	SetBlipScale  (Banco5Blip, 0.8)
	SetBlipColour (Banco5Blip, 1)
	SetBlipAsShortRange(Banco5Blip, true)

	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Robo a Santander")
	EndTextCommandSetBlipName(Banco5Blip)
end)

Citizen.CreateThread(function()
	local DiorBlip = AddBlipForCoord(-170.28, -296.64, 39.72)
	SetBlipSprite (DiorBlip, 119)
	SetBlipDisplay(DiorBlip, 4)
	SetBlipScale  (DiorBlip, 0.8)
	SetBlipColour (DiorBlip, 1)
	SetBlipAsShortRange(DiorBlip, true)

	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Robo a Dior")
	EndTextCommandSetBlipName(DiorBlip)
end)

Citizen.CreateThread(function()
	local MichaelBlip = AddBlipForCoord(-808.88, 172.48, 76.76)
	SetBlipSprite (MichaelBlip, 124)
	SetBlipDisplay(MichaelBlip, 4)
	SetBlipScale  (MichaelBlip, 0.8)
	SetBlipColour (MichaelBlip, 1)
	SetBlipAsShortRange(MichaelBlip, true)

	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Robo a Casa Michael")
	EndTextCommandSetBlipName(MichaelBlip)
end)

Citizen.CreateThread(function()
	local AmmuBlip = AddBlipForCoord(-665.56, -933.32, 21.84)
	SetBlipSprite (AmmuBlip, 119)
	SetBlipDisplay(AmmuBlip, 4)
	SetBlipScale  (AmmuBlip, 0.8)
	SetBlipColour (AmmuBlip, 1)
	SetBlipAsShortRange(AmmuBlip, true)

	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Robo a Ammu")
	EndTextCommandSetBlipName(AmmuBlip)
end)

Citizen.CreateThread(function()
	local Ammu1Blip = AddBlipForCoord(826.16, -2158.76, 29.6)
	SetBlipSprite (Ammu1Blip, 119)
	SetBlipDisplay(Ammu1Blip, 4)
	SetBlipScale  (Ammu1Blip, 0.8)
	SetBlipColour (Ammu1Blip, 1)
	SetBlipAsShortRange(Ammu1Blip, true)

	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Robo a Ammu")
	EndTextCommandSetBlipName(Ammu1Blip)
end)

Citizen.CreateThread(function()
	local Ammu2Blip = AddBlipForCoord(2571.8, 292.52, 108.72)
	SetBlipSprite (Ammu2Blip, 119)
	SetBlipDisplay(Ammu2Blip, 4)
	SetBlipScale  (Ammu2Blip, 0.8)
	SetBlipColour (Ammu2Blip, 1)
	SetBlipAsShortRange(Ammu2Blip, true)

	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Robo a Ammu")
	EndTextCommandSetBlipName(Ammu2Blip)
end)

Citizen.CreateThread(function()
	local Ammu3Blip = AddBlipForCoord(-3174.88, 1085.0, 20.84)
	SetBlipSprite (Ammu3Blip, 119)
	SetBlipDisplay(Ammu3Blip, 4)
	SetBlipScale  (Ammu3Blip, 0.8)
	SetBlipColour (Ammu3Blip, 1)
	SetBlipAsShortRange(Ammu3Blip, true)

	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Robo a Ammu")
	EndTextCommandSetBlipName(Ammu3Blip)
end)

Citizen.CreateThread(function()
	local Ammu3Blip = AddBlipForCoord(-1121.32, 2697.2, 18.56)
	SetBlipSprite (Ammu3Blip, 119)
	SetBlipDisplay(Ammu3Blip, 4)
	SetBlipScale  (Ammu3Blip, 0.8)
	SetBlipColour (Ammu3Blip, 1)
	SetBlipAsShortRange(Ammu3Blip, true)

	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Robo a Ammu")
	EndTextCommandSetBlipName(Ammu3Blip)
end)

Citizen.CreateThread(function()
	local Ammu4Blip = AddBlipForCoord(-1121.36, 2698.44, 18.56)
	SetBlipSprite (Ammu4Blip, 119)
	SetBlipDisplay(Ammu4Blip, 4)
	SetBlipScale  (Ammu4Blip, 0.8)
	SetBlipColour (Ammu4Blip, 1)
	SetBlipAsShortRange(Ammu4Blip, true)

	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Robo a Ammu")
	EndTextCommandSetBlipName(Ammu4Blip)
end)

Citizen.CreateThread(function()
	local CasaBlip = AddBlipForCoord(2447.68, 4981.92, 46.84)
	SetBlipSprite (CasaBlip, 76)
	SetBlipDisplay(CasaBlip, 4)
	SetBlipScale  (CasaBlip, 0.8)
	SetBlipColour (CasaBlip, 1)
	SetBlipAsShortRange(CasaBlip, true)

	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Robo a Casa Narco")
	EndTextCommandSetBlipName(CasaBlip)
end)

Citizen.CreateThread(function()
	local PampBlip = AddBlipForCoord(-1446.4, -246.24, 49.84)
	SetBlipSprite (PampBlip, 119)
	SetBlipDisplay(PampBlip, 4)
	SetBlipScale  (PampBlip, 0.8)
	SetBlipColour (PampBlip, 1)
	SetBlipAsShortRange(PampBlip, true)

	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Robo a Pampero")
	EndTextCommandSetBlipName(PampBlip)
end)

Citizen.CreateThread(function()
	local TrevBlip = AddBlipForCoord(1973.12, 3817.84, 33.44)
	SetBlipSprite (TrevBlip, 79)
	SetBlipDisplay(TrevBlip, 4)
	SetBlipScale  (TrevBlip, 0.8)
	SetBlipColour (TrevBlip, 1)
	SetBlipAsShortRange(TrevBlip, true)

	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Robo a Casa Trevor")
	EndTextCommandSetBlipName(TrevBlip)
end)

Citizen.CreateThread(function()
	local FranklinBlip = AddBlipForCoord(-2.32, 528.56, 175.0)
	SetBlipSprite (FranklinBlip, 86)
	SetBlipDisplay(FranklinBlip, 4)
	SetBlipScale  (FranklinBlip, 0.8)
	SetBlipColour (FranklinBlip, 1)
	SetBlipAsShortRange(FranklinBlip, true)

	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Robo a Casa Franklin")
	EndTextCommandSetBlipName(FranklinBlip)
end)

Citizen.CreateThread(function()
	local LesterBlip = AddBlipForCoord(1273.4, -1708.28, 54.76)
	SetBlipSprite (LesterBlip, 77)
	SetBlipDisplay(LesterBlip, 4)
	SetBlipScale  (LesterBlip, 0.8)
	SetBlipColour (LesterBlip, 1)
	SetBlipAsShortRange(LesterBlip, true)

	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Robo a Casa Lester")
	EndTextCommandSetBlipName(LesterBlip)
end)

Citizen.CreateThread(function()
	local MikeBlip = AddBlipForCoord(-15.92, -1430.2, 31.12)
	SetBlipSprite (MikeBlip, 78)
	SetBlipDisplay(MikeBlip, 4)
	SetBlipScale  (MikeBlip, 0.8)
	SetBlipColour (MikeBlip, 1)
	SetBlipAsShortRange(MikeBlip, true)

	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Robo a Casa Mike")
	EndTextCommandSetBlipName(MikeBlip)
end)

Citizen.CreateThread(function()
	local FloydBlip = AddBlipForCoord(-1153.24, -1517.56, 10.64)
	SetBlipSprite (FloydBlip, 88)
	SetBlipDisplay(FloydBlip, 4)
	SetBlipScale  (FloydBlip, 0.8)
	SetBlipColour (FloydBlip, 1)
	SetBlipAsShortRange(FloydBlip, true)

	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Robo a Casa Floyd")
	EndTextCommandSetBlipName(FloydBlip)
end)

Citizen.CreateThread(function()
	local YateBlip = AddBlipForCoord(-2084.52, -1018.28, 12.8)
	SetBlipSprite (YateBlip, 207)
	SetBlipDisplay(YateBlip, 4)
	SetBlipScale  (YateBlip, 0.8)
	SetBlipColour (YateBlip, 5)
	SetBlipAsShortRange(YateBlip, true)

	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Robo a Yate")
	EndTextCommandSetBlipName(YateBlip)
end)

Citizen.CreateThread(function()
	local Robo3Blip = AddBlipForCoord(-43.2, -1749.28, 29.44)
	SetBlipSprite (Robo3Blip, 119)
	SetBlipDisplay(Robo3Blip, 4)
	SetBlipScale  (Robo3Blip, 0.8)
	SetBlipColour (Robo3Blip, 1)
	SetBlipAsShortRange(Robo3Blip, true)

	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Robo a Tienda")
	EndTextCommandSetBlipName(Robo3Blip)
end)

Citizen.CreateThread(function()
	local Robo4Blip = AddBlipForCoord(1126.84, -980.52, 45.4)
	SetBlipSprite (Robo4Blip, 119)
	SetBlipDisplay(Robo4Blip, 4)
	SetBlipScale  (Robo4Blip, 0.8)
	SetBlipColour (Robo4Blip, 1)
	SetBlipAsShortRange(Robo4Blip, true)

	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Robo a Tienda")
	EndTextCommandSetBlipName(Robo4Blip)
end)

Citizen.CreateThread(function()
	local Robo5Blip = AddBlipForCoord(1160.64, -314.52, 69.2)
	SetBlipSprite (Robo5Blip, 119)
	SetBlipDisplay(Robo5Blip, 4)
	SetBlipScale  (Robo5Blip, 0.8)
	SetBlipColour (Robo5Blip, 1)
	SetBlipAsShortRange(Robo5Blip, true)

	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Robo a Tienda")
	EndTextCommandSetBlipName(Robo5Blip)
end)

Citizen.CreateThread(function()
	local Robo6Blip = AddBlipForCoord(-1219.56, -916.28, 11.32)
	SetBlipSprite (Robo6Blip, 119)
	SetBlipDisplay(Robo6Blip, 4)
	SetBlipScale  (Robo6Blip, 0.8)
	SetBlipColour (Robo6Blip, 1)
	SetBlipAsShortRange(Robo6Blip, true)

	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Robo a Tienda")
	EndTextCommandSetBlipName(Robo6Blip)
end)

Citizen.CreateThread(function()
	local Robo7Blip = AddBlipForCoord(-2958.68, 387.84, 14.04)
	SetBlipSprite (Robo7Blip, 119)
	SetBlipDisplay(Robo7Blip, 4)
	SetBlipScale  (Robo7Blip, 0.8)
	SetBlipColour (Robo7Blip, 1)
	SetBlipAsShortRange(Robo7Blip, true)

	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Robo a Tienda")
	EndTextCommandSetBlipName(Robo7Blip)
end)

Citizen.CreateThread(function()
	local Robo8Blip = AddBlipForCoord(1961.08, 3749.48, 32.36)
	SetBlipSprite (Robo8Blip, 119)
	SetBlipDisplay(Robo8Blip, 4)
	SetBlipScale  (Robo8Blip, 0.8)
	SetBlipColour (Robo8Blip, 1)
	SetBlipAsShortRange(Robo8Blip, true)

	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Robo a Tienda")
	EndTextCommandSetBlipName(Robo8Blip)
end)

Citizen.CreateThread(function()
	local Robo9Blip = AddBlipForCoord(1736.32, 6419.64, 35.04)
	SetBlipSprite (Robo9Blip, 119)
	SetBlipDisplay(Robo9Blip, 4)
	SetBlipScale  (Robo9Blip, 0.8)
	SetBlipColour (Robo9Blip, 1)
	SetBlipAsShortRange(Robo9Blip, true)

	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Robo a Tienda")
	EndTextCommandSetBlipName(Robo9Blip)
end)

Citizen.CreateThread(function()
	local Robo9Blip = AddBlipForCoord(1111.32, 245.96, -45.84)
	SetBlipSprite (Robo9Blip, 119)
	SetBlipDisplay(Robo9Blip, 4)
	SetBlipScale  (Robo9Blip, 0.8)
	SetBlipColour (Robo9Blip, 1)
	SetBlipAsShortRange(Robo9Blip, true)

	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Robo a Casino")
	EndTextCommandSetBlipName(Robo9Blip)
end)


Citizen.CreateThread(function()
	local camionero = AddBlipForCoord(941.16, -2168.12, 29.55)
	SetBlipSprite (camionero, 351)
	SetBlipDisplay(camionero, 4)
	SetBlipScale  (camionero, 1.0)
	SetBlipColour (camionero, 0)
	SetBlipAsShortRange(camionero, true)

	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Camionero")
	EndTextCommandSetBlipName(camionero)
end)

Citizen.CreateThread(function()
	local camionero = AddBlipForCoord(902.04, -176.52, 73.96)
	SetBlipSprite (camionero, 198)
	SetBlipDisplay(camionero, 4)
	SetBlipScale  (camionero, 0.8)
	SetBlipColour (camionero, 46)
	SetBlipAsShortRange(camionero, true)

	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Estación de taxi")
	EndTextCommandSetBlipName(camionero)
end)

Citizen.CreateThread(function()
	local camionero = AddBlipForCoord(-630.88, -228.96, 38.04)
	SetBlipSprite (camionero, 119)
	SetBlipDisplay(camionero, 4)
	SetBlipScale  (camionero, 0.8)
	SetBlipColour (camionero, 1)
	SetBlipAsShortRange(camionero, true)

	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Robo a joye")
	EndTextCommandSetBlipName(camionero)
end)

Citizen.CreateThread(function()
	local ropa = AddBlipForCoord(1693.2, 4828.11, 42.07)
	SetBlipSprite (ropa, 366)
	SetBlipDisplay(ropa, 4)
	SetBlipScale  (ropa, 0.7)
	SetBlipColour (ropa, 47)
	SetBlipAsShortRange(ropa, true)

	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Tienda de ropa")
	EndTextCommandSetBlipName(ropa)
end)

Citizen.CreateThread(function()
	local ropa = AddBlipForCoord(-705.5, -149.22, 37.42)
	SetBlipSprite (ropa, 366)
	SetBlipDisplay(ropa, 4)
	SetBlipScale  (ropa, 0.7)
	SetBlipColour (ropa, 47)
	SetBlipAsShortRange(ropa, true)

	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Tienda de ropa")
	EndTextCommandSetBlipName(ropa)
end)

Citizen.CreateThread(function()
	local ropa = AddBlipForCoord(-1192.61, -768.4, 17.32)
	SetBlipSprite (ropa, 366)
	SetBlipDisplay(ropa, 4)
	SetBlipScale  (ropa, 0.7)
	SetBlipColour (ropa, 47)
	SetBlipAsShortRange(ropa, true)

	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Tienda de ropa")
	EndTextCommandSetBlipName(ropa)
end)

Citizen.CreateThread(function()
	local ropa = AddBlipForCoord(425.91, -801.03, 29.49)
	SetBlipSprite (ropa, 366)
	SetBlipDisplay(ropa, 4)
	SetBlipScale  (ropa, 0.7)
	SetBlipColour (ropa, 47)
	SetBlipAsShortRange(ropa, true)

	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Tienda de ropa")
	EndTextCommandSetBlipName(ropa)
end)

Citizen.CreateThread(function()
	local ropa = AddBlipForCoord(-168.73, -301.41, 39.73)
	SetBlipSprite (ropa, 366)
	SetBlipDisplay(ropa, 4)
	SetBlipScale  (ropa, 0.7)
	SetBlipColour (ropa, 47)
	SetBlipAsShortRange(ropa, true)

	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Tienda de ropa")
	EndTextCommandSetBlipName(ropa)
end)

Citizen.CreateThread(function()
	local ropa = AddBlipForCoord(75.39, -1398.28, 29.38)
	SetBlipSprite (ropa, 366)
	SetBlipDisplay(ropa, 4)
	SetBlipScale  (ropa, 0.7)
	SetBlipColour (ropa, 47)
	SetBlipAsShortRange(ropa, true)

	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Tienda de ropa")
	EndTextCommandSetBlipName(ropa)
end)

Citizen.CreateThread(function()
	local ropa = AddBlipForCoord(-827.39, -1075.93, 11.33)
	SetBlipSprite (ropa, 366)
	SetBlipDisplay(ropa, 4)
	SetBlipScale  (ropa, 0.7)
	SetBlipColour (ropa, 47)
	SetBlipAsShortRange(ropa, true)

	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Tienda de ropa")
	EndTextCommandSetBlipName(ropa)
end)

Citizen.CreateThread(function()
	local ropa = AddBlipForCoord(-1445.86, -240.78, 49.82)
	SetBlipSprite (ropa, 366)
	SetBlipDisplay(ropa, 4)
	SetBlipScale  (ropa, 0.7)
	SetBlipColour (ropa, 47)
	SetBlipAsShortRange(ropa, true)

	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Tienda de ropa")
	EndTextCommandSetBlipName(ropa)
end)

Citizen.CreateThread(function()
	local ropa = AddBlipForCoord(9.22, 6515.74, 31.88)
	SetBlipSprite (ropa, 366)
	SetBlipDisplay(ropa, 4)
	SetBlipScale  (ropa, 0.7)
	SetBlipColour (ropa, 47)
	SetBlipAsShortRange(ropa, true)

	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Tienda de ropa")
	EndTextCommandSetBlipName(ropa)
end)

Citizen.CreateThread(function()
	local ropa = AddBlipForCoord(615.35, 2762.72, 42.09)
	SetBlipSprite (ropa, 366)
	SetBlipDisplay(ropa, 4)
	SetBlipScale  (ropa, 0.7)
	SetBlipColour (ropa, 47)
	SetBlipAsShortRange(ropa, true)

	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Tienda de ropa")
	EndTextCommandSetBlipName(ropa)
end)

Citizen.CreateThread(function()
	local ropa = AddBlipForCoord(1191.61, 2710.91, 38.22)
	SetBlipSprite (ropa, 366)
	SetBlipDisplay(ropa, 4)
	SetBlipScale  (ropa, 0.7)
	SetBlipColour (ropa, 47)
	SetBlipAsShortRange(ropa, true)

	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Tienda de ropa")
	EndTextCommandSetBlipName(ropa)
end)

Citizen.CreateThread(function()
	local ropa = AddBlipForCoord(-3171.32, 1043.56, 20.86)
	SetBlipSprite (ropa, 366)
	SetBlipDisplay(ropa, 4)
	SetBlipScale  (ropa, 0.7)
	SetBlipColour (ropa, 47)
	SetBlipAsShortRange(ropa, true)

	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Tienda de ropa")
	EndTextCommandSetBlipName(ropa)
end)

Citizen.CreateThread(function()
	local ropa = AddBlipForCoord(-1105.52, 2707.79, 19.11)
	SetBlipSprite (ropa, 366)
	SetBlipDisplay(ropa, 4)
	SetBlipScale  (ropa, 0.7)
	SetBlipColour (ropa, 47)
	SetBlipAsShortRange(ropa, true)

	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Tienda de ropa")
	EndTextCommandSetBlipName(ropa)
end)

Citizen.CreateThread(function()
	local ropa = AddBlipForCoord(-1119.24, -1440.6, 5.23)
	SetBlipSprite (ropa, 366)
	SetBlipDisplay(ropa, 4)
	SetBlipScale  (ropa, 0.7)
	SetBlipColour (ropa, 47)
	SetBlipAsShortRange(ropa, true)

	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Tienda de ropa")
	EndTextCommandSetBlipName(ropa)
end)

Citizen.CreateThread(function()
	local ropa = AddBlipForCoord(124.82, -224.36, 54.56)
	SetBlipSprite (ropa, 366)
	SetBlipDisplay(ropa, 4)
	SetBlipScale  (ropa, 0.7)
	SetBlipColour (ropa, 47)
	SetBlipAsShortRange(ropa, true)

	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Tienda de ropa")
	EndTextCommandSetBlipName(ropa)
end)

