Config = {}
Config['Locale'] = 'es'
Config['UsePolicejob'] = true -- cambiar a true si usas otro script que no se llame esx_policejob para cachear
Config['ScriptName'] = '' -- dejar esto en blanco si usas esx_policejob / sp_police ,si no esta activado el usepolicejob pon aqui el nombre del script que usas para cachear
Config['Key'] = 166 -- numero de tecla para añadir al menu
--Config['CinemodeCommand'] = 'modocine' -- comando que usa para para mostrar / ocultar modocine
--Config['HudCommand'] = 'hud' -- comando que usa para  ocultar / mostrar el hud
Config['IdShowCommand'] = 'verid' -- comando que usa para mostrar las ids
Config['IdHideCommand'] = 'noid' -- comando que usa para quitar las ids
Config['WeaponCommand'] = 'arma' -- comando que usa para mostrar las armas
Config['NoWeaponCommand'] = 'noarma' -- comando que usa para quitar las armas
Config['ModoCine'] = 'cinema' -- comando que usa para mostrar el modo cinematico
Config['ComandoTaxi'] = 'taxicall' -- comando que usa para llamar al taxista
Config['Habilidades'] = 'habilidades' -- comando que usa para ver las habilidades