function AddTextEntry(key, value)
	Citizen.InvokeNative(GetHashKey('ADD_TEXT_ENTRY'), key, value)
end
 --Buscar en vehicles.eta <gameName>
Citizen.CreateThread(function()
	AddTextEntry('lp700', 'Lamborghini LP700')
	AddTextEntry('amarok', 'Amarok')
	AddTextEntry('lp700r', 'Lamborghini LP700r')
	AddTextEntry('CHALLENGER', 'Dodge16')
	AddTextEntry('458', '458 Italia')
	AddTextEntry('911TURBOS', 'Porsche 911')
	AddTextEntry('bmws', 'BMW RR')
	AddTextEntry('corvetteZR1', 'Corvette')
	AddTextEntry('camrs17', 'Camaro RS')
	AddTextEntry('Charger2020', 'Charger')
	AddTextEntry('f8t', 'Ferrari f8t')
	AddTextEntry('grandgt18', 'Porsche 4x4 GT')
	AddTextEntry('H2M', 'Hummer H2m')
	AddTextEntry('hcbr17', 'CBR 1000')
	AddTextEntry('mcgt20', 'McLaren gt20')
	AddTextEntry('mcp1', 'McLaren P1')
	AddTextEntry('Dodge', 'Ram 2500')
	AddTextEntry('raptor2017', 'Velociraptor')
	AddTextEntry('rmodlp750', 'Lamborghini 750')
	AddTextEntry('rmodm4gts', 'BMW M4 GTS')
	AddTextEntry('BMWI8', 'BMW I8')
	AddTextEntry('rmodx6', 'BMW x6')
	AddTextEntry('senna', 'Senna')
	AddTextEntry('sq72016', 'Audi Q7')
	AddTextEntry('URUS', 'Lamborghini Urus')
	AddTextEntry('xc90', 'Volvo xc90')
	AddTextEntry('18Velar', 'RangeRover')
	AddTextEntry('206', 'Peugeot 206')
	AddTextEntry('405', 'Peugeot 405')
	AddTextEntry('fiat600', 'Fiat 600')
	AddTextEntry('gtrnismo17', 'Nissan GTR17')
	AddTextEntry('gtr', 'Nissan GTR')
	AddTextEntry('Volkswagen', 'Polo')
	AddTextEntry('Skyline', 'Skyline')
	AddTextEntry('SkylineGTR', 'Skyline')
	AddTextEntry('GL63', 'Mercedez GL 63')
	AddTextEntry('motobm', 'Patrulla de la policía')
	AddTextEntry('dodgecnp', 'Patrulla de la policía')
	AddTextEntry('pranger', 'Patrulla de la policía')
	AddTextEntry('MK7', 'Golf GTI')
	AddTextEntry('supraa90', 'Toyota Supra')
	AddTextEntry('civicfnf', 'Honda Civic')
	AddTextEntry('e2008', 'Peugeot 2008')
	AddTextEntry('ASTROPE', 'Jetta')
	AddTextEntry('divo', 'Bugatti Divo') 
	AddTextEntry('Clio2ph2', 'Clio 2')
	AddTextEntry('R8V10', 'AUDI R8')
	AddTextEntry('asea', 'Fiat Uno')
	AddTextEntry('regina', 'Renault 12')
	AddTextEntry('radi', 'Renault 19')
	AddTextEntry('blista', 'Scirocco')
	AddTextEntry('16cc', 'Passat')
	AddTextEntry('r1', 'Yamaha R1') 
	AddTextEntry('fugitive', 'Palio')
	AddTextEntry('zx10r', 'Kawa ZX10R')
	AddTextEntry('renault4', 'Renault 4')
	AddTextEntry('evoque', 'RR Evoque')
	AddTextEntry('raptor12', 'Raptor CS')
	AddTextEntry('Raptor', 'Raptor CD')
	AddTextEntry('RAPTOR150', 'RaptorMECA')
	AddTextEntry('CHARGER', 'Charger')
	AddTextEntry('ghis2', 'Maserati')
	AddTextEntry('MUSTANG', 'Mustang GT')
	AddTextEntry('ttrs', 'AUDI TT')
	AddTextEntry('GTI', '208 GTI')
	AddTextEntry('992t', 'Porsche Cabriot')
	AddTextEntry('HDFB', 'Choppers')
	AddTextEntry('HDKN', 'Western Choppers')
	AddTextEntry('POLICEB3', 'BFMECA') 
	AddTextEntry('SHIELD2', 'RPMECA')
	AddTextEntry('vodafone', 'CADDYMECA')
	AddTextEntry('s1000', 'Moto BMWSR')
	AddTextEntry('bmci', 'BMW M5')
	AddTextEntry('bmwm5f90', 'BMW M5')
	AddTextEntry('terzo', 'TERZO')
	AddTextEntry('velocir', 'Velociraptor')
	AddTextEntry('amggts2016', 'AMG')
	AddTextEntry('CALIFORNIAT', 'California') 
	AddTextEntry('f812', 'F-812') 
	AddTextEntry('meganers', 'Megane') 
	AddTextEntry('nissan', 'Nissan Titan')
	AddTextEntry('a6', 'Audi A6')
	AddTextEntry('r6', 'YAMAHA R6')
	AddTextEntry('lex570', 'Lexus 570')
	AddTextEntry('wald2018', 'Lexus 570')
	AddTextEntry('focusrs', 'Focus RS')
	AddTextEntry('208', '208')
	AddTextEntry('passat', 'Passat')
	AddTextEntry('dl2016', 'Ram')
	AddTextEntry('rs520', 'Audi RS5')
	AddTextEntry('punto', 'Punto')
	AddTextEntry('zr390', 'Kawasaki ZR')
	AddTextEntry('h2carb', 'Kawasaki H2')
	AddTextEntry('sls amg', 'SLS AMG')
	AddTextEntry('rmodgt63', 'Mercedez GT 63')
	AddTextEntry('SSTI', 'Subaru Impreza')
	AddTextEntry('G65AMG', 'AMG g65')
	AddTextEntry('agerars', 'Agerars')
	AddTextEntry('chiron', 'Chiron')
	AddTextEntry('21camaro', 'Camaro')
	AddTextEntry('nissantitan17', 'Titan 4x4')
	AddTextEntry('yzf', 'YZF 450')
	AddTextEntry('RS3LMS', 'AUDI RS3 LMS')
	AddTextEntry('RS3', 'AUDI RS3')
	AddTextEntry('s200', 'Honda s200')
	AddTextEntry('RSVR16', 'RangeRover')
	AddTextEntry('rmodveneno', 'Lambo Veneno')
	AddTextEntry('AUDIS1', 'AUDI S1')
	AddTextEntry('cullinan', 'Cullinan')
	AddTextEntry('DURANGO18', 'Durango')
	AddTextEntry('Wrangler', 'Jeep 12')
	AddTextEntry('BMECLIPSE95', 'ECLIPSE 95')
	AddTextEntry('F620', 'Maserati GT')
	AddTextEntry('golf75r', 'Golf R')
	AddTextEntry('mr53', 'MiniCooper')
	AddTextEntry('EVO9', 'F&F EVO')
	AddTextEntry('HUAYRAR', 'Pagani huayrar')
	AddTextEntry('Viper8', "Viper")
	AddTextEntry('str20', 'Porsche Cabriot')
	AddTextEntry('V4Speciale', 'Ducati Panigale V4')
	AddTextEntry('s500w223', 'S500w')
	AddTextEntry('cookiers6a', 'Audi RS6')
	AddTextEntry('m6f13', 'BMW M6')
	AddTextEntry('Vantage', 'Aston Martin GT')
	AddTextEntry('A-CLASS 2019', 'A-Class 2019')
	AddTextEntry('rmodskyline34', 'Skyline EXCLUSIVO')
	AddTextEntry('LP610', 'LAMBO LP610')
	AddTextEntry('AMGGT', 'AMGGT')
	AddTextEntry('LAFERRARI', 'FERRARI')
	AddTextEntry('CIVIC', 'Civic')
	AddTextEntry('918', 'Porsche 918')
	AddTextEntry('Supra A90', 'Supra A90')
	AddTextEntry('GLE53', 'GLE53')
	AddTextEntry('RX7TUNABLE', 'Mazda rx7')
	AddTextEntry('206 WRC', '206 WRC')
	AddTextEntry('S63C', 'S63C')
	AddTextEntry('Classe', 'A45amg')
	AddTextEntry('gs1', 'BMW R1200gs')
	AddTextEntry('DemonHawk', 'DemonHawk')
	AddTextEntry('xre300', 'YAMAHA XRE300')
	AddTextEntry('CBB', 'CBB')
	AddTextEntry('RAPIDGT', 'BMW M3')
	AddTextEntry('texviper','VIPER')
	AddTextEntry('20s63c', '20s63c')
	AddTextEntry('WRAITH','Rolls-Royce Wraith')
	AddTextEntry('dukeikx3', '911 CHAMBERS')
end)