Config = {}

-- Turn this to false if you want everyone to use this.
Config.OnlyPolicemen = true

-- This is how much ammo you should get per weapon you take out.
Config.ReceiveAmmo = 250
--452.4512,-980.162,30.689,272.59344482422
-- You don't need to edit these if you don't want to.
Config.Armory = { ["x"] = 452.4512, ["y"] = -980.162, ["z"] = 30.689, ["h"] = 272.59344482422} --default
--Config.Armory = { ["x"] = 452.3082, ["y"] = -979.983, ["z"] = 30.689, ["h"] = 266.84 } --comisaria 2 pisos 


--454.0432,-979.989,30.689,87.19563293457
Config.ArmoryPed = { ["x"] = 454.0432, ["y"] = -979.989, ["z"] = 30.689, ["h"] = 87.19563293457} --default
--Config.ArmoryPed = { ["x"] = 454.0461, ["y"] = -980.045, ["z"] = 30.689, ["h"] = 88.91, ["hash"] = 0x5E3DA4A4 } --s_m_y_cop_01 COMISARIA 2 pisos

-- This is the available weapons you can pick out.
Config.ArmoryWeapons = {
	recruit = {
		{ ["hash"] = "WEAPON_ASSAULTSMG", ["type"] = "rifle", ["tipo"] = "weapon" },
		--{ ["hash"] = "WEAPON_SMG", ["type"] = "rifle", ["tipo"] = "weapon" },
		--{ ["hash"] = "WEAPON_CARBINERIFLE_MK2", ["type"] = "rifle", ["tipo"] = "weapon" },
		{ ["hash"] = "WEAPON_COMBATPISTOL", ["type"] = "pistol", ["tipo"] = "weapon" },
		{ ["hash"] = "WEAPON_NIGHTSTICK", ["type"] = "pistol", ["tipo"] = "weapon" },
		{ ["hash"] = "WEAPON_STUNGUN", ["type"] = "pistol", ["tipo"] = "weapon" },
		{ ["hash"] = "WEAPON_FLASHLIGHT", ["type"] = "pistol", ["tipo"] = "v" },
		{ ["hash"] = "WEAPON_FIREEXTINGUISHER", ["type"] = "pistol", ["tipo"] = "weapon" },
		{ ["hash"] = "WEAPON_HEAVYPISTOL", ["type"] = "pistol", ["tipo"] = "weapon" },
		--{ ["hash"] = "WEAPON_PUMPSHOTGUN", ["type"] = "rifle", ["tipo"] = "weapon" },
		--{ ["hash"] = "WEAPON_SMOKEGRENADE", ["type"] = "pistol", ["tipo"] = "weapon" },
		--{ ["hash"] = "WEAPON_FLARE", ["type"] = "pistol", ["tipo"] = "weapon" },
		--{ ["hash"] = "GADGET_PARACHUTE", ["type"] = "pistol", ["tipo"] = "weapon" },
		--{ ["hash"] = "silenciador", ["type"] = "pistol", ["tipo"] = "item", ["label"] = "Silenciador" },
		--{ ["hash"] = "flashlight", ["type"] = "pistol", ["tipo"] = "item", ["label"] = "Linterna"},
		--{ ["hash"] = "binoculars", ["type"] = "pistol", ["tipo"] = "item", ["label"] = "Binoculares" },
	},
	officer = {
		{ ["hash"] = "WEAPON_ASSAULTSMG", ["type"] = "rifle", ["tipo"] = "weapon" },
		--{ ["hash"] = "WEAPON_CARBINERIFLE_MK2", ["type"] = "rifle", ["tipo"] = "weapon" },
		{ ["hash"] = "WEAPON_COMBATPISTOL", ["type"] = "pistol", ["tipo"] = "weapon" },
		{ ["hash"] = "WEAPON_NIGHTSTICK", ["type"] = "pistol", ["tipo"] = "weapon" },
		{ ["hash"] = "WEAPON_STUNGUN", ["type"] = "pistol", ["tipo"] = "weapon" },
		{ ["hash"] = "WEAPON_FLASHLIGHT", ["type"] = "pistol", ["tipo"] = "v" },
		{ ["hash"] = "WEAPON_FIREEXTINGUISHER", ["type"] = "pistol", ["tipo"] = "weapon" },
		{ ["hash"] = "WEAPON_FLAREGUN", ["type"] = "pistol", ["tipo"] = "weapon" },
		{ ["hash"] = "WEAPON_PUMPSHOTGUN", ["type"] = "rifle", ["tipo"] = "weapon" },
		{ ["hash"] = "WEAPON_SMOKEGRENADE", ["type"] = "pistol", ["tipo"] = "weapon" },
		{ ["hash"] = "WEAPON_FLARE", ["type"] = "pistol", ["tipo"] = "weapon" },
		{ ["hash"] = "GADGET_PARACHUTE", ["type"] = "pistol", ["tipo"] = "weapon" },
		--{ ["hash"] = "silenciador", ["type"] = "pistol", ["tipo"] = "item", ["label"] = "Silenciador" },
		{ ["hash"] = "flashlight", ["type"] = "pistol", ["tipo"] = "item", ["label"] = "Linterna"},
		--{ ["hash"] = "binoculars", ["type"] = "pistol", ["tipo"] = "item", ["label"] = "Binoculares" },
		{ ["hash"] = "WEAPON_CARBINERIFLE", ["type"] = "rifle", ["tipo"] = "weapon" },
		--{ ["hash"] = "WEAPON_CARBINERIFLE_MK2", ["type"] = "rifle", ["tipo"] = "weapon" },
		{ ["hash"] = "WEAPON_HEAVYPISTOL", ["type"] = "pistol", ["tipo"] = "weapon" },
	},
	sergeant = {
		{ ["hash"] = "WEAPON_ASSAULTSMG", ["type"] = "rifle", ["tipo"] = "weapon" },
		--{ ["hash"] = "WEAPON_SMG", ["type"] = "rifle", ["tipo"] = "weapon" },
		--{ ["hash"] = "WEAPON_CARBINERIFLE_MK2", ["type"] = "rifle", ["tipo"] = "weapon" },
		{ ["hash"] = "WEAPON_COMBATPISTOL", ["type"] = "pistol", ["tipo"] = "weapon" },
		{ ["hash"] = "WEAPON_NIGHTSTICK", ["type"] = "pistol", ["tipo"] = "weapon" },
		{ ["hash"] = "WEAPON_STUNGUN", ["type"] = "pistol", ["tipo"] = "weapon" },
		{ ["hash"] = "WEAPON_FLASHLIGHT", ["type"] = "pistol", ["tipo"] = "v" },
		{ ["hash"] = "WEAPON_FIREEXTINGUISHER", ["type"] = "pistol", ["tipo"] = "weapon" },
		{ ["hash"] = "WEAPON_FLAREGUN", ["type"] = "pistol", ["tipo"] = "weapon" },
		{ ["hash"] = "WEAPON_PUMPSHOTGUN", ["type"] = "rifle", ["tipo"] = "weapon" },
		{ ["hash"] = "WEAPON_SMOKEGRENADE", ["type"] = "pistol", ["tipo"] = "weapon" },
		{ ["hash"] = "WEAPON_FLARE", ["type"] = "pistol", ["tipo"] = "weapon" },
		{ ["hash"] = "GADGET_PARACHUTE", ["type"] = "pistol", ["tipo"] = "weapon" },
		{ ["hash"] = "silenciador", ["type"] = "pistol", ["tipo"] = "item", ["label"] = "Silenciador" },
		{ ["hash"] = "flashlight", ["type"] = "pistol", ["tipo"] = "item", ["label"] = "Linterna"},
		{ ["hash"] = "binoculars", ["type"] = "pistol", ["tipo"] = "item", ["label"] = "Binoculares" },
		{ ["hash"] = "WEAPON_CARBINERIFLE", ["type"] = "rifle", ["tipo"] = "weapon" },
		--{ ["hash"] = "WEAPON_CARBINERIFLE_MK2", ["type"] = "rifle", ["tipo"] = "weapon" },
		{ ["hash"] = "WEAPON_CARBINERIFLE_MK2", ["type"] = "rifle", ["tipo"] = "weapon" },
		{ ["hash"] = "WEAPON_HEAVYPISTOL", ["type"] = "pistol", ["tipo"] = "weapon" },
	},
	lieutenant = {
		{ ["hash"] = "WEAPON_ASSAULTSMG", ["type"] = "rifle", ["tipo"] = "weapon" },
		--{ ["hash"] = "WEAPON_SMG", ["type"] = "rifle", ["tipo"] = "weapon" },
		--{ ["hash"] = "WEAPON_CARBINERIFLE_MK2", ["type"] = "rifle", ["tipo"] = "weapon" },
		{ ["hash"] = "WEAPON_COMBATPISTOL", ["type"] = "pistol", ["tipo"] = "weapon" },
		{ ["hash"] = "WEAPON_NIGHTSTICK", ["type"] = "pistol", ["tipo"] = "weapon" },
		{ ["hash"] = "WEAPON_STUNGUN", ["type"] = "pistol", ["tipo"] = "weapon" },
		{ ["hash"] = "WEAPON_FLASHLIGHT", ["type"] = "pistol", ["tipo"] = "v" },
		{ ["hash"] = "WEAPON_FIREEXTINGUISHER", ["type"] = "pistol", ["tipo"] = "weapon" },
		{ ["hash"] = "WEAPON_FLAREGUN", ["type"] = "pistol", ["tipo"] = "weapon" },
		{ ["hash"] = "WEAPON_PUMPSHOTGUN", ["type"] = "rifle", ["tipo"] = "weapon" },
		{ ["hash"] = "WEAPON_SMOKEGRENADE", ["type"] = "pistol", ["tipo"] = "weapon" },
		{ ["hash"] = "WEAPON_FLARE", ["type"] = "pistol", ["tipo"] = "weapon" },
		{ ["hash"] = "GADGET_PARACHUTE", ["type"] = "pistol", ["tipo"] = "weapon" },
		{ ["hash"] = "silenciador", ["type"] = "pistol", ["tipo"] = "item", ["label"] = "Silenciador" },
		{ ["hash"] = "flashlight", ["type"] = "pistol", ["tipo"] = "item", ["label"] = "Linterna"},
		{ ["hash"] = "binoculars", ["type"] = "pistol", ["tipo"] = "item", ["label"] = "Binoculares" },
		{ ["hash"] = "WEAPON_CARBINERIFLE", ["type"] = "rifle", ["tipo"] = "weapon" },
		--{ ["hash"] = "WEAPON_CARBINERIFLE_MK2", ["type"] = "rifle", ["tipo"] = "weapon" },
		{ ["hash"] = "WEAPON_CARBINERIFLE_MK2", ["type"] = "rifle", ["tipo"] = "weapon" },
		{ ["hash"] = "WEAPON_HEAVYPISTOL", ["type"] = "pistol", ["tipo"] = "weapon" },
		--{ ["hash"] = "WEAPON_HEAVYSNIPER", ["type"] = "rifle", ["tipo"] = "weapon" },
	},
	inspect = {
		{ ["hash"] = "WEAPON_ASSAULTSMG", ["type"] = "rifle", ["tipo"] = "weapon" },
		--{ ["hash"] = "WEAPON_SMG", ["type"] = "rifle", ["tipo"] = "weapon" },
		--{ ["hash"] = "WEAPON_CARBINERIFLE_MK2", ["type"] = "rifle", ["tipo"] = "weapon" },
		{ ["hash"] = "WEAPON_COMBATPISTOL", ["type"] = "pistol", ["tipo"] = "weapon" },
		{ ["hash"] = "WEAPON_NIGHTSTICK", ["type"] = "pistol", ["tipo"] = "weapon" },
		{ ["hash"] = "WEAPON_STUNGUN", ["type"] = "pistol", ["tipo"] = "weapon" },
		{ ["hash"] = "WEAPON_FLASHLIGHT", ["type"] = "pistol", ["tipo"] = "v" },
		{ ["hash"] = "WEAPON_FIREEXTINGUISHER", ["type"] = "pistol", ["tipo"] = "weapon" },
		{ ["hash"] = "WEAPON_FLAREGUN", ["type"] = "pistol", ["tipo"] = "weapon" },
		{ ["hash"] = "WEAPON_PUMPSHOTGUN", ["type"] = "rifle", ["tipo"] = "weapon" },
		{ ["hash"] = "WEAPON_SMOKEGRENADE", ["type"] = "pistol", ["tipo"] = "weapon" },
		{ ["hash"] = "WEAPON_FLARE", ["type"] = "pistol", ["tipo"] = "weapon" },
		{ ["hash"] = "GADGET_PARACHUTE", ["type"] = "pistol", ["tipo"] = "weapon" },
		{ ["hash"] = "silenciador", ["type"] = "pistol", ["tipo"] = "item", ["label"] = "Silenciador" },
		{ ["hash"] = "flashlight", ["type"] = "pistol", ["tipo"] = "item", ["label"] = "Linterna"},
		{ ["hash"] = "binoculars", ["type"] = "pistol", ["tipo"] = "item", ["label"] = "Binoculares" },
		{ ["hash"] = "WEAPON_CARBINERIFLE", ["type"] = "rifle", ["tipo"] = "weapon" },
		--{ ["hash"] = "WEAPON_CARBINERIFLE_MK2", ["type"] = "rifle", ["tipo"] = "weapon" },
		{ ["hash"] = "WEAPON_CARBINERIFLE_MK2", ["type"] = "rifle", ["tipo"] = "weapon" },
		{ ["hash"] = "WEAPON_HEAVYPISTOL", ["type"] = "pistol", ["tipo"] = "weapon" },
		--{ ["hash"] = "WEAPON_HEAVYSNIPER", ["type"] = "rifle", ["tipo"] = "weapon" },
	},
	subcomi = {
		{ ["hash"] = "WEAPON_ASSAULTSMG", ["type"] = "rifle", ["tipo"] = "weapon" },
		--{ ["hash"] = "WEAPON_SMG", ["type"] = "rifle", ["tipo"] = "weapon" },
		--{ ["hash"] = "WEAPON_CARBINERIFLE_MK2", ["type"] = "rifle", ["tipo"] = "weapon" },
		{ ["hash"] = "WEAPON_COMBATPISTOL", ["type"] = "pistol", ["tipo"] = "weapon" },
		{ ["hash"] = "WEAPON_NIGHTSTICK", ["type"] = "pistol", ["tipo"] = "weapon" },
		{ ["hash"] = "WEAPON_STUNGUN", ["type"] = "pistol", ["tipo"] = "weapon" },
		{ ["hash"] = "WEAPON_FLASHLIGHT", ["type"] = "pistol", ["tipo"] = "v" },
		{ ["hash"] = "WEAPON_FIREEXTINGUISHER", ["type"] = "pistol", ["tipo"] = "weapon" },
		{ ["hash"] = "WEAPON_FLAREGUN", ["type"] = "pistol", ["tipo"] = "weapon" },
		{ ["hash"] = "WEAPON_PUMPSHOTGUN", ["type"] = "rifle", ["tipo"] = "weapon" },
		{ ["hash"] = "WEAPON_SMOKEGRENADE", ["type"] = "pistol", ["tipo"] = "weapon" },
		{ ["hash"] = "WEAPON_FLARE", ["type"] = "pistol", ["tipo"] = "weapon" },
		{ ["hash"] = "GADGET_PARACHUTE", ["type"] = "pistol", ["tipo"] = "weapon" },
		{ ["hash"] = "silenciador", ["type"] = "pistol", ["tipo"] = "item", ["label"] = "Silenciador" },
		{ ["hash"] = "flashlight", ["type"] = "pistol", ["tipo"] = "item", ["label"] = "Linterna"},
		{ ["hash"] = "binoculars", ["type"] = "pistol", ["tipo"] = "item", ["label"] = "Binoculares" },
		{ ["hash"] = "WEAPON_CARBINERIFLE", ["type"] = "rifle", ["tipo"] = "weapon" },
		--{ ["hash"] = "WEAPON_CARBINERIFLE_MK2", ["type"] = "rifle", ["tipo"] = "weapon" },
		{ ["hash"] = "WEAPON_CARBINERIFLE_MK2", ["type"] = "rifle", ["tipo"] = "weapon" },
		{ ["hash"] = "WEAPON_HEAVYPISTOL", ["type"] = "pistol", ["tipo"] = "weapon" },
		--{ ["hash"] = "WEAPON_HEAVYSNIPER", ["type"] = "rifle", ["tipo"] = "weapon" },
	},
	comi = {
		{ ["hash"] = "WEAPON_ASSAULTSMG", ["type"] = "rifle", ["tipo"] = "weapon" },
		--{ ["hash"] = "WEAPON_SMG", ["type"] = "rifle", ["tipo"] = "weapon" },
		--{ ["hash"] = "WEAPON_CARBINERIFLE_MK2", ["type"] = "rifle", ["tipo"] = "weapon" },
		{ ["hash"] = "WEAPON_COMBATPISTOL", ["type"] = "pistol", ["tipo"] = "weapon" },
		{ ["hash"] = "WEAPON_NIGHTSTICK", ["type"] = "pistol", ["tipo"] = "weapon" },
		{ ["hash"] = "WEAPON_STUNGUN", ["type"] = "pistol", ["tipo"] = "weapon" },
		{ ["hash"] = "WEAPON_FLASHLIGHT", ["type"] = "pistol", ["tipo"] = "v" },
		{ ["hash"] = "WEAPON_FIREEXTINGUISHER", ["type"] = "pistol", ["tipo"] = "weapon" },
		{ ["hash"] = "WEAPON_FLAREGUN", ["type"] = "pistol", ["tipo"] = "weapon" },
		{ ["hash"] = "WEAPON_PUMPSHOTGUN", ["type"] = "rifle", ["tipo"] = "weapon" },
		{ ["hash"] = "WEAPON_SMOKEGRENADE", ["type"] = "pistol", ["tipo"] = "weapon" },
		{ ["hash"] = "WEAPON_FLARE", ["type"] = "pistol", ["tipo"] = "weapon" },
		{ ["hash"] = "GADGET_PARACHUTE", ["type"] = "pistol", ["tipo"] = "weapon" },
		{ ["hash"] = "silenciador", ["type"] = "pistol", ["tipo"] = "item", ["label"] = "Silenciador" },
		{ ["hash"] = "flashlight", ["type"] = "pistol", ["tipo"] = "item", ["label"] = "Linterna"},
		{ ["hash"] = "binoculars", ["type"] = "pistol", ["tipo"] = "item", ["label"] = "Binoculares" },
		{ ["hash"] = "WEAPON_CARBINERIFLE", ["type"] = "rifle", ["tipo"] = "weapon" },
		--{ ["hash"] = "WEAPON_CARBINERIFLE_MK2", ["type"] = "rifle", ["tipo"] = "weapon" },
		{ ["hash"] = "WEAPON_CARBINERIFLE_MK2", ["type"] = "rifle", ["tipo"] = "weapon" },
		{ ["hash"] = "WEAPON_HEAVYPISTOL", ["type"] = "pistol", ["tipo"] = "weapon" },
		--{ ["hash"] = "WEAPON_HEAVYSNIPER", ["type"] = "rifle", ["tipo"] = "weapon" },
	},
	boss = {
		{ ["hash"] = "WEAPON_ASSAULTSMG", ["type"] = "rifle", ["tipo"] = "weapon" },
		--{ ["hash"] = "WEAPON_SMG", ["type"] = "rifle", ["tipo"] = "weapon" },
		--{ ["hash"] = "WEAPON_CARBINERIFLE_MK2", ["type"] = "rifle", ["tipo"] = "weapon" },
		{ ["hash"] = "WEAPON_COMBATPISTOL", ["type"] = "pistol", ["tipo"] = "weapon" },
		{ ["hash"] = "WEAPON_NIGHTSTICK", ["type"] = "pistol", ["tipo"] = "weapon" },
		{ ["hash"] = "WEAPON_STUNGUN", ["type"] = "pistol", ["tipo"] = "weapon" },
		{ ["hash"] = "WEAPON_FLASHLIGHT", ["type"] = "pistol", ["tipo"] = "v" },
		{ ["hash"] = "WEAPON_FIREEXTINGUISHER", ["type"] = "pistol", ["tipo"] = "weapon" },
		{ ["hash"] = "WEAPON_FLAREGUN", ["type"] = "pistol", ["tipo"] = "weapon" },
		{ ["hash"] = "WEAPON_PUMPSHOTGUN", ["type"] = "rifle", ["tipo"] = "weapon" },
		{ ["hash"] = "WEAPON_SMOKEGRENADE", ["type"] = "pistol", ["tipo"] = "weapon" },
		{ ["hash"] = "WEAPON_FLARE", ["type"] = "pistol", ["tipo"] = "weapon" },
		{ ["hash"] = "GADGET_PARACHUTE", ["type"] = "pistol", ["tipo"] = "weapon" },
		{ ["hash"] = "silenciador", ["type"] = "pistol", ["tipo"] = "item", ["label"] = "Silenciador" },
		{ ["hash"] = "flashlight", ["type"] = "pistol", ["tipo"] = "item", ["label"] = "Linterna"},
		{ ["hash"] = "binoculars", ["type"] = "pistol", ["tipo"] = "item", ["label"] = "Binoculares" },
		{ ["hash"] = "WEAPON_CARBINERIFLE", ["type"] = "rifle", ["tipo"] = "weapon" },
		--{ ["hash"] = "WEAPON_CARBINERIFLE_MK2", ["type"] = "rifle", ["tipo"] = "weapon" },
		{ ["hash"] = "WEAPON_CARBINERIFLE_MK2", ["type"] = "rifle", ["tipo"] = "weapon" },
		{ ["hash"] = "WEAPON_HEAVYPISTOL", ["type"] = "pistol", ["tipo"] = "weapon" },
		--{ ["hash"] = "WEAPON_HEAVYSNIPER", ["type"] = "rifle", ["tipo"] = "weapon" },
	},
}
