function AddTextEntry(key, value)
    Citizen.InvokeNative(GetHashKey("ADD_TEXT_ENTRY"), key, value)
end

Citizen.CreateThread(function()
function AddTextEntry(key, value)
    Citizen.InvokeNative(GetHashKey("ADD_TEXT_ENTRY"), key, value)
end

Citizen.CreateThread(function()
    AddTextEntry('rmodmustang', 'Ford Mustang')
    AddTextEntry('p1', 'Mclaren P1')
    AddTextEntry('amarok', 'Vw Amarok V6')
    AddTextEntry('jetta', 'Vw Vento')
    AddTextEntry('boricua', 'Vw Bora')
    AddTextEntry('2017chiron', 'Bugatti Chiron')
    AddTextEntry('350z', 'Nissan 350Z')
    AddTextEntry('370z16', 'Nissan 370Z')
    AddTextEntry('fiat', 'Fiat 147')
    AddTextEntry('180sx', 'Nissan 180sx')
    AddTextEntry('18s560', 'MB s560')
    AddTextEntry('206fn', 'Peugeot 206')
    AddTextEntry('500abarth', 'Fiat 500 Abarth')
    AddTextEntry('504', 'Peugeot 504')
    AddTextEntry('fiat600', 'Fiat 600')
    AddTextEntry('760li20', 'BMW 760')
    AddTextEntry('918concept', 'Porsche 918')
    AddTextEntry('ageraone', 'Koenigsegg Agera One:1')
    AddTextEntry('agerars', 'Koenigsegg Agera Rs')
    AddTextEntry('amggtrligth', 'MB AMG GTR (luces)')
    AddTextEntry('amgone', 'MB AMG ONE')
    AddTextEntry('lc500', 'Luxus LC500')
    AddTextEntry('2013rs7', 'Audi RS7')
    AddTextEntry('dtdbolide', 'Bugatti Bolide')
    AddTextEntry('bmci', 'BMW M5 F90')
    AddTextEntry('bentaygaplsd', 'Bentley Bentayga')
    AddTextEntry('m4', 'BMW M4 F82')
    AddTextEntry('m2f22', 'BMW M2 F22')
    AddTextEntry('m3e36', 'BMW M3 E36')
    AddTextEntry('brz13', 'Subaru BRZ')
    AddTextEntry('16ss', 'Chevrolet Camaro')
    AddTextEntry('c3ktem', 'Camello Tuneado')
    AddTextEntry('celgt4', 'Toyota Celica')
    AddTextEntry('16challenger', 'Dodge Challenger SRT8')
    AddTextEntry('cherokee96', 'Jeep Grand Cherokee ´96')
    AddTextEntry('trhawk', 'Jeep Grand Cherokee TrackHawk')
    AddTextEntry('2cv6naj', 'Citroën 2cv')
    AddTextEntry('civiccoupe', 'Honda Civic EK9 Coupe')
    AddTextEntry('civic', 'Honda Civic EXS')
    AddTextEntry('ek9', 'Honda Civic EK9 Hatch')
    AddTextEntry('astro88', 'Chevrolet Astro')
    AddTextEntry('camaro70', 'Chevrolet Camaro ´70')
    AddTextEntry('eldorado68', 'Cadillac El Dorado ´68')
    AddTextEntry('fleetline48', 'Chevrolet Fleetline ´48')
    AddTextEntry('gabmw507', 'BMW 507 ´58')
    AddTextEntry('gaford34', 'Ford Coupe ´34 HotRod')
    AddTextEntry('gaimpala59', 'Chevrolet Impala ´59')
    AddTextEntry('gaken49', 'Kenworth ´49')
    AddTextEntry('gtorino76', 'Ford Grand Torino ´76')
    AddTextEntry('metro59', 'Nash Metropolitan ´59')
    AddTextEntry('silv86', 'Chevrolet Silverado ´86')
    AddTextEntry('tbird64', 'Ford Thunderbird ´64')
    AddTextEntry('type262', 'Vw Kombi')
    AddTextEntry('white55', 'White Superpower')
    AddTextEntry('bville58', 'Cadillac De Ville ´58')
    AddTextEntry('chargersb', 'Dodge Charger ´71')
    AddTextEntry('fleet78', 'Cadillac Fleetwood ´78')
    AddTextEntry('jzeldo57', 'Cadillac El Dorado ´57')
    AddTextEntry('kustom', 'kustom')
    AddTextEntry('lancer57', 'Dodge Custom Royal ´57')
    AddTextEntry('mbenz220s', 'MB 220S')
    AddTextEntry('newyorker88', 'Chrysler New Yorker ´88')
    AddTextEntry('parklane', 'Mercury Park Lane Marauder')
    AddTextEntry('clio', 'Renault Clio Williams')
    AddTextEntry('clio2ph25', 'Renault Clio')
    AddTextEntry('cobaltss', 'Chevrolet Cobalt SS')
    AddTextEntry('bencongt13', 'Bentley Continental GT')
    AddTextEntry('corolla', 'Toyota Corolla')
    AddTextEntry('corsa', 'Chevrolet Corsa')
    AddTextEntry('c7', 'Chevrolet Corvette C7')
    AddTextEntry('corvettec5z06', 'Chevrolet Corvette C5')
    AddTextEntry('mansc8', 'Chevrolet Corvette C8')
    AddTextEntry('chrxfire', 'Chrysler Crossfire')
    AddTextEntry('sv', 'Lamborghini Diablo')
    AddTextEntry('divo', 'Bugatti Divo')
    AddTextEntry('dtdfenyrlb', 'Lykan Hypersport')
    AddTextEntry('eclipsegt06', 'Mitsubishi Eclipse')
    AddTextEntry('kpcai2', 'Honda C90')
    AddTextEntry('blista', 'Ford Escort XR3 2.0')
    AddTextEntry('f1', 'Formula 1')
    AddTextEntry('f430', 'Ferrari F430 Scuderia')
    AddTextEntry('4881', 'Ferrari 488')
    AddTextEntry('f8spider', 'Ferrari F8 spyder')
    AddTextEntry('enzo', 'Ferrari Enzo')
    AddTextEntry('fct', 'Ferrari California')
    AddTextEntry('fiat1300', 'Fiat 1300')
    AddTextEntry('fiat600', 'Fiat 600')
    AddTextEntry('fiat1', 'Fiat Uno')
    AddTextEntry('xls', 'Honda Fit')
    AddTextEntry('fluencetmspec', 'Renault Fluence')
    AddTextEntry('f100', 'Ford F100')
    AddTextEntry('gt17', 'Ford GT')
    AddTextEntry('fordka', 'Ford Ka')
    AddTextEntry('fe86', 'Ford Escort RS Turbo')
    AddTextEntry('buffalo', 'Ford Taunus')
    AddTextEntry('glendale', 'VW Fox')
    AddTextEntry('testarossa', 'Ferrrari Testarossa')
    AddTextEntry('fto', 'Mitsubishi FTO')
    AddTextEntry('blista3', 'Renault Fuego')
    AddTextEntry('g632021', 'MB G63 AMG')
    AddTextEntry('gencoupe', 'Hyundai Genesis')
    AddTextEntry('golf4', 'VW Golf MK4')
    AddTextEntry('golfgti7', 'VW Golf GTI MK7')
    AddTextEntry('mk3vr6', 'VW Golf MK3 VR6')
    AddTextEntry('gti8', 'VW Golf GTI MK8')
    AddTextEntry('mitsugto', 'Mitsubishi GTO')
    AddTextEntry('gtr', 'Nissan GTR')
    AddTextEntry('hellcat15w', 'Dodge Charger Hellcat')
    AddTextEntry('hilux', 'Toyota Hilux')
    AddTextEntry('fordhv2', 'Mustang Hoonicorn')
    AddTextEntry('bc', 'Pagani Huayra')
    AddTextEntry('infinitig35', 'Infiniti G35') 
    AddTextEntry('p7', 'Jaguar P7')
    AddTextEntry('cooperworks', 'Mini Cooper JCW')
    AddTextEntry('jeepreneg', 'Jeep Renegade')
    AddTextEntry('jeep2012', 'Jeep Wrangler Rubicon')
    AddTextEntry('kxf450', 'Kawasaki kxf450')
    AddTextEntry('laguna', 'Renault Laguna')
    AddTextEntry('cont88', 'Lamborghini Countach')
    AddTextEntry('lhuracan', 'Lamborghini Huracan')
    AddTextEntry('evo9', 'Mitsubishi Lancer Evo IX')
    AddTextEntry('lbdy01', 'Lamborghini Veneno')
    AddTextEntry('lc500', 'Lexus LC500')
    AddTextEntry('seatleon', 'Seat Leon')
    AddTextEntry('lgss', 'Lamborghini Gallardo Superleggera')
    AddTextEntry('m3f80', 'BMW M3 F80')
    AddTextEntry('m3e30', 'BMW M3 E30')
    AddTextEntry('m3e36', 'BMW M3 E36')    
    AddTextEntry('m4comp', 'BMW M4 Competition')
    AddTextEntry('e60', 'BMW M5 E60')
    AddTextEntry('m8gte', 'BMW M8 LeMans')
    AddTextEntry('macla', 'MB Clase A')
    AddTextEntry('brabus', 'MB GLS Brabus')
    AddTextEntry('gt63samg', 'MB GT63S AMG')
    AddTextEntry('senna', 'McLaren Senna')
    AddTextEntry('p1', 'McLaren P1')
    AddTextEntry('mgrantur2010', 'Maserati Gran Turismo')
    AddTextEntry('na6', 'Mazda Mx5 Miata')
    AddTextEntry('models', 'Tesla Model S')
    AddTextEntry('modelx', 'Tesla Model X')
    AddTextEntry('mondeo', 'Ford Mondeo')
    AddTextEntry('murus', 'Lamborghini Urus Mansory')
    AddTextEntry('rmodmustang', 'Ford Mustang Boss')
    AddTextEntry('boss302', 'Ford Mustang Boss 302')
    AddTextEntry('urban', 'Lada Niva')
    AddTextEntry('nova', 'Nova Hoonigan')
    AddTextEntry('ocnetrongt', 'Audi E-Tron')
    AddTextEntry('judge', 'Ponticas GTO')
    AddTextEntry('p911r', 'Porsche 911 GT2RS')
    AddTextEntry('prius', 'Toyota Prius')
    AddTextEntry('punto', 'Fiat Punto Evo')
    AddTextEntry('r33', 'Nissan Skyline GTR R33')
    AddTextEntry('r8ppi', 'Audi R8 V10')
    AddTextEntry('subaru7wrc', 'Subaru Impreza WRX BugEye')
    AddTextEntry('ram2500', 'RAM 2500')    
    AddTextEntry('ranger2019', 'Ford Ranger Raptor')
    AddTextEntry('renault4', 'Renault 4')
    AddTextEntry('rmodsupra', 'Toyota Supra MK4 Chuniado')
    AddTextEntry('rs318', 'Audi RS3')
    AddTextEntry('rs4avant', 'Audi RS4 Avant')
    AddTextEntry('coach', 'Bondi')
    AddTextEntry('hs2000', 'Honda S2000')
    AddTextEntry('scirocco', 'VW Scirocco')
    AddTextEntry('sierra', 'Ford Sierra Cosworth')
    AddTextEntry('silvias15', 'Nissan Silvia S15')
    AddTextEntry('silvia3', 'Nissan Silvia')
    AddTextEntry('skyline', 'Nissan Skyline GTR R34')
    AddTextEntry('fortwo', 'Smart ForTwo')
    AddTextEntry('wrx15', 'Subaru Impresa WRX STI')
    AddTextEntry('toysupmk4', 'Toyota Supra MK4')
    AddTextEntry('suran', 'Vw Suran')
    AddTextEntry('tesroad20', 'Tesla Roadster')
    AddTextEntry('ae86', 'Toyota Trueno')
    AddTextEntry('triton', 'Mitsubishi triton')
    AddTextEntry('trx', 'RAM TRX')
    AddTextEntry('aventador', 'Lamborghini Aventador')
    AddTextEntry('veln', 'Hyundai Veloster N')
    AddTextEntry('bvit', 'Bugatti Veyron')
    AddTextEntry('vip8', 'Dodge Viper')
    AddTextEntry('polo', 'Vw Polo')
    AddTextEntry('virtus', 'Vw Virtus')
    AddTextEntry('wmfenyrcop', 'POLI BMW Serie 3 Recuperado del Narcotrafico')
    AddTextEntry('ghispo2', 'SAME BMW X5')
    AddTextEntry('policeold1', 'POLI Iveco Dayli')
    AddTextEntry('hiluxpfa', 'POLI Toyota Hilux')
    AddTextEntry('metm', 'POLI Ford Mondeo')
    AddTextEntry('mpoli', 'POLI BMW moto')
    AddTextEntry('rangerpba', 'POLI Ford Ranger')
    AddTextEntry('sheriff2', 'SAME Ford Ranger')
    AddTextEntry('ambulance', 'SAME MB Sprinter')
    AddTextEntry('bus', 'Bondi Linea 25')
    AddTextEntry('cargobob', 'Helicoptero Benys')
    AddTextEntry('firetruck', 'BOMBEROS Iveco Trakker 500')
    AddTextEntry('pbus', 'Bondi Vacunate')
    AddTextEntry('police', 'POLI Toyota Hilux')
    AddTextEntry('police2', 'POLI Vw Touran')
    AddTextEntry('police3', 'POLI Ford Ranger')
    AddTextEntry('polmav', 'POLI Helicopteco Gendarmeria')
    AddTextEntry('307c', 'Peugeot 307')
    AddTextEntry('porrs73', 'Porsche 911 Carrera ´73')
    AddTextEntry('pgt3rs19', 'Porsche 911 GT3 RS')
    AddTextEntry('gxgiulia', 'Alfa Romeo Giulia Quadrifoglio')
    AddTextEntry('850', 'BMW 850CSI')
    AddTextEntry('70zr1', 'Chevrolet Corvette Stingray C3')
    AddTextEntry('tico', 'Daewoo Tico')
    AddTextEntry('gxevoviii', 'Mitsubishi Lancer Evo VIII')
    AddTextEntry('focusrs', 'Ford Focus RS')
    AddTextEntry('16challenger', 'Dodge Challenger')
    AddTextEntry('hilux1', 'Toyota Hilux Cabina Simple')
    AddTextEntry('na1', 'Honda NSX')
    AddTextEntry('22b', 'Subaru Impresa 22B')
    AddTextEntry('gxwrx', 'Subaru Impreza WRX STI 2016')
    AddTextEntry('lfa', 'Lexus LFA')
    AddTextEntry('mazrx7fb', 'Mazda RX7 FB')
    AddTextEntry('mcf1', 'McLaren F1')
    AddTextEntry('z32', 'Nissan 300ZX TwinTurbo')
    AddTextEntry('peugeot404', 'Peugeot 404')
    AddTextEntry('bnr32', 'Nissan Skyline GTR R32')
    AddTextEntry('rmodi8mlb', 'BMW i8')
    AddTextEntry('gxrx7', 'Mazda RX7 FD')
    AddTextEntry('rx8r', 'Mazda RX8')
    AddTextEntry('gxs14', 'Nissan Silvia S14')
    AddTextEntry('gxa90', 'Toyota Supra A90')
    AddTextEntry('tmfiatunot', 'Fiat Uno Turbo')
    AddTextEntry('uptsi', 'Vw Up! TSI')
    AddTextEntry('cd69', 'Chevrolet Nova')
    AddTextEntry('romeo155', 'Alfa Romeo 155 Quadrifoglio')
    AddTextEntry('208gti', 'Peugeot 208 GTI')
    AddTextEntry('habanero', 'Chevrolet Agile')
    AddTextEntry('speedo', 'MB Sprinter Andreani')
    AddTextEntry('stratum', 'Chevrolet Astra GSI')
    AddTextEntry('minivan', 'Citroën Berlingo')
    AddTextEntry('captur', 'Renault Captur')
    AddTextEntry('surge', 'Caballo Tuniado')
    AddTextEntry('cayenne', 'Porsche Cayenne Turbo')
    AddTextEntry('celta', 'Chevrolet Celta')
    AddTextEntry('cruze', 'Chevrolet Cruze')
    AddTextEntry('tc1', 'Chevrolet Cruze TC')
    AddTextEntry('fiorino', 'Fiat Cubo')
    AddTextEntry('baller', 'Renault Duster')
    AddTextEntry('dilettante', 'Fiat Tipo')
    AddTextEntry('emperor', 'Fiat Palio')
    AddTextEntry('focus2003', 'Ford Focus SVT')
    AddTextEntry('golfmk6', 'Vw Golf GTI MK6')
    AddTextEntry('moonbeam', 'Renault Kangoo')
    AddTextEntry('youga', 'Renault Master')
    AddTextEntry('trash', 'MB Actros Basura')
    AddTextEntry('romero', 'MB Clase E Funebre')
    AddTextEntry('primo2', 'Chevrolet Onix LTZ')
    AddTextEntry('flatbed', 'Ford Cargo Plancha')
    AddTextEntry('startechrr1', 'Land Rover Range Rover')
    AddTextEntry('emperor2', 'Renault 11 Turbo')
    AddTextEntry('twingo', 'Renault Twingo')
    AddTextEntry('s102019', 'Chevrolet S10')
    AddTextEntry('cog552', 'Nissan Sentra Nismo')
    AddTextEntry('tiptruck', 'MB Sprinter ACA')
    AddTextEntry('nissantitan17', 'Nissan Titan')
    AddTextEntry('jetta', 'Vw Vento')
end)
end)