Furniture = { 
    ['Categories'] = {
        {'television', 'Televisiones'},
        {'sofa', 'Sofas'},
        {'bed', 'Camas'},
        {'carpet', 'Alfombras'},
        {'paintings', 'Cuadros'},
        {'table', 'Mesas'},
        {'office', 'Oficina'},
        {'chair', 'Sillas'},
        {'rusticos', 'Muebles Rusticos'},
        {'modernos', 'Muebles Modernos'},
        {'electronics', 'Electronicos'},
        {'gym', 'Gimnasio'},
        {'fun', 'Diversion'},
        {'decorations', 'Decoraciones'},
        {'Plants', 'Plantas'},
        {'CashGoldJewels', 'Joyeria'},
        {'Drugs', 'Drugs'},
        {'FoodandDrinks','Comidas y Bebidas'},
        {'lights', 'Luces'},
        {'kitchen', 'Cocina'},
        {'bathroom', 'Baño'},
        {'Bins', 'Basurero'},
        {'accessory', 'Miscelaneos'},
        {'Storage', 'Almacen'},
        {'weapon', 'Armamento'},
        {'workbench', 'Mesa de Trabajo'},
    },

    ['television'] = {
	    {'Tube TV',  'v_ret_gc_tv',  0},
            {'TV Pequeña', 'prop_tv_02', 0},
            {'TV Gorda', 'prop_tv_06', 0},
	    {'Tube TV en mueble Blanco', 'v_res_j_tvstand', 0},
	    {'Television en Rack Viejo', 'v_serv_tvrack',  0},
	    {'Television de Pared', 'v_med_cor_flatscreentv',  0},
	    {'Standing Flatscreen', 'des_tvsmash_start',  0},
	    {'LCD Rolling Rack', 'xm_prop_x17_tv_stand_01a', 0},
	    {'TV Plana 1',  'prop_trev_tv_01',  0},
	    {'TV Plana 2', 'prop_tv_flat_03b', 0},
	    {'TV Plana 3', 'prop_tv_flat_02', 0},
	    {'TV Plana 4', 'xs_prop_arena_screen_tv_01',  0},
	    {'TV Plana 5', 'sm_prop_smug_tv_flat_01',  0},
	    {'TV Plana 6', 'prop_tv_flat_michael',  0},
	    {'TV Plana 7', 'xm_prop_x17_tv_flat_01',  0},
	    {'TV Plana 8', 'ba_prop_battle_club_screen_02', 0},
	    {'TV Plana 9', 'xm_prop_x17_tv_flat_02', 0},
	    {'TV Plana 0', 'ex_prop_ex_tv_flat_01',  0},
	    {'TV Plana 11', 'prop_tv_flat_01', 0},
	    {'Teatro en Casa 1', 'apa_mp_h_str_avunits_01', 0},
	    {'Teatro en Casa 2', 'apa_mp_h_str_avunitm_01', 10},
	    {'Teatro en Casa 3', 'apa_mp_h_str_avunitm_03', 10},
	    {'Teatro en Casa 4', 'apa_mp_h_str_avunits_04', 0},
	    {'Teatro en Casa 5', 'hei_heist_str_avunitl_03', 10},
	    {'Teatro en Casa 6', 'apa_mp_h_str_avunitl_01_b', 0},
	    {'Teatro en Casa 7', 'apa_mp_h_str_avunitl_04', 0},

    },

    ['chair'] = {

            {'Silla de ruedas', 'prop_wheelchair_01', 0},
	    {'Silla Vieja 1', 'v_res_m_dinechair', 0},
            {'Silla Vieja 2', 'prop_chair_07', 0},
            {'Silla Vieja 3', 'prop_rock_chair_01', 0},
            {'Silla Vieja 4', 'prop_torture_ch_01', 0},
	    {'Silla Vieja 5', 'v_res_fa_chair01', 0},
            {'Silla Vieja 6', 'prop_clown_chair', 0},
            {'Silla Vieja 7', 'prop_chair_06', 0},
            {'Silla Vieja 8', 'prop_gc_chair02', 0},
            {'Silla Vieja 9', 'v_corp_cd_chair', 0},
            {'Silla de Madera 1', 'prop_table_01_chr_a', 0},
            {'Silla de Madera 2', 'prop_table_01_chr_b', 0},
            {'Silla de Madera 3', 'prop_table_02_chr', 0},
	    {'Silla Rustica 1', 'v_ret_chair', 0},
	    {'Silla Rustica 2', 'v_ret_chair_white', 0},
	    {'Silla Rustica 3', 'p_dinechair_01_s', 0},
	    {'Silla Rustica 4', 'v_res_d_highchair', 0},
	    {'Silla de Oficina 1', 'prop_cs_office_chair', 0},
            {'Silla de oficina 2', 'prop_off_chair_05', 0},
	    {'Silla de Oficina 3', 'prop_off_chair_04b', 0},
            {'Silla de oficina 4', 'prop_off_chair_04_s', 0},
            {'Silla de oficina 5', 'prop_off_chair_04', 0},
            {'Silla de oficina 6', 'prop_off_chair_03', 0},
            {'Silla de oficina 7', 'v_corp_bk_chair3', 0},
            {'Silla de oficina 8', 'v_corp_offchair', 0},
	    {'Silla de Oficina 9', 'hei_prop_heist_off_chair', 0},
            {'Silla de oficina 0', 'prop_off_chair_01', 0},
            {'Silla de oficina 11', 'p_clb_officechair_s', 0},
            {'Silla de oficina 12', 'v_club_officechair', 0},
	    {'Silla de Oficina 13', 'sm_prop_offchair_smug_01', 0},
	    {'Silla de Oficina 14', 'v_ret_gc_chair03', 0},
            {'Silla de Oficina 15', 'p_soloffchair_s', 0},
            {'Silla de Oficina 16', 'prop_sol_chair', 0},
	    {'Silla de Oficina 17', 'sm_prop_offchair_smug_02', 0},
	    {'Silla Moderna 1', 'v_res_fh_barcchair', 0},
            {'Silla Moderna 2', 'v_corp_lazychair', 0},
	    {'Silla Moderna 3', 'v_res_fh_easychair', 0},
	    {'Silla Gamer', 'gr_prop_highendchair_gr_01a', 0},
	    {'Silla Gamer 2', 'xm_prop_x17_avengerchair', 20},
	    {'Silla de Comedor 1', 'apa_mp_h_din_chair_12', 0},
            {'Silla de Comedor 2', 'prop_chair_04a', 0},
            {'Silla de Comedor 3', 'prop_chair_04b', 0},
	    {'Silla de Comedor 4', 'v_res_study_chair', 0},
	    {'Silla de Comedor 5', 'v_res_fh_dineeamesa', 0},
	    {'Silla de Comedor 6', 'v_res_fh_dineeamesb', 0},
	    {'Silla de Comedor 7', 'hei_heist_din_chair_01', 0},
	    {'Silla de Comedor 8', 'apa_mp_h_din_chair_08', 0},
	    {'Silla de Comedor 9', 'hei_heist_din_chair_04', 0},
	    {'Silla de Comedor 0', 'v_res_fh_dineeamesc', 0},
	    {'Silla de Comedor 11', 'hei_heist_din_chair_05', 0},
	    {'Silla de Comedor 11', 'v_res_tre_chair', 0},
	    {'Silla de Comedor 12', 'v_corp_sidechair', 0},
	    {'Silla de Comedor 13', 'v_res_mbchair', 0},
	    {'Silla de Comedor 14', 'hei_heist_din_chair_02', 0},
            {'Silla de Comedor 15', 'prop_chair_09', 0},
            {'Silla de Comedor 16', 'prop_chateau_chair_01', 0},
	    {'Silla de Comedor 17', 'v_med_p_easychair', 0},
	    {'Silla Periquera 1', 'v_ret_gc_chair01', 0},
	    {'Silla Periquera 2', 'v_ret_ta_stool', 0},
	    {'Silla Periquera 3', 'apa_mp_h_stn_chairstool_12', 0},
	    {'Silla Periquera 4', 'ba_prop_int_glam_stool', 0},
	    {'Silla Periquera 5', 'v_res_fh_kitnstool', 0},
	    {'Silla Periquera 6', 'v_res_tre_stool_leather', 0},
	    {'Silla Periquera 7', 'apa_mp_h_yacht_barstool_01', 0},
	    {'Silla Periquera 8', 'bkr_prop_biker_barstool_02', 0},
	    {'Silla Periquera 9', 'v_club_bahbarstool', 0},
            {'Silla de Exterior 1', 'prop_direct_chair_01', 0},
            {'Silla de Exterior 2', 'prop_table_03b_chr', 0},
	    {'Silla de Exterior 3', 'prop_table_03_chr', 0},
            {'Silla de Exterior 4', 'v_ilev_chair02_ped', 0},
            {'Silla de Exterior 5', 'prop_chair_02', 0},
	    {'Silla de Exterior 6', 'prop_table_04_chr', 0},
            {'Silla de Exterior 7', 'prop_chair_01b', 0},
	    {'Silla de Exterior 8', 'v_res_trev_framechair', 0},
	    {'Silla de Exterior 9', 'prop_skid_chair_01', 0},
	    {'Silla de Exterior 0', 'prop_skid_chair_02', 0},
	    {'Silla de Exterior 11', 'prop_skid_chair_03', 0},
            {'Silla de Exterior 12', 'prop_skid_chair_03', 0},
	    {'Silla de Exterior 13', 'prop_table_05_chr', 0},
	    {'Silla de Exterior 14', 'prop_yacht_lounger', 0},

    },

    ['rusticos'] = {

            {'Mueble 1', 'v_res_mbbedtable', 0},
            {'Mueble 2', 'v_res_tre_bedsidetable', 0, true},
	    {'Mueble 3', 'prop_rub_cabinet02', 0},
	    {'Basic Chest of Drawers', 'prop_rub_cabinet01', 0},
            {'Mueble 4', 'v_ret_fh_displayc', 0},
            {'Mueble 5', 'v_res_d_sideunit', 0, true},
            {'Mueble 6', 'v_res_m_h_console', 0, true},
            {'Mueble 7', 'v_res_mbdresser', 0, true},
            {'Mueble 8', 'v_res_mconsolemod', 0, true},
            {'Mueble 9', 'v_res_mcupboard', 0, true},
            {'Mueble 0', 'v_res_m_armoire', 0, true},
            {'Mueble 11', 'v_res_cabinet', 0, true},
            {'Mueble 12', 'v_res_m_stool', 0, true},
	    {'Cajonera Blanca Chica', 'v_res_tre_bedsidetableb', 0},
            {'Cajonera Blanca Mediano', 'v_res_mdbedtable', 0, true},
            {'Cajonera Blanca Grande', 'v_res_tre_storageunit', 0, true},
            {'Cajonera Blanca Alta', 'v_res_mdchest', 0, true},
            {'Tocador Blanco 1', 'v_res_m_sidetable', 0},
	    {'Tocador Blanco 2', 'v_res_mddresser', 0},
            {'Tocador Blanco 3', 'v_res_d_dressingtable', 0},
            {'Librero Chico', 'v_res_tre_smallbookshelf', 0},
	    {'Librero Azul 1', 'v_res_tre_woodunit', 0},
            {'Librero Azul 2', 'v_res_tre_wdunitscuz', 0, true},


    },

    ['modernos'] = {

	    {'Mueble 1', 'prop_tv_cabinet_05', 0},
	    {'Mueble 2', 'v_res_tre_tvstand', 0},
	    {'Mueble 3', 'prop_tv_cabinet_04', 0},
	    {'Mueble 4', 'prop_tv_cabinet_03', 0},
            {'Mueble 5', 'v_res_tre_tvstand_tall', 0},
            {'Mueble 6', 'apa_mp_h_str_sideboards_02', 0, true},
            {'Mueble 7', 'apa_mp_h_str_sideboardl_09', 0, true},
            {'Mueble 8', 'hei_heist_str_sideboardl_03', 0, true},
            {'Mueble 9', 'apa_mp_h_str_sideboardl_11', 0, true},
            {'Mueble 0', 'apa_mp_h_str_sideboardl_14', 0, true},
            {'Mueble 11', 'apa_mp_h_str_sideboardm_02', 0, true},
            {'Mueble 12', 'v_res_fh_sidebrdlngb', 0, true},
            {'Mueble 13', 'apa_mp_h_str_sideboardl_13', 0, true},
            {'Mueble 14', 'apa_mp_h_str_sideboardl_06', 0, true},
            {'Mueble 15', 'apa_mp_h_str_sideboardm_03', 0, true},
            {'Mueble 16', 'apa_mp_h_str_sideboards_01', 0, true},
            {'Mueble 17', 'v_res_fh_sidebrddine', 0, true},
	    {'Small Bookshelves', 'apa_mp_h_str_shelfwallm_01', 0},
	    {'Large White Open Shelves', 'apa_mp_h_str_shelffreel_01', 0},
	    {'Wooden Storage Cabinet', 'apa_mp_h_str_shelffloorm_02', 0},
	    {'Mueble con Accesorios', 'v_res_msoncabinet', 0},
	    {'Mueble para Ropa', 'prop_venice_counter_01', 0},
	    {'Mesa de Cristal Lateral de Cama', 'apa_mp_h_tab_sidesml_02', 0},
	    {'Cajoneras Laterales de Cama 1', 'apa_mp_h_bed_table_wide_12', 0},
	    {'Cajoneras Laterales de Cama 2', 'hei_heist_bed_table_dble_04', 0},
            {'Baul Minimalista', 'prop_devin_box_closed', 0, true},
            {'Baul', 'v_res_tre_storagebox', 0},
	    {'Cajonera Chica', 'prop_cabinet_01b',  0, true},
	    {'Cajonera Mediana', 'hei_heist_bed_chestdrawer_04', 0, true},
	    {'Cajonera Grande', 'apa_mp_h_bed_chestdrawer_02', 0, true},
	    {'Closet Chico', 'v_res_tre_wardrobe',  0, true},
	    {'Closet Mediano', 'v_serv_cupboard_01', 0, true},
	    {'Closet Grande', 'v_med_cor_largecupboard', 30, true},

    },

    ['carpet'] = {


            {'Alfombra 1', 'p_yoga_mat_01_s',  0},  
            {'Alfombra 2', 'p_yoga_mat_02_s',  0}, 
            {'Alfombra 3', 'p_yoga_mat_03_s',  0},  
            {'Alfombra 4', 'prop_yoga_mat_01',  0},  
            {'Alfombra 5', 'prop_yoga_mat_02',  0},  
            {'Alfombra 6', 'prop_yoga_mat_03',  0},  
	    {'Alfombra 7', 'apa_mp_h_acc_rugwools_01',  0},
	    {'Alfombra 8', 'apa_mp_h_acc_rugwools_03', 0},
	    {'Alfombra 9', 'apa_mp_h_acc_rugwoolm_04', 0},
	    {'Alfombra 0', 'hei_heist_acc_rugwooll_01', 0},
	    {'Alfombra 11', 'apa_mp_h_acc_rugwoolm_02', 0},
	    {'Alfombra 12', 'apa_mp_h_acc_rugwoolm_03', 0},
	    {'Alfombra 13', 'apa_mp_h_acc_rugwooll_04', 0},
	    {'Alfombra 14', 'hei_heist_acc_rughidel_01', 0},
	    {'Alfombra 15', 'hei_heist_acc_rugwooll_02', 0},
	    {'Alfombra 16', 'hei_heist_acc_rugwooll_03', 0},
    },

    ['paintings'] = {

	    {'Cuadro 1', 'v_med_wallpicture1', 0},
	    {'Cuadro 2', 'v_med_wallpicture2', 0},
	    {'Cuadro 3', 'ex_mp_h_acc_artwallm_02', 0},
	    {'Cuadro 4', 'ex_mp_h_acc_artwallm_03', 0},
	    {'Cuadro 5', 'ex_mp_h_acc_artwallm_04', 0},
	    {'Cuadro 6', 'ex_p_h_acc_artwallm_03', 0},
	    {'Cuadro 7', 'ex_p_h_acc_artwallm_04', 0},
	    {'cuadro 8', 'apa_mp_h_acc_artwallm_04', 0},
	    {'Cuadro 9', 'apa_p_h_acc_artwalll_02', 0},
	    {'Cuadro 0', 'apa_mp_h_acc_artwalll_01', 0},
	    {'Cuadro 11', 'apa_p_h_acc_artwalll_04', 0},
	    {'Cuadro 12', 'ex_mp_h_acc_artwalll_02', 0},
	    {'Cuadro 13', 'ex_mp_h_acc_artwalll_03', 0},
	    {'Cuadro 14', 'ex_p_h_acc_artwalll_01', 0},
	    {'Cuadro 15', 'ex_p_h_acc_artwalll_03', 0},
	    {'Disco de Oro 1', 'hei_heist_acc_artgolddisc_01', 0},
	    {'Disco de Oro 2', 'hei_heist_acc_artgolddisc_02', 0},
	    {'Disco de Oro 3', 'hei_heist_acc_artgolddisc_03', 0},
	    {'Disco de Oro 4', 'hei_heist_acc_artgolddisc_04', 0},
	    {'Baseball Frame 1', 'apa_p_h_acc_artwalls_03', 0},
	    {'Baseball Frame 2', 'apa_p_h_acc_artwalls_04', 0},
    },


    ['decorations'] = {

	    {'Huevo de Alien', 'prop_alien_egg_01', 0},
	    {'Large Red Candle', 'v_res_m_candle', 0},
	    {'Large White Candle', 'v_res_m_candlelrg', 0},
	    {'Wall Clock', 'v_ret_gc_clock', 0},
	    {'Wall Mirror', 'v_ret_mirror', 0},
	    {'Cat Figurine', 'v_res_r_figcat', 0},
	    {'Clown Figurine', 'v_res_r_figclown', 0},
	    {'Framed Award', 'v_res_r_figauth2', 0},
	    {'Lady Figureing 1', 'v_res_r_figfemale', 0},
	    {'Lady Figurine 2', 'v_res_r_figflamenco', 0},
	    {'Girl Figurine', 'v_res_r_figgirl', 0},
	    {'Clown Figurine 2', 'v_res_r_figgirlclown', 0},
	    {'Oblisk', 'v_res_r_figoblisk', 0},
	    {'Pillar Sculpture', 'v_res_r_figpillar', 0},
	    {'Small Sculpture', 'v_res_sculpt_dec', 0},
	    {'1 Elephant Ornament', 'v_res_sculpt_decd', 0},
	    {'3 Elephant Ornament', 'v_res_sculpt_dece', 0},
	    {'Panther Figurine', 'v_res_sculpt_decf', 10},
	    {'White Vase', 'v_res_cherubvase', 0},
	    {'Brown Vase', 'v_res_mbronzvase', 0},
	    {'Jewellery Box', 'v_res_jewelbox', 0},
	    {'Linth', 'v_res_mplinth', 0},
	    {'Dirty Ashtray', 'v_res_mp_ashtrayb', 0},
	    {'Magazine Closed', 'v_res_fashmag1', 0},
	    {'Magazine Open', 'v_res_fashmagopen', 0},
	    {'Magazine Rack 2', 'v_res_fa_magtidy', 0},
	    {'Magazine Rack 2', 'v_res_j_magrack', 0},
	    {'Large Sculpture', 'v_res_fh_sculptmod', 0},
	    {'Chalk Board', 'v_res_mchalkbrd', 0},
            {'Botella', 'apa_mp_h_acc_bottle_01', 0},
            {'Velas', 'apa_mp_h_acc_candles_01', 0},
            {'Espejo', 'p_int_jewel_mirror', 0},
            {'Placa', 'apa_mp_h_acc_dec_plate_01', 0},
            {'Jarrón', 'apa_mp_h_acc_vase_01', 0},
            {'Jarrón 2', 'v_res_desktidy', 0},
	    {'Tall Basket', 'v_ret_fh_wickbskt', 0},
            {'Cenicero', 'ex_prop_ashtray_luxe_02', 0},
            {'Periodico', 'p_cs_newspaper_s', 0},
            {'Panfleto', 'p_cs_pamphlet_01_s', 0},
            {'Bong', 'prop_bong_01', 0},
            {'Frambuesa', 'prop_mr_rasberryclean', 0},
            {'Pizarra', 'p_planning_board_04', 0},
            {'Reloj 1', 'prop_hotel_clock_01', 0},
            {'Reloj 2', 'prop_big_clock_01', 0},
            {'Reloj 3', 'prop_egg_clock_01', 0},
            {'Pintura', 'v_ilev_ra_doorsafe', 0},
            {'Lazar', 'p_laz_j02_s', 0},
	    {'Ram Skull', 'v_res_d_ramskull', 0},
            {'Katana', 'prop_cs_katana_01', 0},
	    {'Letrero de Neon 1', 'prop_beer_neon_01', 0},
	    {'Letrero de Neon 2', 'prop_beer_neon_02', 0},
	    {'Letrero de Neon 3', 'prop_beer_neon_03', 0},
	    {'Letrero de Neon 4', 'prop_beer_neon_04', 0},
	    {'Letrero de Neon 5', 'prop_beerneon', 0},
	    {'Letrero de Neon 6', 'prop_barrachneon', 0},
	    {'Letrero de Neon 7', 'prop_patriotneon', 0},
	    {'Letrero de Neon 8', 'prop_cockneon', 0},
	    {'Letrero de Neon 9', 'prop_ragganeon', 0},
	    {'Letrero de Neon 0', 'prop_cherenneon', 0},
	    {'Letrero de Neon 11', 'prop_loggneon', 0},


    },
    ['table'] = {


            {'Mesa Vieja 1', 'prop_ld_farm_table02', 0},
            {'Mesa Vieja 2', 'prop_ld_farm_table01', 0},
            {'Mesa Vieja 3', 'prop_rub_table_01', 0},
            {'Mesa Vieja 4', 'prop_rub_table_02', 0},
	    {'Mesa Vieja 5', 'v_res_m_dinetble_replace', 0},
	    {'Mesa Rustica 1', 'v_res_msidetblemod', 0},
	    {'Mesa Rustica 2','v_res_m_dinetble', 0},
            {'Mesa Periquera 1', 'prop_table_07', 0},
	    {'Mesa Periquera 2', 'v_res_d_roundtable', 0},
	    {'Mesa Periquera 3', 'apa_mp_h_yacht_side_table_02', 0},
	    {'Mesa Periquera 4', 'apa_mp_h_tab_sidelrg_04', 0},
	    {'Mesa de Centro de Madera 1', 'prop_tablesmall_01', 0},
	    {'Mesa de Centro de Madera 2', 'v_ind_dc_table', 0},
	    {'Mesa de Centro de Madera 3', 'v_res_j_coffeetable', 0},
	    {'Mesa de Centro de Madera 4', 'v_corp_cd_rectable', 0},
            {'Mesa de Centro de Madera 5', 'prop_fbi3_coffee_table', 0},
            {'Mesa de Centro 1', 'hei_prop_yah_table_01', 0},
	    {'Mesa de Centro 2', 'hei_heist_tab_sidesml_02', 0},
	    {'Mesa de Centro 3', 'hei_heist_tab_sidesml_01', 0},
	    {'Mesa de Centro 4', 'v_res_d_coffeetable', 0},
	    {'Mesa de Centro 5', 'v_res_fh_coftablea', 0},
	    {'Mesa de Centro 6', 'v_res_fh_coftableb', 0},
	    {'Mesa de Centro 7', 'apa_mp_h_yacht_side_table_01', 0},
	    {'Mesa de Centro 8', 'ba_prop_int_edgy_table_01', 50},
	    {'Mesa de Centro 9', 'ba_prop_int_edgy_table_02', 0},
	    {'Mesa de Centro 0', 'hei_heist_tab_coffee_07', 0},
	    {'Mesa de Centro 11', 'apa_mp_h_tab_sidelrg_02', 0},
	    {'Mesa de Centro 12', 'apa_mp_h_tab_sidelrg_07', 0},
	    {'Mesa de Centro 13', 'hei_heist_tab_sidelrg_01', 50},
            {'Mesa de Centro 14', 'hei_prop_yah_table_02', 0},
	    {'Mesa de Centro 15', 'hei_heist_tab_coffee_06', 0},
	    {'Mesa de Centro 16', 'apa_mp_h_tab_coffee_08', 0},
	    {'Mesa de Centro 17', 'apa_mp_h_yacht_coffee_table_01', 0},
            {'Mesa de Centro 18', 'apa_mp_h_yacht_coffee_table_02', 0},
            {'Mesa de Centro 19', 'hei_heist_tab_coffee_05', 0},
	    {'Mesa de Centro 0', 'prop_t_coffe_table', 0},
	    {'Mesa de Centro 21', 'prop_t_coffe_table_02', 0},
	    {'Mesa de Centro 22', 'v_res_fh_coftbldisp', 0},
	    {'Comedor 1', 'v_res_tre_table01', 0},
            {'Comedor 2', 'hei_prop_yah_table_03', 0},
	    {'Comedor 3', 'v_ret_csr_table', 0},
            {'Comedor 4', 'prop_table_05', 0},
            {'Comedor 5', 'prop_chateau_table_01', 0},
	    {'Comedor 6', 'hei_heist_din_table_07', 0},
	    {'Comedor 7', 'hei_heist_din_table_04', 0},
	    {'Comedor 8', 'apa_mp_h_din_table_11', 0},
	    {'Comedor 9', 'hei_heist_din_table_01', 0},
            {'Comedor 0', 'v_ilev_liconftable_sml', 0},
            {'Mesa de Plastico 1', 'prop_table_03b', 0},
            {'Mesa de Plastico 2', 'prop_table_03', 0},
	    {'Mesa de Plastico 3', 'prop_table_03', 0},
            {'Mesa de Plastico 4', 'prop_ven_market_table1', 0},
	    {'Mesa de Plastico 5', 'apa_mp_h_din_table_06', 0},
            {'Mesa de Madera 1', 'prop_table_08', 0},
            {'Mesa de Madera 2', 'prop_picnictable_01', 0},
            {'Mesa de Madera 3', 'prop_table_01', 0},
            {'Mesa de Madera 4', 'prop_table_04', 0},
            {'Mesa de Madera 5', 'prop_proxy_chateau_table', 0},
            {'Mesa de Madera 6', 'prop_table_02', 0},

    },
    ['office'] = {

            {'Escritorio 1', 'v_res_son_desk', 0}, 
            {'Escritorio 2', 'prop_office_desk_01', 0}, 
            {'Escritorio 3', 'v_res_mddesk', 0},
	    {'Escritorio 4', 'xm_prop_lab_desk_01', 0},
	    {'Escritorio 5', 'xm_prop_lab_desk_02', 0},
	    {'Escritorio 6', 'v_med_p_desk', 0},
	    {'Escritorio 7', 'xm_base_cia_desk1', 0},
	    {'Escritorio 8', 'v_corp_maindesk', 0},
	    {'Escritorio 9', 'v_corp_deskseta', 0},
	    {'Escritorio 0', 'v_corp_desksetb', 0},
	    {'Escritorio 11', 'v_corp_officedesk1', 0},
	    {'Escritorio 12', 'v_corp_officedesk', 0},
	    {'Escritorio 13', 'xm_prop_base_staff_desk_01', 0},
	    {'Escritorio 14', 'xm_prop_base_staff_desk_02', 0},
	    {'Escritorio 15', 'xm_base_cia_data_desks', 0},
	    {'Escritorio 16', 'v_ilev_liconftable_sml', 0},
	    {'Escritorio 17', 'v_corp_conftable2', 0},
	    {'Escritorio 18', 'v_corp_conftable3', 0},
	    {'Escritorio 19', 'v_corp_conftable4', 0},
            {'Pizarra 1', 'v_corp_divide', 0},
	    {'Archivero 1', 'v_corp_deskdraw', 0, true},
	    {'Archivero 2', 'v_corp_deskdrawdark01', 0, true},
            {'Archivero 3', 'prop_fbibombfile', 0, true},
            {'Archivero 4', 'v_corp_filecablow', 0},
            {'Archivero 5', 'v_corp_filecabdark01', 0},
            {'Archivero 6', 'prop_cabinet_01', 0, true},
            {'Archivero 7', 'prop_cabinet_02b', 0, true},
            {'Archivero 8', 'v_corp_filecabtall', 0, true},
            {'Archivero 9', 'v_corp_filecabdark02', 0, true},
            {'Archivero 0', 'v_corp_offshelfclo', 0, true},
            {'Librero 1', 'v_corp_offshelfdark', 0},
            {'Librero 2', 'v_corp_offshelf', 0},
            {'Porta Hojas 1', 'prop_folder_02', 0},
            {'Porta Hojas 2', 'prop_inout_tray_02', 0},
            {'Porta Hojas 3', 'prop_folder_01', 0},
            {'Porta Hojas 4', 'v_ret_gc_trays', 0},
            {'Porta Plumas', 'v_res_desktidy', 0},
            {'Sillon de Espera', 'prop_wait_bench_01', 0},

    },

    ['fun'] = {

	    {'Gumball', 'prop_gumball_01', 0},
	    {'Gumball 2', 'prop_gumball_02', 0},
	    {'Gumball 3', 'prop_gumball_03', 0},
	    {'Jukebox 1', 'prop_jukebox_01', 0},
	    {'Jukebox 2', 'prop_jukebox_02', 0},
	    {'Jukebox 3', 'bkr_prop_clubhouse_jukebox_01b', 0},
	    {'Jukebox 4', 'bkr_prop_clubhouse_jukebox_01a', 0},
	    {'Jukebox 5', 'bkr_prop_clubhouse_jukebox_02a', 0},
	    {'Arcade 1', 'prop_arcade_01', 0},
	    {'Arcade 2', 'prop_arcade_02', 0},
	    {'Arcade Ball', 'prop_bball_arcade_01', 0},
	    {'Skateboard', 'v_res_skateboard', 0},
	    {'Bola blanca de Billard', 'prop_poolball_cue', 0},
	    {'Bola de Billar 1', 'prop_poolball_1', 0},
	    {'Bola de Billar 2', 'prop_poolball_2', 0},
	    {'Bola de Billar 3', 'prop_poolball_3', 0},
	    {'Bola de Billar 4', 'prop_poolball_4', 0},
	    {'Bola de Billar 5', 'prop_poolball_5', 0},
	    {'Bola de Billar 6', 'prop_poolball_6', 0},
	    {'Bola de Billar 7', 'prop_poolball_7', 0},
	    {'Bola de Billar 8', 'prop_poolball_8', 0},
	    {'Bola de Billar 9', 'prop_poolball_9', 0},
	    {'Bola de Billar 0', 'prop_poolball_0', 0},
	    {'Bola de Billar 11', 'prop_poolball_11', 0},
	    {'Bola de Billar 12', 'prop_poolball_12', 0},
	    {'Bola de Billar 13', 'prop_poolball_13', 0},
	    {'Bola de Billar 14', 'prop_poolball_14', 0},
	    {'Bola de Billar 15', 'prop_poolball_15', 0},
	    {'Taco de Billar', 'prop_pool_cue', 0},
	    {'Rack Tacos de Billar 1', 'prop_pool_rack_01', 0},
	    {'Rack Tacos de Billar 2', 'prop_pool_rack_02', 0},
	    {'Mesa de Billar', 'prop_pooltable_02', 0},
	    {'Mesa de Billar', 'prop_pooltable_3b', 0},
	    {'Red Airhockey Paddle', 'prop_air_hoc_paddle_01', 0},
            {'Blue Airhockey Paddle', 'prop_air_hoc_paddle_02', 0},
	    {'Mesa de Hockey', 'prop_airhockey_01', 0},
            {'Mesa de Tennis', 'prop_table_tennis', 0},
            {'Tablero de Dardos', 'prop_dart_bd_cab_01', 0},
            {'Tablero de Dardos 2', 'prop_dart_bd_01', 0},
            {'Mesa de Tennis', 'prop_table_tennis', 0},
	    {'Guitara 1', 'prop_acc_guitar_01', 0},
	    {'Guitara 2', 'prop_acc_guitar_01_d1', 0},
	    {'Guitara Electrica 1', 'prop_el_guitar_01', 0},
	    {'Guitara Electrica 2', 'prop_el_guitar_02', 0},
	    {'Guitara Electrica 3', 'prop_el_guitar_03', 0},
	    {'Soporte de Guitarra', 'v_club_roc_gstand', 0},
	    {'Microfono', 'v_club_roc_micstd', 0},
	    {'Controlador DJ 1', 'prop_dj_deck_01', 0},
	    {'Controlador Dj 2', 'prop_dj_deck_02', 0},
	    {'Controlador Dj 3', 'v_club_vu_deckcase', 0},
	    {'Equipo de DJ', 'v_club_vu_djunit', 0},
	    {'Mixer 1', 'v_club_roc_mixer2', 0},
	    {'Mixer 2', 'v_club_roc_mixer1', 0},
	    {'Ecualizador 1', 'v_club_roc_eq1', 0},
	    {'Ecualizador 2', 'v_club_roc_eq2', 0},
	    {'Ecualizador 3', 'v_club_roc_cabamp', 0},
	    {'Amplificador', 'prop_amp_01', 0},
	    {'Bafle 1', 'v_club_roc_cab3', 0},
	    {'Bafle 2', 'v_club_roc_cab2', 0},
	    {'Bafle 3', 'v_club_roc_cab1', 0},
	    {'Bafle 4', 'v_club_roc_monitor', 0},
	    {'Luces 1', 'prop_studio_light_02', 0},
	    {'Luces 2', 'prop_studio_light_01', 0},
            {'Luces 3', 'prop_kino_light_03', 0},
            {'Luces 4', 'prop_kino_light_02', 0},
            {'Luces 4', 'prop_kino_light_01', 0},
	    {'Iluminacion 1', 'v_club_roc_spot_b', 0},
	    {'Iluminacion 2', 'v_club_roc_spot_y', 0},
	    {'Iluminacion 3', 'v_club_roc_spot_r', 0},
	    {'Iluminacion 4', 'v_club_roc_spot_g', 0},
	    {'Iluminacion 5', 'v_club_roc_spot_w', 0},
    },

    ['gym'] = {

            {'Bicicleta de ejercicio', 'prop_exercisebike', 0},
            {'Bicicleta de ejercicio 2', 'prop_exer_bike_01', 0},
            {'Bicicleta de ejercicio 3', 'prop_exer_bike_mg', 0},
	    {'Caminadora', 'apa_p_apdlc_treadmill_s', 0},
	    {'Maquina Eliptica', 'apa_p_apdlc_crosstrainer_s', 0},
	    {'Maquina Eliptica 2', 'hei_heist_crosstrainer_s', 0},
	    {'Barras de Calistenia 1', 'prop_beach_bars_01', 0},
	    {'Barras de Calistenia 2', 'prop_beach_bars_02', 0},
	    {'Barras de Calistenia 3', 'prop_beach_dip_bars_01', 0},
	    {'Barras de Calistenia 4', 'prop_beach_dip_bars_02', 0},
	    {'Anillos de Calistenia', 'prop_beach_rings_01', 0},
	    {'Pelota de Boxeo', 'prop_beach_punchbag', 0},
	    {'Pelota de Boxeo', 'prop_beach_punchbag', 0},
	    {'Pelota de Boxeo 2', 'prop_speedball_01', 0},
	    {'Banco de Pesas 1', 'prop_pris_bench_01', 0},
	    {'Banco de Pesas 2', 'prop_muscle_bench_03', 0},
	    {'Banco de Pesas 3', 'prop_weight_bench_02', 0},
	    {'Banco de Calistenia', 'prop_muscle_bench_05', 0},
	    {'Banco de Abdominales 1', 'prop_muscle_bench_01', 0},
	    {'Banco de Abdominales 2', 'prop_muscle_bench_02', 0},
	    {'Banco de Abdominales 3', 'prop_muscle_bench_04', 0},
	    {'Banco de Piernas', 'prop_muscle_bench_06', 0},
	    {'Rack de Pesas', 'prop_weight_squat', 0},
	    {'Rack de Mancuernas', 'prop_weight_rack_02', 0},
	    {'Rack de Discos de Pesas', 'prop_weight_rack_01', 0},
	    {'Mancuernas', 'prop_barbell_01', 0},
	    {'Pesas', 'prop_barbell_02', 0},
	    {'Pesas 0kg', 'prop_barbell_0kg', 0},
	    {'Pesas 0kg', 'prop_barbell_0kg', 0},
	    {'Pesas 0kg', 'prop_barbell_0kg', 0},
	    {'Pesas 0kg', 'prop_barbell_0kg', 0},
	    {'Pesas 0kg', 'prop_barbell_0kg', 0},
	    {'Pesas 0kg', 'prop_barbell_0kg', 0},
	    {'Pesas 0kg', 'prop_barbell_0kg', 0},
	    {'Pesas 0kg', 'prop_barbell_0kg', 0},

    },

    ['electronics'] = {

            {'Alarma 1', 'v_res_fh_bedsideclock', 0},
	    {'Alarma 2', 'v_res_fa_radioalrm', 0},
	    {'Radio', 'prop_radio_01', 0},
            {'Boomboox 1', 'prop_portable_hifi_01', 0},
            {'Boomboox 2', 'prop_ghettoblast_01', 0},
            {'Boomboox 3', 'prop_ghettoblast_02', 0},
            {'Boomboox Grande', 'prop_el_tapeplayer_01', 0},
	    {'Docking Station 1', 'v_res_ipoddock', 0},
	    {'Docking Station 2', 'v_res_fh_speakerdock', 0},
            {'Bocina 1', 'v_res_pcspeaker', 0},
	    {'Bocina 2', 'prop_speaker_02', 0},
	    {'Bocina 3', 'prop_speaker_05', 0},
	    {'Bocina 4', 'prop_speaker_06', 0},
	    {'Bocina 5', 'prop_speaker_08', 0},
	    {'Bocina 6', 'prop_speaker_03', 50},
	    {'Bocina 7', 'prop_speaker_07', 0},
	    {'Bocina 8', 'prop_speaker_01', 0},
	    {'Woofer 8', 'v_res_pcwoofer', 0},
	    {'Corner Speaker', 'v_res_fh_speaker', 0},
	    {'Camara de Seguridad', 'prop_cctv_cam_07a', 0},
	    {'Camara de Seguridad', 'prop_cctv_cam_06a', 0},
	    {'Camara de Seguridad', 'prop_cctv_cam_05a', 0},
	    {'Camara de Seguridad', 'prop_cctv_cam_03a', 0},
	    {'Camara de Seguridad', 'prop_cctv_cam_02a', 0},
	    {'Camara de Seguridad', 'prop_cctv_cam_01a', 0},
	    {'Camara de Seguridad', 'prop_cctv_cam_01b', 0},
	    {'Camara de Seguridad', 'prop_cs_cctv', 0},
	    {'Control Camara de Seguridad', 'prop_cctv_cont_02', 0},
	    {'Control Camara de Seguridad', 'prop_cctv_cont_01', 0},
	    {'Control Camara de Seguridad', 'prop_cctv_cont_03', 0},
	    {'TV para Camara de Seguridad', 'prop_cctv_01_sm_02', 0},
	    {'TV para Camara de Seguridad', 'prop_cctv_01_sm', 0},
	    {'TV para Camara de Seguridad', 'prop_dest_cctv_03b', 0},
	    {'TV para Camara de Seguridad', 'v_res_cctv', 0},
	    {'TV para Camara de Seguridad', 'prop_cctv_unit_05', 0},
	    {'TV para Camara de Seguridad', 'prop_cctv_02_sm', 0},
	    {'TV para Camara de Seguridad', 'prop_cctv_unit_04', 0},
	    {'TV para Camara de Seguridad', 'prop_cctv_unit_03', 0},
	    {'TV para Camara de Seguridad', 'prop_cctv_unit_01', 0},
	    {'TV para Camara de Seguridad', 'prop_cctv_unit_02', 0},
	    {'TV para Camara de Seguridad', 'prop_cctv_mon_02', 0},
	    {'Camara Fotografica 1', 'prop_ing_camera_01', 0},
	    {'Camara Fotografica 2', 'prop_pap_camera_01', 0},
	    {'Camara de Video Fija', 'p_tv_cam_02_s', 0},
	    {'Camara de Video', 'prop_v_cam_01', 0},
            {'Celular viejo', 'prop_v_m_phone_o1s', 0},
            {'Celular', 'p_amb_phone_01', 0},
	    {'Telefono de Pared', 'v_res_fa_phone', 0},
            {'Telefono de oficina', 'prop_office_phone_tnt', 0},
            {'Telefono de oficina 2', 'v_ret_gc_phone', 0},
            {'Telefono de oficina 3', 'prop_off_phone_01', 0},
            {'Telefono CS', 'prop_cs_phone_01', 0},
            {'Tableta 1', 'prop_cs_tablet_02', 0},
            {'Microfono', 'prop_table_mic_01', 0},
            {'Gamepad', 'prop_controller_01', 0},
            {'Gamepad', 'p_controller_01_s', 0},
            {'Consola de Juegos', 'prop_console_01', 0},
            {'Reproductor VHS', 'v_res_vhsplayer', 0},
            {'Video Grabadora', 'prop_vcr_01', 0},
            {'Reproductor DVD 1', 'v_res_tre_dvdplayer', 0},
            {'Reproductor DVD 2', 'prop_cs_dvd_player', 0},
            {'Reproductor Stereo', 'prop_hifi_01', 0},
            {'Monitor 1', 'prop_monitor_01a', 0},
            {'Monitor 2', 'prop_monitor_01c', 0},
            {'Monitor 3', 'prop_monitor_02', 0},
            {'Monitor 4', 'prop_monitor_li', 0},
	    {'Monitor 5', 'prop_ld_monitor_01', 0},
	    {'Monitor 6', 'prop_monitor_01b', 0},
	    {'Monitor 7', 'prop_monitor_01d', 0},
	    {'Monitor 8', 'prop_monitor_01c', 0},
	    {'Monitor 09', 'v_res_monitorsquare', 0},
	    {'Monitor 0', 'v_res_monitor', 0},
	    {'Monitor 11', 'v_res_lest_monitor', 0},
	    {'Monitor 12', 'prop_monitor_w_large', 0},
	    {'Monitor 13', 'prop_monitor_04a', 0},
	    {'Monitor 14', 'xm_prop_x17_computer_02', 0},
	    {'Monitor 15', 'v_res_monitorwidelarge', 0},
	    {'Monitor 16', 'xm_prop_staff_screens_01', 0},
	    {'Monitor 17', 'xm_prop_x17_screens_01a', 0},
	    {'Monitor 18', 'xm_prop_x17_tv_ceiling_01', 0},
	    {'Monitor 19', 'xm_prop_x17_screens_02a', 0},
            {'Mac PC 1', 'prop_trailer_monitor_01', 0},
	    {'Mac PC 2', 'xm_prop_x17_computer_01', 0},
	    {'Laptop 1', 'prop_laptop_jimmy', 0},
	    {'Laptop 2', 'prop_laptop_lester', 0},
            {'Laptop 3', 'p_amb_lap_top_02', 0},
            {'Laptop 4', 'p_cs_laptop_02', 0},
            {'Laptop 5', 'v_ind_ss_laptop', 0},
            {'Laptop 6', 'xm_prop_x17_laptop_mrsr', 0},
            {'Laptop 7', 'xm_prop_x17_laptop_avon', 0},
            {'Laptop 8', 'xm_prop_x17_laptop_agent14_01', 0},
            {'Laptop 9', 'xm_prop_x17_laptop_lester_01', 0},
            {'Portatil cerrado', 'p_cs_laptop_02_w', 0},
            {'Gabinete PC 1', 'prop_pc_01a', 0},
            {'Gabinete PC 2', 'prop_dyn_pc_02', 0},
	    {'Gabinete PC 3', 'hei_prop_heist_pc_01', 0},
	    {'Gabinete PC 4', 'prop_dyn_pc', 0},
	    {'Gabinete PC 5', 'prop_pc_02a', 0}, 
            {'Teclado 1', 'prop_keyboard_01a', 0},
            {'Teclado 2', 'hei_prop_hei_cs_keyboard', 0},
            {'Teclado 3', 'prop_cs_keyboard_01', 0},
            {'Teclado 4', 'prop_keyboard_01b', 0},
            {'Mouse 1', 'prop_cs_mouse_01', 0},
            {'Mouse 2', 'prop_mouse_01a', 0},
            {'Mouse 3', 'prop_mouse_01b', 0},
            {'Mouse 4', 'v_res_mousemat', 0},
            {'Calculadora 1', 'prop_ld_keypad_01b', 0},
            {'Calculadora 2', 'prop_ld_keypad_01', 0},
            {'Fotocopiadora', 'prop_copier_01', 0},
            {'Impresora 1', 'v_res_printer', 0},
            {'Impresora 2', 'prop_printer_01', 0},
            {'Impresora 3', 'v_ret_gc_print', 0},
            {'Trituradora de Papel 1', 'v_ret_gc_shred', 0},
            {'Trituradora de Papel 2', 'prop_shredder_01', 0},
	    {'Ventilador 1', 'v_res_fa_fan', 0},
	    {'Ventilador 2', 'bkr_prop_weed_fan_floor_01a', 50},
	    {'Servidores 1', 'xm_base_cia_server_01', 0},
	    {'Servidores 2', 'xm_base_cia_server_02', 0},
	    {'Servidores 3', 'hei_prop_mini_sever_01', 0},
	    {'Servidores 4', 'hei_prop_mini_sever_02', 0},
	    {'Servidores 5', 'hei_prop_mini_sever_03', 0},
    },
    ['bed'] = {

	    {'Alomada 1', 'v_res_tre_cushiona', 0},
	    {'Alomada 2', 'v_res_tre_cushionb', 0},
	    {'Alomada 3', 'v_res_tre_cushionc', 0},
	    {'Alomada 4', 'v_res_tre_cushiond', 0},
	    {'Alomada 5', 'v_res_tre_cushnscuzb', 0},
	    {'Alomada 6', 'v_res_tre_cushnscuzd', 0},
	    {'Alomada 7', 'v_res_tt_bedpillow', 0},
	    {'Cama 1', 'gr_prop_bunker_bed_01', 0},
            {'Cama 2', 'v_res_msonbed_s', 0},
	    {'Cama 3', 'p_lestersbed_s', 0},
            {'Cama 4', 'p_mbbed_s', 0}, 
            {'Cama 4', 'v_49_motelmp_bed', 0}, 
	    {'Cama 5', 'p_v_res_tt_bed_s', 0},
            {'Cama 6', 'v_res_mbbed', 0},
            {'Cama 7', 'v_res_d_bed', 0},
            {'Cama 8', 'v_res_tre_bed1', 0},
            {'Cama 9', 'v_res_tre_bed2', 0},
            {'Cama 0', 'v_res_tt_bed', 0},
            {'Cama 11', 'apa_mp_h_bed_double_08', 0},
            {'Cama 12', 'apa_mp_h_bed_double_09', 0},
            {'Cama 13', 'apa_mp_h_bed_with_table_02', 0},
            {'Cama 14', 'apa_mp_h_bed_wide_05', 0},
            {'Cama 15', 'apa_mp_h_yacht_bed_01', 0},
            {'Cama 16', 'apa_mp_h_yacht_bed_02', 0}
    },
    ['sofa'] = {

            {'Sofa Viejo 1', 'v_tre_sofa_mess_a_s', 0},
            {'Sofa Viejo 2', 'v_tre_sofa_mess_b_s', 0},
            {'Sofa Viejo 3', 'v_tre_sofa_mess_c_s', 0},
            {'Sofa Viejo 4', 'prop_ld_farm_chair01', 0},
            {'Sofa Viejo 5', 'prop_ld_farm_couch01', 0},
            {'Sofa Viejo 6', 'prop_ld_farm_couch02', 0},
            {'Sofa Viejo 7', 'prop_rub_couch02', 0},
	    {'Sofa Individual 1', 'v_res_fh_pouf', 0},
	    {'Sofa Individual 2', 'v_res_mbottoman', 0},
	    {'Sofa Individual 3', 'apa_mp_h_stn_foot_stool_02', 0},
	    {'Sofa Individual 4', 'apa_mp_h_stn_foot_stool_01', 0},
	    {'Sofa Individual 5', 'apa_mp_h_stn_sofa_daybed_01', 0},
	    {'Sofa Individual 6', 'apa_mp_h_stn_sofa_daybed_02', 0},
	    {'Sofa Individual 7', 'v_corp_facebeanbag', 0},
	    {'Sofa Individual 8', 'v_corp_facebeanbagb', 0},
	    {'Sofa Individual 9', 'v_corp_facebeanbagc', 0},
	    {'Sofa Individual 0', 'v_corp_facebeanbagd', 0},
	    {'Sofa Individual 11', 'apa_mp_h_stn_chairarm_26', 0},
	    {'Sofa Individual 12', 'v_med_whickerchair1', 0},
	    {'Sofa Individual 13', 'apa_mp_h_yacht_armchair_03', 0},
	    {'Sofa Individual 14', 'v_res_m_armchair', 0},
	    {'Sofa Individual 15', 'prop_couch_sm1_07', 0},
	    {'Sofa Individual 16', 'prop_couch_sm2_07', 0},
	    {'Sofa Individual 17', 'apa_mp_h_stn_chairarm_01', 0},
	    {'Sofa Individual 18', 'apa_mp_h_stn_chairstrip_01', 0},
	    {'Sofa Individual 19', 'apa_mp_h_stn_chairstrip_02', 0},
	    {'Sofa Individual 0', 'apa_mp_h_stn_chairstrip_07', 0},
            {'Sofa Individual 21', 'v_res_mp_stripchair', 0},
	    {'Sofa Individual 22', 'apa_mp_h_stn_chairarm_23', 0},
            {'Sofa Individual 23', 'v_res_d_armchair', 0},
	    {'Sofa Individual 24', 'apa_mp_h_stn_chairstrip_04', 0},
	    {'Sofa Individual 25', 'v_res_fh_singleseat', 0},
	    {'Sofa Individual 26', 'apa_mp_h_yacht_armchair_04', 0},
	    {'Sofa Individual 27', 'apa_mp_h_stn_chairstrip_05', 0},
	    {'Sofa Individual 28', 'apa_mp_h_yacht_armchair_01', 0},
	    {'Sofa Individual 29', 'apa_mp_h_stn_chairstrip_08', 0},
	    {'Sofa Individual 0', 'v_ret_ps_chair', 0},
	    {'Sofa Individual 31', 'apa_mp_h_stn_chairarm_25', 0},
	    {'Sofa Individual 32', 'prop_couch_sm_07', 0},
	    {'Sofa Individual 33', 'bkr_prop_clubhouse_armchair_01a', 0},
	    {'Sofa Individual 34', 'prop_yacht_seat_03', 0},
	    {'Sofa Individual 35', 'prop_yaught_chair_01', 0},
	    {'Sofa Individual 36', 'prop_yacht_seat_01', 0},
	    {'Sofa Mediano 1', 'prop_fib_3b_bench', 0},
            {'Sofa Mediano 2', 'prop_yaught_sofa_01', 0},
            {'Sofa Mediano 3', 'prop_yacht_seat_02', 0},			
            {'Sofa Mediano 4', 'p_yacht_sofa_01_s', 0},
            {'Sofa Mediano 5', 'p_res_sofa_l_s', 0},
            {'Sofa Mediano 6', 'v_res_m_h_sofa_sml', 0},
	    {'Sofa Mediano 7', 'v_res_tre_sofa', 0},
	    {'Sofa Mediano 8', 'apa_mp_h_stn_sofa2seat_02', 0},
	    {'Sofa Mediano 9', 'hei_heist_stn_sofa3seat_01', 0},
	    {'Sofa Mediano 0', 'prop_couch_01', 0},
	    {'Sofa Mediano 11', 'prop_couch_sm_06', 0},
	    {'Sofa Grande 1', 'prop_couch_lg_06', 0},
	    {'Sofa Grande 2', 'prop_couch_lg_07', 0},
	    {'Sofa Grande 3', 'hei_heist_stn_sofa3seat_02', 0},
	    {'Sofa Grande 4', 'hei_heist_stn_sofa2seat_03', 0},
	    {'Sofa Grande 5', 'hei_heist_stn_sofa3seat_06', 0},	
	    {'Sofa Grande 6', 'p_v_med_p_sofa_s', 0},
	    {'Sofa Grande 7', 'bkr_prop_clubhouse_sofa_01a', 0},
	    {'Sofa Grande 8', 'ex_mp_h_off_sofa_01', 0},
	    {'Sofa Grande 9', 'ex_mp_h_off_sofa_02', 0},
	    {'Sofa Grande 0', 'ex_mp_h_off_sofa_03', 0},
	    {'Sofa Grande 11', 'apa_mp_h_yacht_sofa_01', 0},
	    {'Sofa Cama 1', 'prop_t_sofa_02', 0},
            {'Sofa Cama 2', 'prop_t_sofa', 0}, 
	    {'Sofa en L 1', 'p_lev_sofa_s', 0},
            {'Sofa en L 2', 'v_ilev_m_sofa', 0},
	    {'Sofa en L 3', 'apa_mp_h_stn_sofacorn_01', 0},
	    {'Sofa en L 4', 'apa_mp_h_stn_sofacorn_05', 0},
	    {'Sofa en L 5', 'apa_mp_h_stn_sofacorn_06', 0},
	    {'Sofa en L 6', 'apa_mp_h_stn_sofacorn_07', 0},
	    {'Sofa en L 7', 'apa_mp_h_stn_sofacorn_08', 0},
	    {'Sofa en L 8', 'apa_mp_h_stn_sofacorn_09', 0},
	    {'Sofa en L 9', 'apa_mp_h_stn_sofacorn_0', 0},
	    {'Sofa en L 0', 'v_res_mp_sofa', 0},
	    {'Sofa en L 11', 'v_res_fh_sofa', 0},
	    {'Sofa en L 12', 'p_lev_sofa_s', 0},

    },
    ['Plants'] = {


	    {'Flores 1', 'v_res_mflowers', 0},
	    {'Flores 2', 'v_ret_flowers', 0},
	    {'Flores 3', 'apa_mp_h_acc_vase_flowers_01', 0},
	    {'Flores 4', 'apa_mp_h_acc_vase_flowers_02', 0},
	    {'Flores 5', 'hei_heist_acc_flowers_01', 0},
	    {'Flores 6', 'v_ret_ps_flowers_01', 0},
	    {'Flores 7', 'v_ret_ps_flowers_02', 0},
	    {'Flores 8', 'v_res_fh_flowersa', 0},
	    {'Flores 9', 'v_ret_j_flowerdisp', 0},
	    {'Flores 0', 'v_ret_j_flowerdisp_white', 0},
	    {'Flores 11', 'apa_mp_h_acc_vase_flowers_03', 0},
	    {'Flores 12', 'v_res_mvasechinese', 0},
	    {'Flores 13', 'apa_mp_h_acc_vase_flowers_04', 0},
	    {'Planta Colgante 1', 'prop_pot_plant_6a', 0},
	    {'Planta Colgante 2', 'prop_pot_plant_6b', 0},
	    {'Planta 1', 'prop_plant_int_04a', 0},
	    {'Planta 2', 'prop_fib_plant_01', 0},
	    {'Planta 3', 'v_res_rubberplant', 0},
	    {'Planta 4', 'v_res_tre_plant', 0},
	    {'Planta 5', 'v_res_m_urn', 0},
	    {'Planta 6', 'v_med_p_planter', 0},
            {'Planta 7', 'v_res_mplanttongue', 0},
	    {'Planta 8', 'prop_plant_int_01a', 0},
	    {'Planta 9', 'prop_plant_int_01b', 0},
	    {'Planta 0', 'prop_plant_int_02a', 0},
	    {'Planta 11', 'prop_plant_int_02b', 0},
	    {'Planta 12', 'v_corp_bombplant', 0},
	    {'Planta 13', 'v_res_tre_tree', 0},
	    {'Planta 14', 'prop_pot_plant_01a', 0},
	    {'Planta 15', 'prop_pot_plant_01c', 0},
	    {'Planta 16', 'prop_pot_plant_01d', 0},
	    {'Planta 17', 'prop_pot_plant_01e', 0},
	    {'Planta 18', 'prop_pot_plant_05a', 0},
	    {'Planta 19', 'prop_pot_plant_05b', 0},
            {'Planta 0', 'p_int_jewel_plant_02', 0},
            {'Planta 21', 'p_int_jewel_plant_01', 0},
            {'Planta 22', 'prop_fbibombplant', 0},
            {'Planta 23', 'prop_fib_plant_02', 0},
            {'Planta 24', 'prop_plant_int_03b', 0},
            {'Planta 25', 'prop_plant_int_04b', 0},
            {'Planta 26', 'prop_pot_plant_01b', 0},
            {'Planta 27', 'prop_pot_plant_01a', 0},
            {'Planta 28', 'prop_pot_plant_03c', 0},
	    {'Helecho 1', 'prop_plant_int_04c', 0},
	    {'Helecho 2', 'prop_plant_int_03a', 50},
	    {'Helecho 3', 'prop_plant_int_03c', 50},
	    {'Palma 1', 'v_res_m_bananaplant', 0},
	    {'Palma 2', 'v_res_m_palmplant1', 0},
	    {'Palma 3', 'v_res_m_palmstairs', 0},
	    {'Arbol 1', 'prop_prop_tree_01', 0},
	    {'Arbol 2', 'prop_plant_int_06b', 0},
	    {'Plantas en Macetero Grande 1', 'prop_pot_plant_02a', 0},
	    {'Plantas en Macetero Grande 2', 'prop_pot_plant_04b', 0},
	    {'Plantas en Macetero Grande 3', 'prop_pot_plant_02b', 0},
	    {'Plantas en Macetero Grande 4', 'prop_pot_plant_02c', 0},
	    {'Plantas en Macetero Grande 5', 'prop_pot_plant_04c', 0},
	    {'Plantas en Macetero Grande 6', 'prop_plant_int_05a', 0},
	    {'Plantas en Macetero Grande 7', 'prop_plant_interior_05a', 0},
	    {'Plantas en Macetero Grande 8', 'prop_plant_int_05b', 0},
	    {'Plantas en Macetero Grande 9', 'prop_plant_int_06a', 0},
	    {'Plantas en Macetero Grande 0', 'prop_pot_plant_04a', 0},
            {'Centro', 'prop_ld_dstplanter_01', 0},

    },
    ['CashGoldJewels'] = {
            {'Caja de dinero', 'prop_cash_case_02', 0},
            {'Caja de dinero 2', 'prop_cash_crate_01', 0},
            {'Caja de dinero 3', 'hei_prop_cash_crate_half_full', 0},
            {'Nota dinero', 'prop_anim_cash_note_b', 0},
            {'Pila de dinero', 'prop_anim_cash_pile_01', 0},
            {'Carro de dinero', 'prop_cash_trolly', 0},
            {'Carro de dinero 2', 'prop_poly_bag_money', 0},
            {'Carro de oro completo', 'prop_gold_trolly_full', 0},
            {'Carro de oro', 'prop_gold_trolly', 0},
            {'Barra de oro 2', 'prop_gold_bar', 0},
            {'Barra grande de oro', 'prop_large_gold', 0},
            {'Barra grande de oro 2', 'p_large_gold_s', 0},
            {'Cofre de oro', 'prop_ld_gold_chest', 0},
            {'Petita de oro', 'prop_peyote_gold_01', 0},
            {'Joya 1', 'prop_jewel_03b', 0}, 
	    {'Joya 2', 'prop_jewel_04b', 0},
            {'Joya 3', 'prop_jewel_02b', 0},
            {'Joya 4', 'prop_jewel_pickup_new_01', 0},
            {'Joya 5', 'prop_jewel_04b', 0}, 

    },
    ['Drugs'] = {
            {'Drogas 1', 'prop_weed_pallet', 0},
            {'Drogas 2', 'hei_prop_hei_drug_pack_01b', 0},
            {'Drogas 3', 'hei_prop_hei_drug_pack_01a', 0},
            {'Drogas 4', 'hei_prop_hei_drug_pack_02', 0},
            {'Drogas 5', 'hei_prop_heist_drug_tub_01', 0},
            {'Drogas 6', 'ng_proc_drug01a02', 0},
            {'Drogas 7', 'prop_drug_bottle', 0},
            {'Drogas 8', 'hei_prop_hei_drug_case', 0},
            {'Drogas 9', 'prop_drug_burner', 0},
            {'Drogas 0', 'prop_drug_erlenmeyer', 0},
            {'Drogas 11', 'prop_drug_package', 0},
            {'Drogas 12', 'prop_drug_package_02', 0},
            {'Drogas 13', 'prop_mp_drug_package', 0},
            {'Drogas 14', 'prop_mp_drug_pack_blue', 0},
            {'Drogas 15', 'prop_mp_drug_pack_red', 0},
            {'Drogas 16', 'prop_coke_block_01', 0},
            {'Drogas 17', 'prop_coke_block_half_a', 0},
            {'Drogas 18', 'p_meth_bag_01_s', 0},
            {'Drogas 19', 'prop_meth_bag_01', 0},
            {'Drogas 0', 'prop_meth_setup_01', 0}
    },

    ['lights'] = {

            {'Lampara de Escritorio 1', 'prop_cd_lamp', 0},
	    {'Lampara de Escritorio 2', 'v_corp_cd_desklamp', 0},
            {'Lampara de Escritorio 3','v_res_desklamp', 0},
	    {'Lampara de Escritorio 4', 'v_ret_gc_lamp', 0},
	    {'Lampara de Escritorio 5', 'apa_mp_h_lit_lamptable_02', 0},
	    {'Lampara de Escritorio 6', 'apa_mp_h_lit_lamptable_14', 0},
	    {'Lampara de Mesa 1', 'v_res_d_lampa', 0},
	    {'Lampara de Mesa 2', 'v_res_fa_lamp1on', 0},
	    {'Lampara de Mesa 3', 'v_res_fh_lampa_on', 0},
	    {'Lampara de Mesa 4', 'v_res_j_tablelamp1', 0},
	    {'Lampara de Mesa 5', 'v_res_j_tablelamp2', 0},
	    {'Lampara de Mesa 6', 'v_res_mdbedlamp', 0},
	    {'Lampara de Mesa 7', 'v_res_mtblelampmod', 0},
	    {'Lampara de Mesa 8', 'v_res_m_lamptbl', 0},
            {'Lampara de Mesa 9', 'hei_prop_hei_bnk_lamp_02', 0},
            {'Lampara de Mesa 0', 'hei_prop_hei_bnk_lamp_01', 0},
            {'Lampara de Mesa 11', 'v_ilev_fh_lampa_on', 0},
            {'Lampara de Mesa 12', 'prop_construcionlamp_01', 0},
            {'Lampara de Mesa 13', 'prop_oldlight_01c', 0},
            {'Lampara de Mesa 14', 'prop_recycle_light', 0},
            {'Lampara de Mesa 15', 'apa_mp_h_lit_lamptable_05', 0},
            {'Lampara de Mesa 16', 'apa_mp_h_lit_lamptable_04', 0},
            {'Lampara de Mesa 17', 'apa_mp_h_lit_lamptable_09', 0},
            {'Lampara de Mesa 18', 'apa_mp_h_lit_lamptable_17', 0},
            {'Lampara de Mesa 19', 'apa_mp_h_lit_lamptable_21', 0},
            {'Lampara de Mesa 0', 'apa_mp_h_lit_lamptablenight_16', 0},
            {'Lampara de Mesa 21', 'apa_mp_h_lit_lamptablenight_24', 0},
	    {'Lampara de Piso 1', 'v_res_fh_floorlamp',0},
	    {'Lampara de Piso 2', 'v_res_m_lampstand', 0},
	    {'Lampara de Piso 3', 'v_res_m_lampstand2', 50},
	    {'Lampara de Piso 4', 'v_res_tre_talllamp', 0},
	    {'Lampara de Piso 5', 'apa_mp_h_lit_floorlamp_06', 0},
	    {'Lampara de Piso 6', 'apa_mp_h_lit_floorlamp_0', 0},
	    {'Lampara de Piso 7', 'apa_mp_h_lit_floorlamp_13', 0},
	    {'Lampara de Piso 8', 'apa_mp_h_lit_floorlamp_17', 0},
	    {'Lampara de Piso 9', 'apa_mp_h_lit_floorlampnight_05', 0},
	    {'Lampara de Piso 0', 'apa_mp_h_lit_floorlampnight_07', 0},
	    {'Lampara de Piso 11', 'apa_mp_h_lit_floorlampnight_14', 0},
	    {'Lampara de Piso 12', 'apa_mp_h_floor_lamp_int_08', 0},
	    {'Lampara de Piso 13', 'apa_mp_h_floorlamp_a', 0},
	    {'Lampara de Piso 14', 'apa_mp_h_floorlamp_b', 0},
	    {'Lampara de Piso 15', 'apa_mp_h_floorlamp_c', 0},
	    {'Lampara de Piso 16', 'apa_mp_h_lit_floorlamp_01', 0},
	    {'Lampara de Piso 17', 'apa_mp_h_lit_floorlamp_02', 0},
	    {'Lampara de Piso 18', 'apa_mp_h_lit_floorlamp_03', 0},
	    {'Lampara de Piso 19', 'apa_mp_h_lit_floorlamp_05', 0},
	    {'Lampara de Piso 0', 'apa_mp_h_yacht_floor_lamp_01', 0},
	    {'Lampara de Techo', 'apa_mp_h_lit_lightpendant_01', 0},
	    {'Lampara de Techo', 'apa_mp_h_lit_lightpendant_05', 0},
	    {'Lampara de Techo', 'apa_mp_h_lit_lightpendant_05b', 0},
	    {'Lampara de Techo', 'ex_mp_h_lit_lightpendant_01', 0},
	    {'Lampara de Techo', 'hei_heist_lit_lightpendant_03', 0},
	    {'Lampara de Techo', 'hei_heist_lit_lightpendant_01', 0},
	    {'Lampara de Techo', 'hei_heist_lit_lightpendant_02', 0},
	    {'Ventilador con Lampara', 'v_res_tre_lightfan', 0},
	    {'Lampara de Pared 1', 'v_ret_fh_walllighton', 0},
            {'Lampara de Pared 2', 'prop_wall_light_02a', 0},
            {'Lampara de Pared 3', 'prop_wall_light_03a', 0},
            {'Lampara de Pared 4', 'prop_wall_light_04a', 0},
            {'Lampara de Pared 5', 'prop_wall_light_05a', 0},
            {'Lampara de Pared 6', 'prop_wall_light_05c', 0},
            {'Lampara de Pared 7', 'prop_chall_lamp_02', 0},
	    {'Luces de Mosaico', 'apa_mp_h_ceiling_light_01_day', 0},
	    {'Luces de Mosaico 1', 'prop_runlight_r', 0},
	    {'Luces de Mosaico 2', 'prop_runlight_y', 0},
	    {'Luces de Mosaico 3', 'prop_runlight_g', 0},
	    {'Luces de Mosaico 4', 'prop_runlight_b', 0},

      },

    ['FoodandDrinks'] = {

	    {'Salero', 'v_res_foodjarb', 0},
	    {'Pimientero', 'v_res_foodjara', 0},
            {'Cacahuetes 1', 'prop_peanut_bowl_01', 0},
            {'Cacahuetes 2', 'prop_bar_beans', 0},
            {'Plato con Limones 1', 'prop_bar_limes', 0},
            {'Plato con Limones 2', 'prop_bar_lemons', 0},
	    {'Panesillos', 'v_res_cakedome', 0},
            {'Bol', 'prop_cs_bowl_01', 0}, 
            {'Fruta 1', 'apa_mp_h_acc_fruitbowl_01', 0},
            {'Fruta 2', 'apa_mp_h_acc_fruitbowl_02', 0},
            {'Fruta 3', 'prop_bar_fruit', 0},
	    {'Fruta 4', 'v_res_fh_fruitbowl', 0},
	    {'Fruta 5', 'v_res_m_woodbowl', 45},
	    {'Fruta 6', 'v_res_mbowlornate', 0},
            {'Cafe', 'p_ing_coffeecup_02', 0},
	    {'Refresco', 'prop_cs_bs_cup', 0},
	    {'Refresco Enlatado 1', 'ng_proc_sodacan_01a', 0},
	    {'Refresco Enlatado 2', 'ng_proc_sodacan_01b', 0},
	    {'Refresco Enbotellado ', 'ng_proc_sodabot_01a', 0},
	    {'Copa con Vino 1', 'p_pour_wine_s', 5},
	    {'Copa con Vino 2', 'p_wine_glass_s', 5},
            {'Caja de cerveza', 'prop_cs_beer_box', 0},
            {'Conjunto de Cerveza 1', 'beerrow_world', 0},
            {'Conjunto de Cerveza 2', 'beerrow_local', 0},
            {'Cerveza 1', 'prop_beer_amopen', 0},
            {'Cerveza 2', 'prop_beer_bottle', 0},
            {'Cerveza 3', 'prop_beer_bison', 0},
            {'Cerveza 4', 'beerrow_world', 0},
            {'Cerveza 5', 'prop_amb_beer_bottle', 0},
            {'Cerveza 6', 'prop_beer_pissh', 0},
            {'Cerveza 7', 'prop_beer_stzopen', 0},
            {'Cerveza 8', 'prop_beer_jakey', 0},
            {'Cerveza 9', 'prop_beer_bar', 0},
            {'Cerveza 0', 'prop_beer_blr', 0},
            {'Cerveza 11', 'prop_beer_logger', 0},
            {'Cerveza 12', 'prop_beer_am', 0},
            {'Cerveza 13', 'prop_beer_patriot', 0},
            {'Cerveza 14', 'prop_sh_beer_pissh_01', 0},
            {'Cerveza 15', 'prop_cs_beer_bot_0oz_02', 0},
            {'Cerveza 16', 'prop_amb_beer_bottle', 0},
            {'Cerveza 17', 'prop_cs_beer_bot_03', 0},
            {'Cerveza 18', 'prop_cs_beer_bot_02', 0},
            {'Cerveza 19', 'prop_cs_beer_bot_01', 0},
            {'Cerveza 0', 'prop_cs_beer_bot_0oz_03', 0},
            {'Cerveza 21', 'prop_cs_beer_bot_0oz', 0},
            {'Vino 1', 'prop_wine_white', 0},
            {'Vino 2', 'prop_wine_red', 0},
            {'Vino 3', 'prop_wine_bot_02', 0},
            {'Vino 4', 'prop_wine_rose', 0},
            {'Vino 5', 'prop_drink_redwine', 0},
            {'Vino 6', 'prop_drink_whtwine', 0},
            {'Vino 7', 'prop_wine_bot_01', 0},
            {'Vino 8', 'winerow', 0},
            {'Comida', 'ng_proc_food_bag01a', 0},
            {'Comida 2', 'prop_food_bs_burg1', 0},
            {'Comida 3', 'prop_food_bs_burg3', 0},
            {'Comida 4', 'prop_food_bs_chips', 0},
            {'Comida 5', 'prop_food_bs_burger2', 0},
            {'Comida 6', 'prop_food_bs_coffee', 0},
            {'Comida 7', 'prop_food_cups1', 0},
            {'Comida 8', 'prop_food_cb_cups01', 0},
            {'Comida 9', 'prop_food_cb_cups02', 0},
            {'Comida 0', 'prop_food_bs_cups02', 0},
            {'Puesto de fruta 1', 'prop_fruit_stand_03', 0},
            {'Puesto de fruta 2', 'prop_fruit_stand_02', 0},
            {'Puesto de fruta 3', 'prop_fruit_stand_01', 0},
            {'Puesto de fruta 4', 'prop_fruit_stand_03', 0},
            {'Puesto de fruta 5', 'prop_fruit_stand_03', 0},
    },
    
      ['kitchen'] = {
	    {'Klinex', 'v_res_tissues', 0},
	    {'Rollo de Papel 1', 'v_ret_ta_paproll', 0},
	    {'Rollo de Papel 2', 'v_ret_ta_paproll2', 0},
	    {'Porta Vasos 1', 'prop_bar_coastbarr', 5},
	    {'Porta Vasos 2', 'prop_bar_coastchamp', 5},
	    {'Porta Vasos 3', 'prop_bar_coastdusc', 5},
	    {'Porta Vasos 4', 'prop_bar_coastmount', 5},
	    {'Copa de Cristal 1', 'prop_sh_wine_glass', 5},
	    {'Copa de Cristal 2', 'lts_prop_wine_glass_s2', 5},
	    {'Shaker 1', 'prop_bar_cockshaker', 5},
	    {'Shaker 2', 'prop_bar_cockshakropn', 5},
	    {'Cafetera 1', 'v_res_r_teapot', 0},
	    {'Cafetera 2', 'prop_coffee_mac_02', 0},
            {'Jarra', 'prop_bar_measrjug', 0},
	    {'Tabla para Picar 1', 'v_res_fa_chopbrd', 0},
	    {'Tabla para Picar 2', 'v_res_mchopboard', 0},
	    {'Utensilios 1', 'prop_utensil', 0},
	    {'Utensilios 2', 'v_res_mutensils', 0},
	    {'Rack de Cuchillos', 'v_res_mkniferack', 0},
	    {'Porta Cuchillos 1', 'v_res_mknifeblock', 0},
	    {'Porta Cuchillos 2', 'prop_knife_stand', 0},
	    {'Taza 1', 'v_res_tt_mug2', 0},
	    {'Taza 2', 'v_ind_cfcup', 0},
	    {'Taza 3', 'v_res_mcofcupdirt', 0},
	    {'Taza 4', 'v_res_fa_potcof', 0},
	    {'Taza 5', 'prop_mug_06', 0},
	    {'Taza 6', 'v_res_mcofcup', 0},
	    {'Taza 7', 'v_ret_ta_mug', 0},
	    {'Taza 8', 'v_res_tt_mug01', 0},
	    {'Taza 9', 'prop_mug_03', 0},
	    {'Platos 1', 'v_res_mkniferack', 0},
	    {'Platos 2', 'prop_plate_02', 0},
	    {'Platos 3', 'prop_plate_01', 0},
	    {'Platos 4', 'v_ret_fh_plate1', 0},
	    {'Platos 5', 'v_res_mplatelrg', 0},
	    {'Platos 6', 'v_res_tt_bowlpile02', 0},
	    {'Platos 7', 'v_res_mplatesml', 0},
	    {'Platos 8', 'v_res_tt_plate01', 0},
	    {'Platos 8', 'v_res_tt_bowlpile01', 0},
	    {'Rallador', 'v_res_fa_grater', 0},
            {'Cuchillo', 'prop_cleaver', 0},
	    {'Moledora', 'v_res_pestle', 0},
	    {'Cazuela 1', 'v_ret_fh_pot01', 0},
	    {'Cazuela 2', 'v_ret_fh_pot02', 0},
	    {'Cazuela 3', 'prop_pot_03', 0},
	    {'Cazuela 4', 'prop_pot_04', 0},
	    {'Sarten 1', 'prop_pot_05', 0},
	    {'Sarten 2', 'prop_pot_06', 0},
	    {'Sarten 3', 'prop_wok', 0},
	    {'Sarten 4', 'prop_kitch_pot_fry', 0},
	    {'Sarten 4', 'v_res_tt_pot02', 0},
	    {'Procesador de Comida', 'prop_foodprocess_01', 0},
            {'Juego de Cocina', 'prop_pot_rack', 0},
	    {'Porta Toalla', 'prop_bar_napkindisp', 0},
            {'Bascula 1', 'bkr_prop_coke_scale_01', 0},
	    {'Bascula 2', 'v_res_m_kscales', 0},
	    {'Tostador 1', 'prop_toaster_01', 0},
	    {'Tostador 2', 'prop_toaster_02', 0},
	    {'Batidora', 'v_res_tre_mixer', 0},
	    {'Cafetera Electrica 1', 'prop_cs_kettle_01', 0},
	    {'Cafetera Electrica 2', 'prop_kettle', 0},
	    {'Exprimidor de Jugos', 'prop_kitch_juicer', 0},
	    {'Dispensador de Helados', 'prop_slush_dispenser', 0},
	    {'Dispensador de refresco 1', 'prop_food_bs_soda_02', 0},
	    {'Dispensador de refresco 2', 'prop_food_cb_soda_01', 0},
	    {'Dispensador de refresco 3', 'prop_food_bs_soda_01', 0},
	    {'Dispensador de refresco 4', 'prop_food_cb_soda_02', 0},
	    {'Dispensador de Cerveza 1', 'prop_bar_pump_06', 0},
	    {'Dispensador de Cerveza 2', 'prop_bar_pump_08', 0},
	    {'Dispensador de Cerveza 3', 'prop_bar_pump_07', 0},
	    {'Dispensador de Cerveza 4', 'prop_bar_pump_05', 0},
	    {'Dispensador de hielo', 'prop_bar_ice_01', 0},
	    {'Dispensador de cafe 1', 'hei_heist_kit_coffeemachine_01', 0},
            {'Dispensador de cafe 2', 'apa_mp_h_acc_coffeemachine_01', 0},
	    {'Dispensador de cafe 3', 'ex_mp_h_acc_coffeemachine_01', 0},
	    {'Dispensador de cafe 4', 'prop_coffee_mac_01', 0},
	    {'Dispensador de cafe 5', 'prop_tea_urn', 0},
	    {'Microondas 1', 'prop_micro_01', 0},
	    {'Microondas 2', 'prop_micro_02', 50},
	    {'Microondas 3', 'prop_micro_04', 0},
	    {'Microondas 4', 'prop_microwave_1', 0},
	    {'Frigobar de Cervezas', 'prop_bar_fridge_03', 0},
	    {'Doble Frigobar de Cervezas', 'ba_prop_battle_bar_fridge_02', 0},
	    {'Refrigerador de Vinos', 'ba_prop_battle_bar_fridge_01', 0},
	    {'Refrigerador de Cerveza', 'ba_prop_battle_bar_beerfridge_01', 0},
	    {'Estufa 1', 'v_res_ovenhobmod', 0},
	    {'Estufa 2', 'prop_cooker_03', 0},
	    {'Azador 1', 'prop_bbq_4', 0},
	    {'Azador 1', 'prop_bbq_5', 0},
	    {'Azador 2', 'prop_bbq_1', 0},	
            {'Taburete de cocina', 'v_ilev_fh_kitchenstool', 0},
            {'Azador de Trompo', 'prop_kebab_grill', 0},
            {'Trolly', 'hei_prop_hei_cash_trolly_03', 0},
            {'Mesa de Acero', 'prop_ff_counter_03', 0},
            {'Mesa de Acero', 'prop_ff_counter_02', 0},
            {'Contenedor de Comida 1', 'prop_food_bs_bshelf', 0},
            {'Contenedor de Comida 2', 'prop_food_cb_bshelf', 0},
            {'Contenedor Acero', 'prop_ff_counter_01', 0},
            {'Anaquel de Acero', 'prop_ff_shelves_01', 0},
            {'Horno de Pizza', 'prop_pizza_oven_01', 0},
	    {'Lavabo 1', 'prop_bar_sink_01', 0},
	    {'Lavabo 2', 'prop_ff_sink_02', 0},
	    {'Lavabo 3', 'prop_sink_04', 0},
            {'Refrigerador 1', 'prop_trailr_fridge', 0},
            {'Refrigerador 2', 'prop_fridge_03', 0},
            {'Refrigerador 3', 'v_res_tre_fridge', 0},
            {'Refrigerador 4', 'prop_fridge_01', 0},
            {'Refrigerador 5', 'v_res_fridgemodsml', 0},
            {'Refrigerador 6', 'v_res_fridgemoda', 0},
	    {'Congelador', 'prop_bar_cooler_01', 0},
	    {'Maquina de Hielos', 'prop_bar_ice_01', 0},
            {'Vend 1', 'prop_vend_fridge01', 0},
            {'Vend 2', 'prop_vend_snak_01', 0},
            {'Vend 3', 'prop_vend_coffe_01', 0},
            {'Vend 4', 'prop_vend_soda_01', 0},
            {'Vend 5', 'prop_vend_soda_02', 0},
            {'Vend 6', 'prop_vend_water_01', 0},
            {'Vend 7', 'prop_watercooler', 0},
    },
    ['bathroom'] = {

            {'Loción1', 'prop_beach_lotion_01', 0},
            {'Loción2', 'prop_beach_lotion_02', 0},
            {'Loción3', 'prop_beach_lotion_03', 0},
            {'Rasuradora', 'prop_clippers_01', 0},
	    {'Espejo', 'p_int_jewel_mirror', 0},
	    {'Dispensador de Jabon 1', 'prop_soap_disp_01', 0},
	    {'Organizador', 'prop_shower_rack_01', 0},
	    {'Secador de Mano 1', 'prop_handdry_01', 0},
	    {'Secador de Mano 2', 'prop_handdry_02', 0},
	    {'Toallera 1', 'prop_towel_rail_01', 0},
	    {'Toallera 2', 'prop_towel_rail_02', 0},
	    {'Toalla 1', 'prop_towel_01', 0},
	    {'Toalla 2', 'v_res_mbtowel', 0},
	    {'Toalla 3', 'v_res_mbtowelfld', 0},
            {'Toalla 4', 'prop_shower_towel', 0},
            {'Toalla 5', 'p_shower_towel_s', 0},
            {'Toalla 6', 'prop_ftowel_08', 0},
	    {'Canasta de Ropa', 'v_res_fh_laundrybasket', 0},
            {'Inodoro 1', 'prop_ld_toilet_01', 0},
            {'Inodoro 2', 'prop_toilet_01', 0},
	    {'Toilet 2', 'prop_toilet_02', 0},
            {'Lavabo 1', 'prop_sink_05', 0},
            {'Lavabo 2', 'prop_sink_06', 0},
            {'Lavabo 3', 'v_res_mbsink', 0},
	    {'Lavabo 4', 'prop_sink_02', 0},
	    {'Lavabo 5', 'prop_ff_sink_01', 0},
	    {'Combo Lavabo/Inodoro', 'v_res_m_sinkunit', 0},
            {'Almacen', 'p_new_j_counter_02', 0},
            {'Bañera 1', 'v_res_mbath', 0},
            {'Bañera 2', 'apa_mp_h_bathtub_01', 0},
	    {'Lavadora', 'prop_washer_02', 0},
	    {'Mini Yacuzzi', 'prop_hottub2', 0},
    },

    ['Bins'] = {

	    {'Bote de Basura 1', 'v_res_mbbin', 0},
	    {'Bote de Basura 2', 'v_ret_csr_bin', 0},
	    {'Bote de Basura 3', 'v_res_tre_bin', 0},
	    {'Bote de Basura 4', 'hei_heist_kit_bin_01', 0},
            {'Bote de Basura 5', 'prop_cs_bin_02', 0},
            {'Bote de Basura 6', 'prop_cs_bin_03', 0},
            {'Bote de Basura 7', 'prop_fbibombbin', 0},
            {'Bote de Basura 8', 'prop_bin_04a', 0},
            {'Bote de Basura 9', 'prop_bin_07a', 0},
            {'Bote de Basura 0', 'prop_bin_06a', 0},
            {'Bote de Basura 11', 'prop_bin_0b', 0},
            {'Bote de Basura 12', 'prop_bin_11b', 0},
            {'Bote de Basura 13', 'prop_bin_11a', 0},
            {'Bote de Basura grande', 'prop_bin_13a', 0},
            {'Bolsa de basura', 'prop_rub_binbag_sd_01', 0},
    },
    ['Storage'] = {
            {'Armario', 'p_cs_locker_01_s', 0, true}, 
            {'Armario 2', 'p_cs_locker_02', 0, true}, 
            {'Armario 3', 'p_cs_locker_01', 0, true}, 
            {'Champ Box', 'prop_champ_box_01', 0},
            {'Caja Fuerte 1', 'prop_ld_int_safe_01', 0, true},
            {'Caja Fuerte 2', 'p_v_43_safe_s', 0, true},
            {'Caja Fuerte 3', 'prop_ld_int_safe_01', 0, true},
            {'Ataud', 'prop_coffin_02b', 0},
    },

    ['weapon'] = {

            {'Tarima de Armamento', 'gr_prop_gr_gunsmithsupl_01a', 0, true},
            {'Tarima de Armamento', 'gr_prop_gr_gunsmithsupl_03a', 0, true},
            {'Tarima de Armamento', 'gr_prop_gr_gunsmithsupl_02a', 0, true},
            {'Tarima de Armamento', 'ex_prop_adv_case_sm_03', 0, true},
            {'Tarima de Armamento', 'ex_prop_crate_ammo_sc', 0, true},
            {'Tarima de Armamento', 'ex_office_swag_guns04', 0, true},
            {'Tarima de Armamento', 'ex_prop_crate_ammo_bc', 0, true},
            {'Tarima de Armamento', 'gr_prop_gr_crates_weapon_mix_01a', 0, true},
            {'Tarima de Armamento', 'gr_prop_gr_crates_sam_01a', 0, true},
            {'Tarima de Armamento', 'gr_prop_gr_crates_rifles_01a', 0, true},
            {'Tarima de Armamento', 'gr_prop_gr_crates_pistols_01a', 0, true},
            {'Cajas de Armamento', 'gr_prop_gr_cratespile_01a', 0, true},
            {'Baul Militar 1', 'ex_prop_adv_case_sm_flash', 0, true},
            {'Baul Militar 2', 'prop_mil_crate_01', 0, true},
            {'Baul Militar 3', 'prop_mil_crate_02', 0, true},
            {'Caja Militar Secreta', 'p_secret_weapon_02', 0, true},
            {'Locker de Armas', 'gr_prop_gr_gunlocker_01a', 0},
            {'Porta Armas 1', 'prop_gun_case_01', 0},
            {'Porta Armas 2', 'prop_gun_case_02', 0},
            {'Porta Armas 3', 'p_gcase_s', 0},
            {'Bidon de Gasolina', 'w_am_jerrycan', 0},
            {'Cadenas', 'prop_cs_leg_chain_01', 0},
            {'Bat', 'w_me_bat', 0},
	    {'Crowbar', 'w_me_crowbar', 0},
	    {'Daga', 'w_me_dagger', 0},
	    {'Cuchillo', 'w_me_knife_01', 0},
	    {'Martillo', 'w_me_hammer', 0},
	    {'Hacha', 'w_me_hatchet', 0},
            {'Granada', 'w_ex_grenadefrag', 0},
            {'Bombas Adhesivas', 'w_ex_pe', 0},
            {'Pistola APP', 'w_pi_appistol', 0},
            {'Pistola de Combate', 'w_pi_combatpistol', 0},
            {'Pistola Pesada', 'w_pi_heavypistol', 0},
            {'Pistola', 'w_pi_pistol', 0},
            {'Pistola .0', 'w_pi_pistol0', 0},
            {'Pistola SNS', 'w_pi_sns_pistol', 0},
            {'SMG de Asalto', 'w_sb_assaultsmg', 0},
            {'Micro SMG', 'w_sb_microsmg', 0},
            {'SMG', 'w_sb_smg', 0},
            {'Escopeta de Asalto', 'w_sg_assaultshotgun', 0},
            {'Escopeta Bullup', 'w_sg_bullpupshotgun', 0},
            {'Escopeta Pesada', 'w_sg_heavyshotgun', 0},
            {'Escopeta de Bombeo', 'w_sg_pumpshotgun', 0},
            {'Escopeta Recortada', 'w_sg_sawnoff', 0},
            {'Pistola SNS', 'w_pi_sns_pistol', 0},
            {'MG', 'w_mg_mg', 0},
            {'Combat MG', 'w_mg_combatmg', 0},
            {'Rifle de Asalto', 'w_ar_assaultrifle', 0},
            {'Carabina', 'w_ar_carbinerifle', 0},
            {'Rifle Bullup', 'w_ar_bullpuprifle', 0},
            {'Carabina Especial', 'w_ar_specialcarbine', 0},
            {'Rifle Avanzado', 'w_ar_advancedrifle', 0},
            {'Rifle de Tirador', 'w_sr_marksmanrifle', 0},
            {'Rifle Francotirador', 'w_sr_sniperrifle', 0},
            {'Rifle Francotirador Pesado', 'w_sr_heavysniper', 0},
            {'Lanza Granadas', 'w_lr_grenadelauncher', 0},
            {'RPG', 'w_lr_rpg', 0},
            {'Lanza Misiles', 'w_lr_homing', 0},
            {'Chaleco Antibalas 1', 'prop_bodyarmour_02', 0},
            {'Chaleco Antibalas 2', 'prop_bodyarmour_03', 0},
            {'Chaleco Antibalas 3', 'prop_bodyarmour_04', 0},
            {'Chaleco Antibalas 4', 'prop_bodyarmour_05', 0},
            {'Chaleco Antibalas 5', 'prop_armour_pickup', 0},
            {'Chaleco Antibalas 6', 'prop_bodyarmour_06', 0},
            {'Tortura', 'prop_torture_01', 0},
            {'Sangre 1', 'prop_jet_bloodsplat_01', 0},
            {'Sangre 2', 'p_bloodsplat_s', 0},
            {'Cuerpo', 'prop_water_corpse_01', 0},
            {'Cuerpo', 'prop_water_corpse_02', 0},
            {'Cuerpo', 'xm_prop_body_bag', 0},
            {'Cuerpo Mutilado', 'v_ilev_body_parts', 0},
            {'Mesa de Trabajo 1', 'gr_prop_gr_bench_02a', 0},
            {'Mesa de Trabajo 2', 'gr_prop_gr_bench_02b', 0},
            {'Mesa de Trabajo 3', 'gr_prop_gr_bench_04a', 0},
            {'Mesa de Trabajo 4', 'gr_prop_gr_bench_04b', 0},
            {'Mesa de Trabajo 5', 'gr_prop_gr_bench_01a', 0},
            {'Mesa de Trabajo 6', 'gr_prop_gr_bench_01b', 0},
            {'Mesa de Trabajo 7', 'gr_prop_gr_bench_03a', 0},
            {'Mesa de Trabajo 8', 'gr_prop_gr_bench_03b', 0},
            {'Maquina CNC 1', 'gr_prop_gr_cnc_01b', 0},
            {'Maquina CNC 2', 'gr_prop_gr_cnc_01c', 0},
            {'Torno 1', 'gr_prop_gr_lathe_01a', 0},
            {'Torno 2', 'gr_prop_gr_lathe_01b', 0},
            {'Torno 3', 'gr_prop_gr_lathe_01c', 0},
            {'Taladro Vertical', 'prop_vertdrill_01', 0},

    },

    ['workbench'] = {

            {'Gabinetes de Herramienta 1', 'imp_prop_tool_cabinet_01a', 0, true},
            {'Gabinetes de Herramienta 2', 'imp_prop_tool_cabinet_01b', 0, true},
            {'Gabinetes de Herramienta 3', 'imp_prop_tool_cabinet_01c', 0, true},
            {'Gabinetes de Herramienta 4', 'imp_prop_tool_chest_01a', 0, true},
            {'Gabinetes de Herramienta 5', 'imp_prop_tool_draw_01a', 0 ,true},
            {'Gabinetes de Herramienta 6', 'imp_prop_tool_draw_01b', 0, true},
            {'Gabinetes de Herramienta 7', 'imp_prop_tool_draw_01c', 0, true},
            {'Gabinetes de Herramienta 8', 'imp_prop_tool_draw_01d', 0, true},
            {'Gabinetes de Herramienta 9', 'imp_prop_tool_draw_01e', 0, true},
            {'Gabinetes de Herramienta 0', 'prop_toolchest_01', 0, true},
            {'Gabinetes de Herramienta 11', 'prop_toolchest_02', 0, true},
            {'Gabinetes de Herramienta 12', 'prop_toolchest_03', 0, true},
            {'Gabinetes de Herramienta 13', 'prop_toolchest_04', 0, true},
            {'Gabinetes de Herramienta 14', 'prop_toolchest_05', 0, true},
            {'Gabinetes de Herramienta 15', 'prop_toolchest_01', 0, true},
            {'Mesa de Trabajo', 'imp_prop_impexp_mechbench', 0,},
            {'Tablero de Herramientas', 'v_ind_cs_toolboard', 0,},
            {'Maquina de Soldar', 'imp_prop_welder_01a', 0, true},
            {'Gato Hidraulico', 'imp_prop_car_jack_01a', 0, true},
            {'Gato Hidraulico 2', 'prop_carjack_l2', 0, true},
            {'Gato Hidraulico 3', 'prop_carjack', 0, true},
            {'Torres de Levante', 'imp_prop_axel_stand_01a', 0, true},
            {'Compresor', 'imp_prop_air_compressor_01a', 0, true},
            {'Compresor 2', 'prop_compressor_01', 0, true},
            {'Compresor 3', 'prop_compressor_03', 0, true},
            {'Balanceadora', 'imp_prop_wheel_balancer_01a', 0, true},
            {'Levanta Motor', 'imp_prop_engine_hoist_02a', 0},
            {'Compresor de Suspension', 'imp_prop_strut_compressor_01a', 0},
            {'Maquina de Sandblast', 'imp_prop_sand_blaster_01a', 0},
            {'Soporte de Transmision', 'imp_prop_transmission_lift_01a', 0},
            {'Caja de Mecanico 1', 'prop_tool_box_04', 0},
            {'Caja de Mecanico 2', 'prop_tool_box_06', 0},
            {'Caja de Mecanico 3', 'prop_tool_box_07', 0},
            {'Caja de Mecanico 4', 'prop_tool_box_05', 0},
            {'Caja de Mecanico 5', 'prop_tool_box_03', 0},
            {'Caja de Mecanico 5', 'prop_tool_box_02', 0},
            {'Caja de Mecanico 6', 'prop_tool_box_01', 0},
	    {'Stilson 1', 'prop_tool_wrench', 0},
	    {'Stilson 2', 'prop_cs_wrench', 0},
	    {'Soplete', 'prop_tool_blowtorch', 0},
	    {'Destornillador 1', 'prop_tool_screwdvr03', 0},
	    {'Destornillador 2', 'prop_tool_screwdvr02', 0},
	    {'Martillo', 'prop_tool_hammer', 0},
	    {'Hacha Contra Incendio', 'prop_tool_fireaxe', 0},
	    {'Pico', 'prop_tool_pickaxe', 0},
	    {'Llave Española 1', 'prop_tool_spanner01', 0},
	    {'Llave Española 2', 'prop_tool_spanner02', 0},
	    {'Llave Adjustable', 'prop_tool_adjspanner', 0},
	    {'Pala de Cavar', 'prop_tool_shovel3', 0},
	    {'Pala de Cavar 2', 'prop_tool_shovel06', 0},
	    {'Pala de Cavar 3', 'prop_tool_shovel', 0},
	    {'Pala de Cavar 4', 'prop_tool_shovel2', 0},
	    {'Pala de Cavar 5', 'prop_tool_shovel4', 0},
	    {'Mazo 1', 'prop_tool_sledgeham', 0},
	    {'Mazo 2', 'prop_tool_mallet', 0},
	    {'Taladro', 'prop_tool_drill', 0},
	    {'Sierra Circular', 'gr_prop_gr_grinder_01a', 0},
	    {'Sierra Electrica', 'prop_tool_consaw', 0},
	    {'Prensa de Banco', 'gr_prop_gr_vice_01a', 0},
	    {'Mesa de Trabajo de Madera 1', 'prop_tool_bench02_ld', 0},
	    {'Mesa de Trabajo de Madera 2', 'prop_tool_bench02', 0},
	    {'Camilla de Mecanico', 'prop_carcreeper', 0},
	    {'Auto Cubierto 1', 'prop_entityxf_covered', 0},
	    {'Auto Cubierto 2', 'prop_jb0_covered', 0},
	    {'Auto Clasico', 'lr_supermod_peyote', 0},
	    {'Auto Deportivo', 'lr_supermod_banshee', 0},


    },
    ['accessory'] = {

            {'Reloj', 'p_watch_02_s', 0}, 
	    {'Reloj 2', 'p_watch_01_s', 0},
            {'Paquete de cigarros', 'p_cigar_pack_02_s', 0},
            {'Paquete de cigarros 2', 'p_fag_packet_01_s', 0},
            {'Cartera', 'prop_ld_wallet_01_s', 0},
            {'Mochila de mano', 'prop_ld_handbag_s', 0},
            {'Mochila', 'prop_m_pack_int_01', 0},
            {'Mochila 2', 'prop_cs_heist_bag_02', 0},
            {'Maleta', 'prop_ld_suitcase_01', 0},
            {'Maleta 1', 'prop_suitcase_01c', 0},
            {'Maleta 2', 'prop_suitcase_01b', 0},
            {'Maleta 3', 'prop_suitcase_01', 0},
            {'Maleta 4', 'prop_suitcase_03b', 0},
            {'Nevera', 'prop_coolbox_01', 0},
            {'Palos de Golf', 'prop_golf_bag_01c', 0},
            {'Bolsa de nigel', 'prop_nigel_bag_pickup', 0},
            {'Gorras', 'prop_cap_row_01', 0},
            {'Gorras 2', 'prop_cap_row_01b', 0},
            {'Anaquel de Sombreros', 'prop_display_unit_01', 0},
            {'Anaquel de Ropa', 'prop_tshirt_shelf_2', 0},
            {'Anaquel de Ropa', 'prop_tshirt_shelf_2a', 0},
            {'Anaquel de Ropa', 'prop_tshirt_shelf_2b', 0},
            {'Anaquel de Ropa', 'prop_tshirt_shelf_2c', 0},
            {'Anaquel de Ropa', 'prop_tshirt_shelf_1', 0},
            {'Stripper pole', 'prop_strip_pole_01', 0},
    },
}