Strings = {
    -- blips
    ["purchasable_house"] = "Casa Comprable",
    ["owned_house"] = "Casas Adquiridas",
    ["access_house"] = "Casas para las que Tienes Llave",
    ["purchased_house"] = "Casa de Alguien",

    ["purchasable_apartment"] = "Departamento Comprable",
    ["owned_apartment"] = "Departamento Adquirido",
    ["access_apartment"] = "Departamento para las que Tienes Llave",
    ["purchased_apartment"] = "Departamento de Alguien",

    ["ikea"] = "IKEA",
    ["robbery"] = "Robo",

    -- text for buttons
    ["buy_house"] = "Presiona ~INPUT_CONTEXT~ para comprar ~b~%s~s~ (#%s) por ~g~$%s~s~.",
    ["contact_rea"] = "Presiona ~INPUT_CONTEXT~ para previsualizar %s [#%s]",
    ["contact_rea_nopreview"] = "Contacta al Vendedor para Comprar esta Propiedad.",
    ["enter"] = "Presiona ~INPUT_CONTEXT~ para entrar a tu Propiedad.",
    ["door"] = "Presiona ~INPUT_CONTEXT~ para abrir el menu de la Puerta (%s)",
    ["enter_ikea"] = "Presiona ~INPUT_CONTEXT~ para entrar a IKEA.\nPress   ~INPUT_DETONATE~para vender tus muebles.",
    ["furnishing"] = "Objeto: %s\nVelocidad: %s ~INPUT_COVER~ ~INPUT_TALK~\nUsar ~INPUT_WEAPON_WHEEL_PREV~ ~INPUT_WEAPON_WHEEL_NEXT~ para mover los muebles arriba/abajo\nUsar ~INPUT_ATTACK~ ~INPUT_AIM~ para girar el objeto\nUsar ~INPUT_CELLPHONE_LEFT~ ~INPUT_CELLPHONE_RIGHT~ ~INPUT_CELLPHONE_UP~ ~INPUT_CELLPHONE_DOWN~ para mover el objeto\nPresiona ~INPUT_DETONATE~ para teletransportar el objeto hacia ati\nPresiona ~INPUT_FRONTEND_RDOWN~ para confirmar.\nPresiona ~INPUT_FRONTEND_RRIGHT~ para cancelar.",
    ["access_storage"] = "Presiona ~INPUT_DETONATE~ para acceder al Almacen.",
    ["press_manage"] = "\nPresiona ~INPUT_DETONATE~ para administrar esta Casa",
    ["enter_garage"] = "Presiona ~INPUT_CONTEXT~ para enter the garage.",
    ["store_garage"] = "Presiona ~INPUT_CONTEXT~ para store the vehicle.",
    ["breach_door"] = "\nPresiona ~INPUT_DETONATE~ para breach the door.",
    ["lockpick_door"] = "\nPresiona ~INPUT_DETONATE~ para lockpick the door.",
    ["pole_dance"] = "Presiona ~INPUT_CONTEXT~ para bailar tubo",
    ["stop_dancing"] = "Presiona ~INPUT_VEH_DUCK~ para parar de bailar",
    ["lap_dance"] = "Presiona ~INPUT_CONTEXT~ para bailar tubo\nPress   ~INPUT_VEH_EXIT~para sentarse",
    ["storage_wardrobe"] = "Almacen o Vestuario",
    ["storage_option"] = "Abrir el Almacen",
    ["wardrobe_option"] = "Abrir el Vestuario",
    ["select_outfit"] = "Selecciona un Vestuario",
    ["lockpicking"] = "Cuando la cerradura se ralentiza, estas cerca de la posición correcta.\nGanzuas disponibles: %s\n\nUsar ~INPUT_CELLPHONE_LEFT~ ~INPUT_CELLPHONE_RIGHT~ para girar la cerradura\n~INPUT_FRONTEND_RDOWN~ Desbloquear\n~INPUT_FRONTEND_RRIGHT~ Cancelar",

    -- ikea
    ["viewing_furniture"] = "Navegar ~r~%s~s~.\nUsar ~INPUT_REPLAY_BACK~ ~INPUT_REPLAY_ADVANCE~ para cambiar objeto.\nUsar ~INPUT_REPLAY_FFWD~ ~INPUT_REPLAY_REWIND~ para cambiar categoria.\nUsar ~INPUT_MOVE_LEFT_ONLY~ ~INPUT_MOVE_RIGHT_ONLY~ para girar el objeto.\nUsar ~INPUT_MOVE_UP_ONLY~ ~INPUT_MOVE_DOWN_ONLY~ para enfocar.%s\nPresiona ~INPUT_FRONTEND_RDOWN~ para comprar ~b~%s~s~ por ~g~$%s~s~.\nPresiona ~INPUT_FRONTEND_RRIGHT~ para salir de IKEA.",
    ["confirm_purchase"] = "Comprar ~b~%s~s~ por ~g~$%s~s~?\n\n~INPUT_FRONTEND_RDOWN~ Comprar\n~INPUT_FRONTEND_RRIGHT~ Cancelar",
    ["purchased"] = "Compraste %s por ~g~$%s~s~.",
    ["storage"] = "\nPuedes Almacenar cosas en este Articulo.",

    -- locked state
    ["locked"] = "Bloqueado",
    ["unlocked"] = "Desbloqueado",
    
    -- text for menus 
    ["house_key"] = "Llaves de Casa",
    ["door_menu"] = "Acciones",
    ["toggle_lock"] = "Bloquear / Desbloquear",
    ["exit"] = "Salir",
    ["furnish"] = "Amueblear",
    ["put_furniture"] = "Colocar Muebles",
    ["manage_furniture"] = "Administrar Muebles",
    ["amount_furniture"] = "x%s %s",
    ["confirm_house_purchase"] = "Comprar %s por <span style='color:lime'>$%s</span>",
    ["are_you_sure"] = "Comprar %s?",
    ["what_interior"] = "Que interior deseas?",
    ["interior_number"] = "Interior #%s",
    ["remove_furniture"] = "Remover %s?",
    ["inventory"] = "Almacen",
    ["inventory_weapons"] = "Almacen - Armas",
    ["inventory_items"] = "Almacen - Objetos",
    ["black_money"] = "Dinero Sucio: <span style='color:red'>$%s</span>",
    ["cash"] = "Dinero en Efectivo: <span style='color:lime'>$%s</span>",
    ["put"] = "Depositar Objeto",
    ["get"] = "Retirar Objeto",
    ["deposit"] = "Depositar",
    ["withdraw"] = "Retirar",
    ["weapons"] = "Armas",
    ["items"] = "Objetos",
    ["amount_of"] = "Cantidad de %s?",
    ["make_key_copy"] = "Hacer copia de tu llave",
    ["resell_house"] = "Vender la propiedad por <span style='color:lime'>$%s</span>",
    ["kick_someone_out"] = "Correr a alguien afuera",
    ["kick_out?"] = "Correr afuera %s?",
    ["kick_out"] = "Correr afuera %s",
    ["preview"] = "Vista previa de posibles Interiores",
    ["previewing"] = "~h~Vista previa de interiores\n\n~h~Visualizando el interior %s de %s posibles.\nUse ~INPUT_CELLPHONE_LEFT~ ~INPUT_CELLPHONE_RIGHT~ para visualizar otro interior\nPresiona ~INPUT_FRONTEND_RRIGHT~ para detener la previsualizacion.",
    ["previewing_nohelp"] = "~h~Visualizando la Casa~h~\nContacta al Encargado de Bienes Raices para comprar esta Casa.\nPresiona ~INPUT_FRONTEND_RRIGHT~ para detener la previsualizacion.",
    ["transfer_house"] = "Transferir Propiedad",
    ["transfer_property"] = "Transferir propiedad a %s?",
    ["none_nearby"] = "No hay nadie cerca",
    ["yes"] = "Si",
    ["no"] = "No",
    ["no_outfits"] = "No tienes ninguna Vestimenta Guardada.",
    ["confirm_delete"] = "Borrar Vestimenta \"%s\"?",
    ["equip_outfit"] = "Equipar Vestimenta",
    ["delete_outfit"] = "Borrar Vestimenta",

    -- text for notifications
    ["no_spawn"] = "No se pude encontrar una ubicacion para la casa/departamento.\n\nDigale al dueño del servidor que agregue mas ubicaciones",
    ["error_locked"] = "No pudiste entrar a la casa / departamento - La puerta esta bloqueada.",
    ["not_near_door"] = "No estas cerca de la puerta y por lo tanto, no puedes bloquearla / desbloquearla.",
    ["must_be_number"] = "Debes ingresar un número.",
    ["dont_have"] = "No tienes demasiados.",
    ["not_enough"] = "No hay suficiente en el Almacen.",
    ["cant_carry"] = "No puedes cargar tanto.", 
    ["has_items"] = "Este mueble tiene objetos en el, y por lo tanto no puedes eliminarlo. Asegurate de vaciar el almacen!",
    ["someone_in_house_cant_sell"] = "Alguien esta en la Casa - No puedes venderla ahora!",
    ["cant_own_more"] = "No puedes tener más propiedades.",
    ["no_lockpicks"] = "No tienes Ganzuas.",
    ["robbery_progress"] = "ALERTA!! Alguien esta robando la casa! Checa tu GPS!",
    ["you_got_kicked"] = "Te han corrido de la casa.",
    ["house_spawned_transfer"] = "Alguien esta adentro, No puedes transferir la propiedad.",
    ["nolonger_nearby"] = "El jugador ya no esta cerca.",
    ["nearby_storage"] = "Alguien esta cerca, y por lo tanto no puedes acceder al Almacen.",
    ["locked_door"] = "Has bloqueado la puerta",
    ["unlocked_door"] = "Has desbloqueado la puerta",

    -- text for loading
    ["purchasing"] = "Comprando",
    ["removing_furniture"] = "Removiendo Muebles",
    ["loading_object"] = "Cargando Objetos",
    ["loading_storage"] = "Cargando Almacen",

    -- other
    ["rotation"] = "Rotación: %s",
    ["not_enough_cops"] = "No hay suficientes policias en Servicio!",
}