local Vehicles = {
---Normales---
{label = "Nissan 180sx", spawnName = "180sx"},
{label = "Toyota Tundra", spawnName = "19tundra"},
{label = "Alfa Romeo 4c", spawnName = "4c"},
{label = "Ducati 999", spawnName = "999"},
{label = "Audi A4", spawnName = "aaq4"},
{label = "Volkswagen Amarok", spawnName = "amarok"},
{label = "Avarus", spawnName = "Avarus"},
{label = "Bifta", spawnName = "Bifta"},
{label = "Toyota Hilux", spawnName = "bison2"},
{label = "buccaneer", spawnName = "buccaneer2"},
{label = "Corvette C7", spawnName = "C7"},
{label = "Corvette C8", spawnName = "C8"},
{label = "Toyota Camry", spawnName = "camry55"},
{label = "Carbonizzare", spawnName = "Carbonizzare"},
{label = "Honda CBR", spawnName = "cbrrr"},
{label = "Porsche Carrera GT", spawnName = "CGT"},
{label = "Grand Cherokee", spawnName = "cherokee1"},
{label = "Honda Civic", spawnName = "civic"},
{label = "Renaul Clio", spawnName = "clio"},
{label = "Shelby Cobra", spawnName = "cobra"},
{label = "Mini Cooper", spawnName = "cooperworks"},
{label = "Ford Escort Tuning", spawnName = "cos"},
{label = "Defiler", spawnName = "Defiler"},
{label = "Diabolus", spawnName = "Diabolus"},
{label = "Dominator", spawnName = "Dominator"},
{label = "Double-T", spawnName = "Double-T"},
{label = "Dukes", spawnName = "Dukes"},
{label = "Honda Civic EF9", spawnName = "EF9"},
{label = "Esskey", spawnName = "Esskey"},
{label = "EVO 9", spawnName = "evo9mr"},
{label = "Range Rover Evoque", spawnName = "evoque"},
{label = "Subaru WRX", spawnName = "ff4wrx"},
{label = "Ford Mustang", spawnName = "fmgt"},
{label = "Skyline GTR", spawnName = "fnf4r34"},
{label = "Mitsubishi Evo X", spawnName = "fnflan"},
{label = "Eclipse Rally", spawnName = "fnfmits"},
{label = "Ford Focus", spawnName = "focus3"},
{label = "Mercedes Benz 6x6", spawnName = "g63amg6x6"},
{label = "Mercedez Benz G65", spawnName = "g65"},
{label = "Gauntlet", spawnName = "Gauntlet"},
{label = "GB200", spawnName = "GB200"},
{label = "Lexus Gs 350", spawnName = "gs350"},
{label = "Vehiculo Donador", spawnName = "lwhuracan"},
{label = "Vehiculo Donador", spawnName = "m3gtr"},
{label = "GB200", spawnName = "GB200"},
{label = "Eclipse", spawnName = "gsx"},
{label = "Ford GT 2017", spawnName = "gt17"},
{label = "Nissan Gtr", spawnName = "gtr"},
{label = "Hayabusa", spawnName = "hayabusa"},
{label = "Lamborghini Aventador", spawnName = "lp700r"},
{label = "Harley-Davidson V-Rod", spawnName = "hvrod"},
{label = "hermes", spawnName = "hermes"},
{label = "Hotknife", spawnName = "Hotknife"},
{label = "Pegassi Infernus", spawnName = "infernus2se"},
{label = "Innovation", spawnName = "Innovation"},
{label = "issi6", spawnName = "issi6"},
{label = "Itali GTO", spawnName = "Itali GTO"},
{label = "Volkswagen Golf", spawnName = "mkvr32ar"},
{label = "Moonbeam", spawnName = "moonbeam2"},
{label = "Honda CRX SiR 1991", spawnName = "na1"},
{label = "Nightshade", spawnName = "Nightshade"},
{label = "Volkswagen Passat", spawnName = "passat"},
{label = "Patriot", spawnName = "Patriot"},
{label = "Toyota Prius", spawnName = "prius"},
{label = "Porsche Pruf", spawnName = "pruf"},
{label = "Volkswagen Touareg", spawnName = "R50"},
{label = "Ram 2500", spawnName = "Ram 2500"},
{label = "Audi Rs4", spawnName = "rs4"},
{label = "rs4avant", spawnName = "rs4avant"},
{label = "Ruston", spawnName = "Ruston"},
{label = "Mazda Rx3", spawnName = "rx3"},
{label = "Mazda Rx7", spawnName = "Mazda Rx7"},
{label = "McClaren Senna", spawnName = "senna"},
{label = "Audi SQ7", spawnName = "sq72016"},
{label = "Street Z28 Camaro", spawnName = "streetz28"},
{label = "Limosina", spawnName = "Stretch"},
{label = "Taipan", spawnName = "Taipan"},
{label = "Hoonicorn V2", spawnName = "tampa4"},
{label = "Tropos", spawnName = "Tropos"},
{label = "Zenvo 20", spawnName = "ts1"},
{label = "Porche 911 Turbo", spawnName = "turbo33"},
{label = "Ducati V4S", spawnName = "v4sf"},
{label = "Hyundau Veloster N", spawnName = "veln"},
{label = "Voodoo", spawnName = "Voodoo"},
{label = "Windsor 4 Puertas", spawnName = "windsor2"},
{label = "Citroën Xantia", spawnName = "xantiafn"},
{label = "FITITO 600", spawnName = "yFiat595ssA"},
{label = "Yamaha 250", spawnName = "yzf"},
{label = "Hawasaki 1000r", spawnName = "zx10r"},



---vips---
{label = "Challenger", spawnName = "16challenger"},
{label = "Chrysler 300 SRT8", spawnName = "300srt8"},
{label = "Ferrari 488 spider", spawnName = "488s"},
{label = "BMW 645ci", spawnName = "645ci"},
{label = "Duke 690", spawnName = "690r"},
{label = "Alpine 110s", spawnName = "a110s"},
{label = "Audi A6", spawnName = "a6"},
{label = "Africa twin", spawnName = "africat"},
{label = "Aston Martin DBX", spawnName = "asdbx"},
{label = "Audi Quattros", spawnName = "audquattros"},
{label = "Autarch", spawnName = "Autarch"},
{label = "Volkswagen Fox", spawnName = "blista"},
{label = "Blista GTI", spawnName = "blistagp"},
{label = "Bmw M5", spawnName = "bmci"},
{label = "Proyecto BRZ", spawnName = "brz13"},
{label = "Bugatti", spawnName = "bvit"},
{label = "cayenne porsche", spawnName = "cayenne"},
{label = "Koenigsegg CCX", spawnName = "ccx"},
{label = "chry 300", spawnName = "chry300"},
{label = "Cadillac CT5", spawnName = "ct5v"},
{label = "BMW E23", spawnName = "e23"},
{label = "BMW E36", spawnName = "e36prb"},
{label = "Ford F100", spawnName = "fortek"},
{label = "Toyota Fortuner", spawnName = "fortuner"},
{label = "fx50", spawnName = "fx50s"},
{label = "Mercedez g63 6x6", spawnName = "g63amg6x6"},
{label = "h6", spawnName = "h6"},
{label = "Pagani Huayra", spawnName = "huayra"},
{label = "Hustler", spawnName = "Hustler"},
{label = "Seat ibiza", spawnName = "ibiza"},
{label = "Chevrolet Impala", spawnName = "impala"},
{label = "infinity", spawnName = "inf"},
{label = "Jeep 2012", spawnName = "jeep2012"},
{label = "Dinka Jester", spawnName = "Jester"},
{label = "Skoda Joyster", spawnName = "joyster"},
{label = "Potiac Judge", spawnName = "judge"},
{label = "Kamacho", spawnName = "Kamacho"},
{label = "lwhuracan", spawnName = "Iwharacan"},
{label = "m3gtr", spawnName = "m3gtr"},
{label = "Mercedez Benz Macla", spawnName = "macla"},
{label = "Mercedez MB300", spawnName = "mb300sl"},
{label = "Mesa", spawnName = "mesa3"},
{label = "Mercedez Benz Vision Gt", spawnName = "mvisiongt"},
{label = "Kawasaki Ninja", spawnName = "nh2r"},
{label = "Omnis", spawnName = "Omnis"},
{label = "nissantitan", spawnName = "nissantitan17"},
{label = "Porsche Panamera", spawnName = "panamera18"},
{label = "Porsche Turbo S", spawnName = "pts14"},
{label = "Porsche Turbo S", spawnName = "pts21"},
{label = "Dewbauchee", spawnName = "rapidgt4"},
{label = "Riata", spawnName = "rapidgt4"},
{label = "Sandking", spawnName = "Ruston"},
{label = "scirocco", spawnName = "Sandking"},
{label = "Monopatin Electrico", spawnName = "scijo"},
{label = "Ultimate Aero", spawnName = "serv_electricscooter"},
{label = "Stafford", spawnName = "ssc"},
{label = "Streiter", spawnName = "stafford"},
{label = "Tractor", spawnName = "streiter2"},
{label = "Grand Cherokee", spawnName = "Tractor"},
{label = "Trophy Truck", spawnName = "trhawk"},
{label = "Trophy Truck 2", spawnName = "TrophyTruck"},
{label = "Tyrant", spawnName = "TrophyTruck2"},
{label = "Jaguar xfr", spawnName = "xfr"},
{label = "Kawasaki Z1000", spawnName = "z1000"},









}

Citizen.CreateThread(function()
for num,vehicle in ipairs(Vehicles) do
AddTextEntryByHash(GetHashKey(vehicle.spawnName), vehicle.label)
end
end)

