Citizen.CreateThread(function()
    AddTextEntry('amarok', 'Amarok')
    AddTextEntry('ocnetrongt', 'Audi etron')
    AddTextEntry('bermk1', 'Berlingo vieja')
    AddTextEntry('dl2016', 'RAM 1500')
    AddTextEntry('evija', 'Lotus')
    AddTextEntry('fiat600', 'Fiat 600')
    AddTextEntry('fiat1300', 'Fiat 1300')
    AddTextEntry('punto', 'Fiat punto')
    AddTextEntry('ftoro', 'Fiat toro')
    AddTextEntry('fluencetmspec', 'Fluence')
    AddTextEntry('focus3', 'Focus')
    AddTextEntry('focus2003', 'Ford focus viejo')
    AddTextEntry('f100', 'Ford F100')
    AddTextEntry('fescape', 'Ford escape')
    AddTextEntry('fe86', 'Ford escort')
    AddTextEntry('explorer', 'Ford explorer')
    AddTextEntry('f250r', 'F250')
    AddTextEntry('00f350', 'F350')
    AddTextEntry('64ford', 'Ford falcon')
    AddTextEntry('xbgt', 'falcon XBGT')
    AddTextEntry('fiestarbnormal', 'Ford fiesta')
    AddTextEntry('focusrs', 'Ford focus RS')
    AddTextEntry('fusiont', 'Ford fusion')
    AddTextEntry('fordka', 'Ford KA')
    AddTextEntry('mustang68', 'Mustang')
    AddTextEntry('fortwo17', 'Smart')
    AddTextEntry('denali16', 'GMC Sierra')
    AddTextEntry('golf75r', 'Golf RS')
    AddTextEntry('golfmk6', 'Golf MK6')
    AddTextEntry('golqoriginal', 'Gol 95')
    AddTextEntry('hilux2019', 'Hilux 2019')
    AddTextEntry('hondacivictr', 'Onda Civic')
    AddTextEntry('crv', 'Honda CRV')
    AddTextEntry('hs2000', 'HS 2000')
    AddTextEntry('745le', 'BMW 745')
    AddTextEntry('loweye', 'Chevrolet LOW')
    AddTextEntry('m720', 'Mc Laren 720')
    AddTextEntry('mk4', 'Golf MK4')
    AddTextEntry('daduster', 'Duster')
    AddTextEntry('parselx', 'Peugeot 405')
    AddTextEntry('passat', 'Passat')
    AddTextEntry('pcmansory', 'Cayenne turbo')
    AddTextEntry('504', 'Peugeot 504')
    AddTextEntry('206RPS16', 'Peugeot 206')
    AddTextEntry('307c', 'Peugeot 307')
    AddTextEntry('308cc', 'Peugeot 308 CC')
    AddTextEntry('405glx', 'Peugeot 405 GLX')
    AddTextEntry('406', 'Peugeot 406')
    AddTextEntry('yPG205t16A', 'Peugeot 205')
    AddTextEntry('polo2018', 'Polo 2018')
    AddTextEntry('rrst', 'Range Rover')
    AddTextEntry('renault4', 'Renault 4')
    AddTextEntry('fusilade', 'Renault 11')
    AddTextEntry('renault16', 'Renault 16')
    AddTextEntry('capi20', 'Renault capture')
    AddTextEntry('dilettante', 'Clio nuevo')
    AddTextEntry('cliors', 'Clio RS')
    AddTextEntry('clio', 'Clio')
    AddTextEntry('kangoo', 'Kangoo')
    AddTextEntry('mers18', 'Megane RS')
    AddTextEntry('twingo', 'TWINGO')
    AddTextEntry('saveirosurf', 'Saveiro')
    AddTextEntry('sjtoyota', 'Land Cruiser')
    AddTextEntry('toy70', 'Corolla')
    AddTextEntry('alfmito', 'Alfa Romeo mito')
    AddTextEntry('aone', 'Aston Martin aone')
    AddTextEntry('vmoda6', 'Audi A6')
    AddTextEntry('evcrs8', 'Audi A8')
    AddTextEntry('audiq2sline', 'Audi Q2S')
    AddTextEntry('rs520', 'Audi RS5 coupe')
    AddTextEntry('rs6abt20', 'Audi RS6')
    AddTextEntry('audsq517', 'Audi SQ5')
    AddTextEntry('m3e36', 'BMW M3')
    AddTextEntry('m422', 'BMW M4')
    AddTextEntry('rmodm4gts', 'BWM M4 GTS')
    AddTextEntry('22m5', 'BMW M5')
    AddTextEntry('m6f13', 'BMW M6')
    AddTextEntry('bmwe70', 'BMW X5M')
    AddTextEntry('z48', 'BMW Z4 coupe')
    AddTextEntry('d35', 'Adventure')
    AddTextEntry('cfmotoz10', 'CANAM')
    AddTextEntry('mesar', 'Canis Mesa')
    AddTextEntry('ccss16', 'Camaro SS')
    AddTextEntry('21ltz', 'Camaro ZL1')
    AddTextEntry('silverado', 'Silverado')
    AddTextEntry('glendale', 'Citroen 2CV')
    AddTextEntry('bermk1', 'Berlingo nueva')
    AddTextEntry('durango18', 'Dodge durango')
    AddTextEntry('trx', 'RAM TRX')
    AddTextEntry('tdf', 'Ferrari F12')
    AddTextEntry('500lGM', 'Fiat500')
    AddTextEntry('mustang19', 'Mustang GT')
    AddTextEntry('project8', 'Jaguar SV')
    AddTextEntry('jeepg', 'Jeep gladiator')
    AddTextEntry('19sorento', 'Kia sorento')
    AddTextEntry('urus', 'URUS')
    AddTextEntry('sclgt63s', 'Mercedes GT63S')
    AddTextEntry('600sl', 'Mercedes 600sl')
    AddTextEntry('gxa45', 'Mercedes A45')
    AddTextEntry('amggtbs', 'Mercedes AMGGT')
    AddTextEntry('e400', 'Mercedes E400 coupe')
    AddTextEntry('4444', 'Mercedes G63 4x4')
    AddTextEntry('gle21', 'Mercedes GLE 63s AMG')
    AddTextEntry('oycmr500', 'Mercedes Maybach')
    AddTextEntry('sl55', 'Mercedes SL55 AMG')
    AddTextEntry('gtr50', 'Nissan GTR')
    AddTextEntry('206cc', 'Peugeot 206 CC')
    AddTextEntry('718gts', 'Porsche 718')
    AddTextEntry('porrs73', 'Porsche 911 carrera')
    AddTextEntry('928gts', 'Porsche 928 GTS')
    AddTextEntry('992Cabriolet4s', 'Porsche 911 2020')
    AddTextEntry('boxster', 'Porsche Boxters')
    AddTextEntry('avalon', 'Toyota avalon')
    AddTextEntry('caprice13', 'Toyota caprice')
    AddTextEntry('gt86lb', 'Toyota GT86')
    AddTextEntry('toyotasj', 'Land Cruiser')
    AddTextEntry('rav4', 'Toyota RAV4')
    AddTextEntry('59911', 'Ferrari 599')
    AddTextEntry('911turbos', '911 Turbo S')
    AddTextEntry('africat', 'Africat Twin')
    AddTextEntry('mv2019', 'Brutale')
    AddTextEntry('banshee87', 'Banshee')
    AddTextEntry('km1000rr', 'BMW 1000rr')
    AddTextEntry('bmws', 'BMWS')
    AddTextEntry('cb500f', 'CB500F')
    AddTextEntry('exciter', 'Exciter')
    AddTextEntry('goldwing', 'Super tenere')
    AddTextEntry('gsxr1000', 'GSXR1000')
    AddTextEntry('hornetrepsol', 'REPSOL')
    AddTextEntry('rc213v', 'REPSOL 2020')
    AddTextEntry('ninja250fi', 'Ninja 250')
    AddTextEntry('bros', 'Nxr 160')
    AddTextEntry('yzfr125', 'Yzfr 125')
    AddTextEntry('cb650fr', 'CB 650')
    AddTextEntry('rmzsm', 'Rmzsm')
    AddTextEntry('smc690', 'SMC 690')
    AddTextEntry('tmsm', 'TMSM')
    AddTextEntry('r1', 'R1')
    AddTextEntry('r25', 'R25')
    AddTextEntry('gtr', 'Nissan GTR')
    AddTextEntry('dk350z', 'dk350z')
    AddTextEntry('cayenne', 'cayenne')
    AddTextEntry('avj', 'Lambo AVJ')
    AddTextEntry('tonkat', 'Toyota tonka')
    AddTextEntry('sl65bs', 'Mercedes AMG 65sl')
    AddTextEntry('f150', 'F150')
    AddTextEntry('jeepreneg', 'Jeep Renegade')
    AddTextEntry('mc300sl', 'Mercedes Clásico')
    AddTextEntry('mercxclass', 'Mercedes 4x4')
    AddTextEntry('raptor2017', 'Raptor 6x6')
    AddTextEntry('titanddi', 'Nissan Titan')
    AddTextEntry('17cliofl', 'Clio')
    AddTextEntry('17mansorypnmr', 'Mansory Panamera')
    AddTextEntry('20blazer', 'Chevrolet blazer')
    AddTextEntry('124spider', 'Ferrari Spider')
    AddTextEntry('206gti', 'Peugeot 206')
    AddTextEntry('306pj', 'Peugeot 306')
    AddTextEntry('307CC', 'Peugeot 307')
    AddTextEntry('amggtr', 'Amg GTR')
    AddTextEntry('asea', 'Moto rappi')
    AddTextEntry('blista', 'Moto rappi')
    AddTextEntry('c10custom', 'Ford Custom')
    AddTextEntry('chevelle1970', 'Chevy')
    AddTextEntry('citytrg', 'Honda City')
    AddTextEntry('cl65', 'Mercedes CL65')
    AddTextEntry('cox2013', 'New Beetle')
    AddTextEntry('fiat500', 'Fiat 500')
    AddTextEntry('fiorino', 'Fiorino')
    AddTextEntry('fnfcivic', 'Honda civic')
    AddTextEntry('fox', 'Fox')
    AddTextEntry('fugitive', 'Fiat Palio')
    AddTextEntry('fuluxt2', 'Gua gua')
    AddTextEntry('fusca', 'Escarabajo')
    AddTextEntry('g632019', 'Mercedes G63')
    AddTextEntry('gls600', 'Mercedes 600')
    AddTextEntry('jetta', 'Vento')
    AddTextEntry('honody', 'Honda Oddisey')
    AddTextEntry('MansoryDBX', 'Aston Martin DBX')
    AddTextEntry('MercedesBenzGSeries', 'Mercedes Benz G Series')
    AddTextEntry('mk7', 'Golf MK7')
    AddTextEntry('mr53', 'Mini Cooper')
    AddTextEntry('PandeMraptor', 'Raptor Pandem')
    AddTextEntry('R50', 'GTR 50')
    AddTextEntry('renaultm', 'Renault Sport')
    AddTextEntry('renmaster', 'Renault master')
    AddTextEntry('rs322', 'Audi RS3')
    AddTextEntry('s2k', 'Honda s2000')
    AddTextEntry('sclkuz', 'Land Cruiser')
    AddTextEntry('supra19', 'Toyota supra 2019')
    AddTextEntry('tempra', 'Fiat tempra')
    AddTextEntry('terrortarga', 'Porsche viejo')
    AddTextEntry('vanzcamaro', 'Camaro')
    AddTextEntry('vespa1', 'Piagio Vespa')
    AddTextEntry('vwt6przemo', 'ABT')
    AddTextEntry('z4bmw', 'BWM Z4')
    AddTextEntry('lwscir', 'Scirocco DRIFT')
    AddTextEntry('demon', 'Dodge demon')
    AddTextEntry('alfmito', 'Alfa Romeo Mito')
    AddTextEntry('500lGM', 'Fiat 500')
    AddTextEntry('10ram', 'Dodge Ram')
    AddTextEntry('saveiroquadrada', 'Saveiro vieja')
    AddTextEntry('uptsi', 'Up')
    AddTextEntry('s63coupe', 'Mercedes S63 coupe')
    AddTextEntry('aaq4', 'Audi A4')
    AddTextEntry('sq72016', 'Audi SQ7')
    AddTextEntry('skyline', 'Nissan Skyline')
    AddTextEntry('srt8', 'Jeep SRT8')
    AddTextEntry('raptor2017', 'Raptor 2017')
    AddTextEntry('MK3', 'MK3')
    AddTextEntry('nissantitan17', 'Titan 17')
    AddTextEntry('golg', 'Gol GTI 95')
    AddTextEntry('panamera17turbo', 'Porsche Panamera Turbo')
    AddTextEntry('rsq8m', 'Audi Q8')
    AddTextEntry('fox', 'Volkswagen Fox')
    AddTextEntry('ram16', 'Dodge Ram 2016')
    AddTextEntry('rs6c8', 'Audi RS6')
    AddTextEntry('trhawk', 'Jeep Hawk')
    AddTextEntry('golf4', 'Golf 4')
    AddTextEntry('rmodx6', 'Audi X6M')
    AddTextEntry('18performante', 'Lamborghini performante')
    AddTextEntry('rmodmustang', 'Mustang')
    AddTextEntry('levante', 'Maseratti')
    AddTextEntry('2015s3', 'Audi S3')
    AddTextEntry('h2m', 'Hummer 2M')
    AddTextEntry('rs7', 'Audi RS7')
    AddTextEntry('habanero', 'Chevrolet Agile')
	AddTextEntry('corsa09', 'Corsa')
    AddTextEntry('savaoriginal', 'Saveiro')
    AddTextEntry('06sx2t', 'KTM')
    AddTextEntry('19tundra', 'Toyota tundra 2019')
    AddTextEntry('bcyfz450', 'YFZ 450')
    AddTextEntry('bikelete', 'Bicimoto')
    AddTextEntry('blazer3', 'Cuatri 450')
    AddTextEntry('blazer4', 'Silla automática')
    AddTextEntry('cb500f', 'CB 500f')
    AddTextEntry('cbr650r', 'CB 650f')
    AddTextEntry('cghonda21', 'Moto honda vieja')
    AddTextEntry('cr85', 'Honda CR80')
    AddTextEntry('CRFRally', 'Moto Dakar')
    AddTextEntry('EC350F', 'Gas Gas')
    AddTextEntry('fz50', 'Suzuki 50')
    AddTextEntry('ge6', 'Honda fit')
    AddTextEntry('gle63sgg', 'Mercedes GLE63S')
    AddTextEntry('hornetagstore', 'Honda drak')
    AddTextEntry('m6prior', 'BMW M6')
    AddTextEntry('RAPTOR150', 'Raptor 150')
    AddTextEntry('razerx3', 'Canam x4')
    AddTextEntry('sadler', 'Hilux 2019')
    AddTextEntry('scijo', 'Scirocco')
    AddTextEntry('serv_electricscooter', 'Monopatín')
    AddTextEntry('srt8', 'Jeep Demonhawk')
    AddTextEntry('tc14', 'Toyota Corolla')
    AddTextEntry('v4sf', 'Ducatti V4')
    AddTextEntry('wave125i', 'Honda Wave')
    AddTextEntry('xt660r', 'Tornado')
    AddTextEntry('yamzr7', 'Yamaha R7')
    AddTextEntry('20s63c', 'Mercedes S63 2020')
    AddTextEntry('65c10', 'Chevrolet 67')
    AddTextEntry('510', 'Fiat 128')
    AddTextEntry('adr8', 'Audi R8')
    AddTextEntry('berlingo', 'Berlingo 2022')
    AddTextEntry('BMWM5CS', 'BMW M5CS')
    AddTextEntry('c5', 'Corvette C5')
    AddTextEntry('cookiers6a', 'Audi S6')
    AddTextEntry('cox2013', 'New Beetle')
    AddTextEntry('ctsv16', 'Cadillac SV16')
    AddTextEntry('cuda', 'Cuda')
    AddTextEntry('demonhawk', 'Jeep demonhawk')
    AddTextEntry('denail21', 'GMC Denali')
    AddTextEntry('durango18', 'Dodge Durango')
    AddTextEntry('dwrangler', 'Rangler')
    AddTextEntry('escalade', 'Cadillac Escalade')
    AddTextEntry('evo10', 'Mitsubishi evo10')
    AddTextEntry('ffrs', 'Ford Focus RS')
    AddTextEntry('fiat', 'Fiat 147')
    AddTextEntry('fox', 'Fox')
    AddTextEntry('fxxkevoTT', 'Evo TT')
    AddTextEntry('gauntletstx', 'Bravado')
    AddTextEntry('gcmcliors2000', 'Clio RS')
    AddTextEntry('GCram1500', 'RAM 1500')
    AddTextEntry('gladiatorf9', 'Jeep Gladiator')
    AddTextEntry('golcl', 'Gol CL')
    AddTextEntry('golf8gti', 'Gol GTI')
    AddTextEntry('GolfR18', 'Gol FR')
    AddTextEntry('GT12', 'Aston Martin GT')
    AddTextEntry('h1', 'Hummer h1')
    AddTextEntry('habanero', 'Agile')
    AddTextEntry('hotwee', 'Escarabajo V2')
    AddTextEntry('ingot', 'Suran')
    AddTextEntry('jettagli', 'Vento GLI')
    AddTextEntry('k5blazer', 'Chevrolet k5')
    AddTextEntry('l90fn', 'Renault Megane')
    AddTextEntry('lfahachi', 'Lexus LFA')
    AddTextEntry('m5f90', 'Audi M5')
    AddTextEntry('masgc', 'Maseratti GC')
    AddTextEntry('monster6x6', 'Monster 6x6')
    AddTextEntry('mst', 'Mustang Shelby')
    AddTextEntry('mt09', 'Yamaha MT09')
    AddTextEntry('nfi8ks', 'BMW I8 super Sport')
    AddTextEntry('p911r', 'Porsche 911 R')
    AddTextEntry('porcgt03', 'Porsche Carrera GT')
    AddTextEntry('r8lms2', 'Audi R8 GT')
    AddTextEntry('r8v10abt', 'Audi ABT')
    AddTextEntry('r35kream', 'GTR 35')
    AddTextEntry('s19tahoe', 'Silverado al piso')
    AddTextEntry('sc20', 'Lamborghini SC20')
    AddTextEntry('sf90', 'Ferrari SF90')
    AddTextEntry('shelby20', 'Mustang Shelby 20')
    AddTextEntry('stratum', 'Onyx')
    AddTextEntry('tannen', 'Tannen')
    AddTextEntry('tantrumf9', 'Charger 70')
    AddTextEntry('teramont', 'Volkswagen Teramont X')
    AddTextEntry('titanh', 'Nissan Titan H')
    AddTextEntry('trailcat', 'Jeep Trailcat')
    AddTextEntry('twizy', 'Renault Twizy')
    AddTextEntry('uptsi', 'UP')
    AddTextEntry('urusvennum', 'Urus venom')
    AddTextEntry('x3def70', 'Defender')
    AddTextEntry('bmwm8', 'Bmw M8')
    AddTextEntry('19raptor', 'Raptor 2019')
    AddTextEntry('benze55', 'Mercedes S63 2020')
    AddTextEntry('civic2022', 'Chevrolet 67')
    AddTextEntry('Evoque', 'Ferrari 812 GTS')
    AddTextEntry('gmcat4', 'Fiat 128')
    AddTextEntry('rnine', 'Audi R8')
    AddTextEntry('robust', 'Focus')
    AddTextEntry('topfoil', 'Berlingo 2022')
    AddTextEntry('4c', 'Mercedes S63 2020')
    AddTextEntry('4runner', 'Chevrolet 67')
    AddTextEntry('14m4f82', 'Ferrari 812 GTS')
    AddTextEntry('17m760i', 'Fiat 128')
    AddTextEntry('22silvlt', 'Audi R8')
    AddTextEntry('335i', 'Focus')
    AddTextEntry('390b21', 'Berlingo 2022')
    AddTextEntry('750licustom', 'BMW M5CS')
    AddTextEntry('22530i', 'Corvette C5')
    AddTextEntry('a45', 'Chevrolet Toretto')
    AddTextEntry('alfieri', 'Audi S6')
    AddTextEntry('bronco2021', 'New Beetle')
    AddTextEntry('civic16', 'Cadillac SV16')
    AddTextEntry('contgt2011', 'Cuda')
    AddTextEntry('audis62021', 'Cuda')
    AddTextEntry('bmwi7', 'Cuda')
    AddTextEntry('panameratbst', 'Cuda')
    AddTextEntry('e2008', 'Mercedes S63 2020')
    AddTextEntry('f350punisher', 'Fiat 128')
    AddTextEntry('f355s', 'Audi R8')
    AddTextEntry('F430SKom', 'Focus')
    AddTextEntry('fatboy', 'Berlingo 2022')
    AddTextEntry('fc13', 'BMW M5CS')
    AddTextEntry('fct', 'Corvette C5')
    AddTextEntry('gallardosuperlb', 'Cadillac SV16')
    AddTextEntry('12q7', 'Mercedes S63 2020')
    AddTextEntry('13fmb302', 'Chevrolet 67')
    AddTextEntry('14r8', 'Ferrari 812 GTS')
    AddTextEntry('16charger', 'Fiat 128')
    AddTextEntry('22front', 'Audi R8')
    AddTextEntry('69nova', 'Focus')
    AddTextEntry('992t', 'Berlingo 2022')
    AddTextEntry('2013LP560', 'BMW M5CS')
    AddTextEntry('amggtbs', 'Corvette C5')
    AddTextEntry('amggts2016', 'Chevrolet Toretto')
    AddTextEntry('aone', 'Audi S6')
    AddTextEntry('audsq517', 'New Beetle')
    AddTextEntry('bcps', 'Cadillac SV16')
    AddTextEntry('c63coupe', 'Cuda')
    AddTextEntry('camry55v6', 'Cycloneex')
    AddTextEntry('cayenneturbo', 'Jeep demonhawk')
    AddTextEntry('cbr650r', 'GMC Denali')
    AddTextEntry('colzr2', 'Dodge Durango')
    AddTextEntry('dbsr', 'Rangler')
    AddTextEntry('esca', 'Cadillac Escalade')
    AddTextEntry('evo9', 'Mitsubishi evo10')
    AddTextEntry('frr', 'Ford Focus RS')
    AddTextEntry('golfr21', 'Fiat 147')
    AddTextEntry('grandgt18', 'Daytona FR')
    AddTextEntry('gtr50', 'Mustang FF')
    AddTextEntry('h1truck', 'Fox')
    AddTextEntry('hummersuv', 'Evo TT')
    AddTextEntry('i815', 'Bravado')
    AddTextEntry('impreza2019', 'Clio RS')
    AddTextEntry('jaguarftype', 'RAM 1500')
    AddTextEntry('jeep2012', 'Jeep Gladiator')
    AddTextEntry('lp610-4', 'Gol CL')
    AddTextEntry('m2f22', 'Gol GTI')
    AddTextEntry('m3tdy', 'Gol FR')
    AddTextEntry('m6f13', 'Aston Martin GT')
    AddTextEntry('m6gc', 'Hummer h1')
    AddTextEntry('m40i', 'Agile')
    AddTextEntry('m135i', 'Harley Davidson Iron')
    AddTextEntry('mcjcw20', 'Escarabajo V2')
    AddTextEntry('merc', 'Peugeot 205')
    AddTextEntry('ingot', 'Suran')
    AddTextEntry('r8v10', 'Jesko 2022')
    AddTextEntry('R50', 'Renault 11')
    AddTextEntry('r82012', 'Vento GLI')
    AddTextEntry('rbgator', 'Chevrolet k5')
    AddTextEntry('rmodbmwm8', 'Renault Megane')
    AddTextEntry('s63w222', 'Lexus LFA')
    AddTextEntry('sti12', 'Audi M5')
    AddTextEntry('Taycans20', 'Bugatti Veyron')
    AddTextEntry('ttrs', 'Maseratti GC')
    AddTextEntry('wycalt', 'Monster 6x6')
    AddTextEntry('x5_radmir', 'Mustang Shelby')
    AddTextEntry('zl12017', 'Yamaha MT09')
    AddTextEntry('zoeesport', 'Mercedes Vision GT')
    AddTextEntry('domscharger', 'Mercedes Vision GT')
    AddTextEntry('cls2015', 'Mercedes Vision GT')
    AddTextEntry('rmodlp570', 'Mercedes Vision GT')
end)